### ISSUE TITLE
unlink is not executed on /etc/shadow.lock

### ISSUE THREAD

**Issue by tpgxyz** [shadow-maint/shadow#10]
Running any user/password manipulating program from shadow package leaves /etc/shadow.lock file, which prevents further actions on user management.

Based on strace output it is visible that unlink is executed on all /etc/{gshadow,group,passwd}.lock
except /etc/shadow.lock when running for example useradd.

https://issues.openmandriva.org/show_bug.cgi?id=1375

**Comment by hallyn** [comment]
Can you show a specific example command which does this, and attach the corresponding strace output?

Where can we find the package source (or some list of the patches applied and build config)?

What MAC systems (i.e. selinux/apparmor/smack/tomoyo/something-custom) are enabled on your system?  Are there any syslog messages pointing to a mac denial for removing the file?

**Comment by tpgxyz** [comment]
Hi,
sources can be found here:
https://abf.io/openmandriva/shadow

Latest log for x86_64 build:
http://file-store.rosalinux.ru/api/v1/file_stores/e57e396d20c9bd2e732f94ab011e3260a62edc52.log?show=true

No MAC system enabled by default.

More information will come soon.

**Comment by itchka** [comment]
strace -o userad_trace /usr/sbin/useradd -m -s /bin/bash -U -G lp,video,wheel,audio pete
[root@localhost /]# ls /etc/*.lock
/etc/shadow.lock
[root@localhost /]# ls /etc/.*.lock
/etc/.pwd.lock
Strace can be found here:-
https://gist.github.com/itchka/e74233afdbd72ff7269f

**Comment by hallyn** [comment]
I cannot reproduce that here (on ubuntu).  Can you run under gdb, stop it at commonio_unlock(), and trace through that?  Also step through commonio_lock and commonio_lock_nowait.

I notice in your strace that your run just does 'open("/etc/shadow.lock")':

open("/etc/shadow.lock", O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW, 0600) = 7
fcntl(7, F_GETFD)                       = 0
fcntl(7, F_SETFD, FD_CLOEXEC)           = 0

It should be create /etc/shadow.lock.$(getpid) and then linking that to /etc/shadow.lock, as in:

7975  open("/etc/shadow.7975", O_WRONLY|O_CREAT|O_EXCL, 0600) = 10
7975  write(10, "7975\0", 5)            = 5
7975  close(10)                         = 0
7975  link("/etc/shadow.7975", "/etc/shadow.lock") = 0
7975  stat("/etc/shadow.7975", {st_mode=S_IFREG|0600, st_size=5, ...}) = 0
7975  unlink("/etc/shadow.7975")        = 0

**Comment by itchka** [comment]
Here is the output of gdb at the various breakpoints requested. gdb reports a syntax error.

https://gist.github.com/itchka/2483b43635a3d1f89d45

**Comment by tpgxyz** [comment]
@hallyn What about this ?
https://bugs.launchpad.net/ubuntu/+source/shadow/+bug/523896

Looks like ubuntu guys "fixed" locked files by adding upstart job to simply run rm -rf /etc/*.lock

**Comment by tpgxyz** [comment]
Defined WITH_TCB when compiling binary mixed with USE_TCB set to "no" in login.defs is the culprit here.

So this means if shadow is compiled with TCB you cannot use "non-tcb" shadow functionality of storing passwords, OR this is a bug.

**Comment by hallyn** [comment]
On Wed, Oct 21, 2015 at 09:56:44AM -0700, Tomasz Paweł Gajc wrote:
> @hallyn What about this ?
> https://bugs.launchpad.net/ubuntu/+source/shadow/+bug/523896
> 
> Looks like ubuntu guys "fixed" locked files by adding upstart job to simply run rm -rf /etc/*.lock

Hm, it only seems to do that on bootup though.

**Comment by hallyn** [comment]
On Wed, Oct 21, 2015 at 03:54:53PM -0700, Tomasz Paweł Gajc wrote:
> Defined WITH_TCB when compiling binary mixed with USE_TCB set to "no" in login.defs is the culprit here.

Hm.  So it sounds like a bug in the package configuration?  It should enforce
WITH_TCB off when USE_TCB is no.

> So this means if shadow is compiled with TCB you cannot use "non-tcb" shadow functionality of storing passwords, OR this is a bug.

I think both are the case.  It's a bug that shadow allows this combination.

**Comment by tpgxyz** [comment]
>> Hm. So it sounds like a bug in the package configuration? It should enforce WITH_TCB off when USE_TCB is no.

Yes it seems like a bug.

**Comment by hallyn** [comment]
Looking at it closely, the source seems to do the right thing.

Built a version of shadow with tcb, and set USE_TCB no in login.defs, but still cannot reproduce this.

I don't see any patches in your packaging that would cause this.

It still seems to me that the key is in the fact that your strace shows just an open(/etc/shadow.lock) without a preceeding link().  So I do think it is a mishandling of some combination of configurations here, but I don't know what.
