### ISSUE TITLE
su double grabs '--'

### ISSUE THREAD

**Issue by HarmtH** [shadow-maint/shadow#101]
(Tested on latest master, commit '5f3e3c2c62aae95a694221e43888a1181f979ea4')

Create the following test-file:
```
#!/bin/sh
echo 0:$0
echo 1:$1
echo 2:$2
echo 3:$3
echo 4:$4
```
Call it test.sh and make it executable.

Now the following command double grabs '--', which should not happen, as everything after '--' should be just passed through:
```
thinkbox ~% su harmth -s ./test.sh -- -- -- 1 "2 3" 4
0:./test.sh
1:--
2:1
3:2 3
4:4
```

Expected output, and output given by coreutil's su:
```
dev01 ~%% su harmth -s ./test.sh -- -- -- 1 "2 3" 4
Password: 
0:./test.sh
1:--
2:--
3:1
4:2 3
```

**Comment by HarmtH** [comment]
This only seem to happen when a username is passed:
```
thinkbox ~% sudo -- su root -s ./test.sh -- -- -- 1 "2 3" 4
0:./test.sh
1:--
2:1
3:2 3
4:4
```
but
```
thinkbox ~% sudo -- su -s ./test.sh -- -- -- 1 "2 3" 4
0:./test.sh
1:--
2:--
3:1
4:2 3
```

**Comment by hallyn** [comment]
Indeed if you look at https://github.com/shadow-maint/shadow/blob/master/src/su.c#L826
I don't see why that extra slurping of '--' is there.

**Comment by HarmtH** [comment]
I've further investigated the issue, and I think I have figured it out.

In commit https://github.com/shadow-maint/shadow/blob/e663c696c2a6ccf46e2b68a2b0a3c2a6f52c17dd the option parsing was refactored.

In the old code, the arguments to ```su``` weren't reordered, i.e. option arguments weren't placed before non-options in the argument vector (this can be done/was done by letting the ```optstring``` of ```getopt_long``` start with a dash: https://github.com/shadow-maint/shadow/blob/65d0682647863c92a8a0517cc7ee63a777e88401/src/su.c#L365

Options were parsed until a non-option or a ```-``` was encountered. Everything after the first non-option or ```-``` wasn't seen as an option anymore. Non-options and ```-``` were then manually parsed, but this also meant that ```--``` had to be handled manually, which was done at https://github.com/shadow-maint/shadow/blob/65d0682647863c92a8a0517cc7ee63a777e88401/src/su.c#L406 and https://github.com/shadow-maint/shadow/blob/65d0682647863c92a8a0517cc7ee63a777e88401/src/su.c#L448

In the new code, ```getopt_long``` may reorder the arguments, and everything is parsed until a ```--``` is encountered (which is also parsed and 'removed'), so manual handling of ```--``` isn't necessary anymore and should have been removed in that commit. This means that both https://github.com/shadow-maint/shadow/blob/45b41875968042a41fcebf575762c3b493a146b4/src/su.c#L813 and https://github.com/shadow-maint/shadow/blob/45b41875968042a41fcebf575762c3b493a146b4/src/su.c#L826 should be removed. My issue hit the second case, but you can also hit the first case, or even both at the same time, for example by:
```
thinkbox ~% sudo -- su -c '/home/harmth/test.sh $0 $@' -- - -- root -- 1 2 3 4
0:/home/harmth/test.sh
1:1
2:2
3:3
4:4
```
Both the ```--``` after the ```-``` and the ```--``` after the ```root``` are erroneously removed.

There is an issue with ```getopt_long```: ```-``` is also an option in ```su```, but isn't recognized as such by ```getopt_long```. This makes everything pretty annoying, and I just found out that core-utils ```su``` also does something special here: ```su -- -``` gives you a login-shell, even though ```-``` really should be seen as an option. This is 'fixed' by specifying it in the syntax: (coreutils)```su --help```: ``` su [options] [-] [USER [arg]...]```: ```-``` isn't part of ```[options]``` but a special situation.

By the way, in my opinion the second check on https://github.com/shadow-maint/shadow/blob/45b41875968042a41fcebf575762c3b493a146b4/src/su.c#L824 should be removed as well, for predictability. Now you don't have to specifiy a username if your first argument starts with a ```-```. So at the moment ```su -- --help``` is valid but ```su -- ls``` isn't, which can surprise users.

**Comment by glensc** [comment]
ps: there's also util-linux version of [`su`](https://github.com/karelzak/util-linux/blob/v2.32/login-utils/su.c)

**Comment by hallyn** [comment]
Thanks, @HarmtH  - can you propose a PR to fix it, or would you prefer not to?

**Comment by HarmtH** [comment]
I will try to make a PR tonight.
