### ISSUE TITLE
Release 4.16.0 missing assets

### ISSUE THREAD

**Issue by arachsys** [shadow-maint/shadow#1024]
Completely trivial one I'm afraid, but https://github.com/shadow-maint/shadow/releases/tag/4.16.0 has `shadow-4.16.0.tar.xz.asc` and `shadow-4.16.0.tar.gz.asc` signatures as assets, but neither of the actual tarballs they sign: `shadow-4.16.0.tar.xz` and `shadow-4.16.0.tar.gz`.

**Comment by alejandro-colomar** [comment]
Hmmmm, editing the tag, I can see a warning:

```
Upload failed. Delete and try uploading this file again.
```

@hallyn

**Comment by jubalh** [comment]
I mentioned this this morning on IRC as well :)

**Comment by alejandro-colomar** [comment]
Serge told me it was an ISP connection error, and that he's not able to fix it at the moment.  We'll have to wait for some time.

**Comment by hallyn** [comment]
Yes, sorry, simply wasn't able to push up the bits yesterday.  I need to change my internet plans.

Uploaded now.
