### ISSUE TITLE
su: check whether waitpid() return value is equal to pid_child

### ISSUE THREAD

**Issue by mephi42** [shadow-maint/shadow#104]
When su runs as pid 1 (happened to me in Docker), it can get adopted children.
If such child exits, it makes su exit prematurely with its retcode.
It would be great to simply loop here https://github.com/shadow-maint/shadow/blob/master/src/su.c#L357 if pid != -1 && pid != pid_child.

**Comment by hallyn** [comment]
So you're saying only in the case where su detects that the
child has exited, right? Not in the passing-of-signals cases?

That seems reasonable.

**Comment by mephi42** [comment]
Yes, only the exit case. I don't think SIGSTOP/SIGCONT forwarding is affected.
