### ISSUE TITLE
4.14.7 release was deleted

### ISSUE THREAD

**Issue by thesamesam** [shadow-maint/shadow#1042]
See https://bugs.gentoo.org/935453. It appears 4.14.7 was yanked. Please don't _ever_ delete releases, especially not for a security-critical package. It destroys provenance and raises alarm bells.

If a release is broken, please add a note to the release notes and issue a new release.

**Comment by alejandro-colomar** [comment]
I noticed, but didn't know when or how it happened.  I noticed some glitches while uploading some of the more recent versions (github misbehaved), so I guessed it would have been some github glitch that also removed 4.14.7.  But don't know what happened for sure.

**Comment by alejandro-colomar** [comment]
I have the original release tarballs in my own server

<http://www.alejandro-colomar.es/share/dist/shadow/4/4.14/4.14.7/>

but I didn't want to re-upload it because that would obviously be suspicious.  But if anyone needs it, it's available there.  Just check the signature, and compare a checksum with one of the old github release, if anyone keeps it.

**Comment by alejandro-colomar** [comment]
If anyone knows how to report a bug to github, feel free to do so.  It'd be interesting to learn what the hell happened, because as you say, it's pretty bad.  If they can show logs of how that happened, that would be good.

**Comment by floppym** [comment]
There's a bug form [here](https://support.github.com/contact/bug-report).

Given that we don't know what you did or how you did it, I don't think anyone can file a bug on your behalf.

**Comment by alejandro-colomar** [comment]
> There's a bug form [here](https://support.github.com/contact/bug-report).
> 
> Given that we don't know what you did or how you did it, I don't think anyone can file a bug on your behalf.

Done.  <https://support.github.com/ticket/personal/0/2874751>

Although, I think that link is private, and don't see any button to make it public.  :|

**Comment by alejandro-colomar** [comment]
I've created one on behalf of shadow.  Maybe this gives visibility at least to other maintainers...

<https://support.github.com/ticket/personal/0/2874769>

**Comment by alejandro-colomar** [comment]
Github support said this is in their logs:

```
{
"action": "release.destroy",
"actor": "hallyn",
"created_at": "2024-05-25 18:33:57 +0300",
"name": "4.14.7: Casín aged++++++",
"repo": "shadow-maint/shadow"
}
```

Cc: @hallyn

**Comment by alejandro-colomar** [comment]
Here's the request for branch removal that @hallyn referenced: <https://github.com/shadow-maint/shadow/issues/926#issuecomment-2118178358>
