### ISSUE TITLE
Missing .asc file for 4.6 release

### ISSUE THREAD

**Issue by jubalh** [shadow-maint/shadow#108]
Hi there,
maybe you still plan on doing this, but here is a short reminder. `.asc` file is missing in GH downloads for 4.6 release ;)

**Comment by hallyn** [comment]
Yup - I need to grab my hardware keyring.  I intend to post it by tonight.

**Comment by hallyn** [comment]
D'oh, indeed.  I should have created an ascii-armored detached signature.  Updated.
