### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by alejandro-colomar** [shadow-maint/shadow#1088]
Hi @ikerexxe ,

I've seen some CI fail with the following error.  Maybe you know why it happens?

```
Reading package lists...
E: You must put some 'deb-src' URIs in your sources.list
Error: Process completed with exit code 100.
```
<https://github.com/shadow-maint/shadow/actions/runs/11315585583/job/31466940612?pr=1048>

**Comment by alejandro-colomar** [comment]
Maybe <https://linuxconfig.org/ubuntus-repository-configuration-ubuntu-sources-have-moved-to-etc-apt-sources-list-d-ubuntu-sources>?

**Comment by ikerexxe** [comment]
Yes, that's probably the problem. If I remember correctly Debian also made a similar change. I'll take a look today ;)

**Comment by alejandro-colomar** [comment]
@ikerexxe 

It seems to be bad again.  This time it seems the .sources file doesn't exist.  :/

```
cat: /etc/apt/sources.list.d/ubuntu.sources: No such file or directory
```

<https://github.com/shadow-maint/shadow/actions/runs/11371739677/job/31634488628?pr=1095>

Can you have a look?  In some cases, it seems to be running on Ubuntu 22, and in some other cases in Ubuntu 24.

**Comment by ikerexxe** [comment]
This seems to be a bug in the Github infrastructure since from shadow we always run the workflows in `ubuntu-latest`. I think it would be a good idea to open an issue at https://github.com/actions/runner-images/issues for Github to fix this problem.

**Comment by alejandro-colomar** [comment]
> This seems to be a bug in the Github infrastructure since from shadow we always run the workflows in `ubuntu-latest`. I think it would be a good idea to open an issue at https://github.com/actions/runner-images/issues for Github to fix this problem.

Thanks!  It seems it's alreayd open: <https://github.com/actions/runner-images/issues/10636>.  Github seems to have rolled back the upgrade to 24.  We'll have CI partially broken until they fix that.  At least the alpine/fedora/debian builds are working.  Those are the most important ones, IMO.

**Comment by ikerexxe** [comment]
I don't know who has made these decisions but I think they have been wrong several times :disappointed:

**Comment by hallyn** [comment]
@ikerexxe do you have a fix in the works for this, or should I take it?

I think our tests just have to check for which style sources.list we have, and do the right thing.
