### ISSUE TITLE
shadow-4.6: /bin/groups lists supplementary groups twice

### ISSUE THREAD

**Issue by aeckstein** [shadow-maint/shadow#109]
Hi,
the new shadow suite's 'groups' tool lists supplementary groups twice:

**> useradd -m test -g users -G audio,video**
**> groups test**
audio video audio video users

**Comment by joakim-tjernlund** [comment]
Note, shadow-4.6 already went stable on Gentoo due to security issues with previous
release. I hope this wont cause any serious regressions ?

**Comment by joakim-tjernlund** [comment]
hmm, this seems to be caused by nsswitch.conf:
group:       compat files

removing compat fixes the problem for me

**Comment by joakim-tjernlund** [comment]
See https://bugs.gentoo.org/637674 for more info.

**Comment by hallyn** [comment]
Thanks, clearly this is a dup of #87 which was never actually fixed.

**Comment by joakim-tjernlund** [comment]
Yes, looks like it.

**Comment by hallyn** [comment]
(Removing 'files' also fixes it, fwiw)

**Comment by hallyn** [comment]
Ah, I get the same behavior with 4.3.0.

**Comment by hallyn** [comment]
And 4.1.0.  If you look at the coreutils implementation, they do a step to remove adjacent duplicates, but explicitly do not guarantee no duplicates.
Doing the same here would be quite trivial.  I'd accept a patch to do so, or may eventually do it myself, but this is not a regression and arguably not a bug.
