### ISSUE TITLE
CI: Using ansible makes it more complex to see the error logs

### ISSUE THREAD

**Issue by alejandro-colomar** [shadow-maint/shadow#1091]
Hi @ikerexxe , @hallyn ,

I'm finding it more difficult to see `stderr` when a build fails.  Previously, I could just scroll the github screen to see the logs.  I could also see at the top the `docker build` command that had been run to run it in my computer and check `stderr` myself (maybe piping it to less(1): `docker build ... |& less`).

Now that's become significantly more complex.  Would you consider doing something that writes to stderr?  If you want to **also** produce a log file, that's fine, but I would very much prefer to continue having stderr and stdout.

**Comment by alejandro-colomar** [comment]
Ahh, I see that in the JSON there's some garbled stderr (newlines and such are printed as escapes).  Maybe I can work with that.

**Comment by ikerexxe** [comment]
I know it is not as simple as before but now you can see all available logs if you click on the CI action that failed, then click on Summary and do some scrolling. There you will see all captured logs (which are more than before).
