### ISSUE TITLE
Proposal: Create .lock files on temporal directory

### ISSUE THREAD

**Issue by jlsalvador** [shadow-maint/shadow#111]
If someone reboot the machine while you're using chpasswd (.lock files created on /etc), the lock files will stay on /etc forever. Maybe you can create these .lock files on /var/run or /tmp (will be cleanup on reboots).

Thoughts?

**Comment by hallyn** [comment]
Perhaps we could add a (default-off) "--varrun-lockfiles" configure flag to fix the paths, in an attempt at migrating everyone in the long term?

**Comment by vapier** [comment]
you mean --run-lockfiles ? ;)

**Comment by vapier** [comment]
i'm not sure we'll be in a place where we would hard require a specific path.  maybe make the option `--with-lockfiles-path`, have it default to `/etc`, and then distros/whoever could decide to use `/run` or `/var/run` or whatever.

**Comment by jubalh** [comment]
Since https://github.com/shadow-maint/shadow/pull/605 we changed the lock mechanism. This issue can be closed.
