### ISSUE TITLE
groupadd / groupmod --users doesn't add users to /etc/gshadow

### ISSUE THREAD

**Issue by sandwm** [shadow-maint/shadow#1124]
If you run `groupadd --users` the given user(s) will not be added to the new entry in the group shadow file. Found this when `grpck` complained about it.

```
# groupadd --users swm test
# grep ^test: /etc/group /etc/gshadow
/etc/group:test:x:1005:swm
/etc/gshadow:test:!::
# grpck
...
'swm' is a member of the 'test' group in /etc/group but not in /etc/gshadow
```

I'll try to create a patch for src/groupadd.c and a corresponding test case.

**Comment by alejandro-colomar** [comment]
Thanks!  Which versions are affected?

**Comment by sandwm** [comment]
A patch for both groupadd and groupmod is available at https://github.com/sandwm/shadow/commit/1627abdb4f09b9f845b1f972766f77d9e07f4946.

I tested it only in the Ubuntu VM _with_ a /etc/gshadow file. I.e., the codepath of undefined `SHADOWGRP`, `!is_shadow_grp` is untested. I also manually removed a group from /etc/gshadow only (keeping it in /etc/group), to see that groupmod would still behave as intended (here: adding a user to the group in /etc/group, not changing /etc/gshadow).

Regarding the test suite: I tried to run it unmodified, but got a lot of failures (e.g. for many, but not all su tests). Looking into it, it's apparently using the system installation of the shadow utils, not the one from the git clone it's started from. To be honest, I'm currently not very motivated to dig into this test suite and how to compile and install shadow manually without breaking Ubuntu's system setup (which, considering it's Ubuntu, probably carries a bunch of distro patches, too), even if it's just a random VM and not my production system. So I'll leave it at the code fix without new tests.

**Comment by alejandro-colomar** [comment]
Thanks!  Would you mind opening a PR?

**Comment by ikerexxe** [comment]
I didn't check the patch at https://github.com/shadow-maint/shadow/pull/1129, but that's because I've been unable to reproduce the bug reported in this issue.

Fedora 41:

```console
# rpm -qa shadow-utils
shadow-utils-4.16.0-7.fc42.x86_64
# useradd tuser
# groupadd --users tuser tgroup
# grep ^tgroup: /etc/group /etc/gshadow
/etc/group:tgroup:x:1001:tuser
/etc/gshadow:tgroup:!::
```

Same for Ubuntu 24.04:

```
# useradd tuser
# groupadd --users tuser tgroup
# grep ^tgroup: /etc/group /etc/gshadow
/etc/group:tgroup:x:1002:tuser
/etc/gshadow:tgroup:!::
```

By the way, https://github.com/shadow-maint/shadow/commit/342c934a35906362b89aaa015b265a66ce011d45 was first introduced in v4.9, ~4 years ago.

**Comment by sandwm** [comment]
Um, that is exactly the bug behaviour?

> ```
> # grep ^tgroup: /etc/group /etc/gshadow
> /etc/group:tgroup:x:1001:tuser
> /etc/gshadow:tgroup:!::
> ```

/etc/gshadow should contain `tgroup:!::tuser`, but it only contains `tgroup:!::`. Run `grpck` and it should complain about it. See also gshadow(5):
>        members
>            It must be a comma-separated list of user names.
> 
>            Members can access the group without being prompted for a password.
> 
>            You should use the same list of users as in /etc/group.

**Comment by ikerexxe** [comment]
My bad, I misunderstood the problem. Let me recheck it.
