### ISSUE TITLE
"no changes" is not an error, it should not be output to stderr

### ISSUE THREAD

**Issue by quent** [shadow-maint/shadow#113]
If a command such as: `/usr/sbin/usermod -s /sbin/nologin sysaccount` has no effect then it outputs 
"usermod: no changes" to stderr and returns with an exit code of 0.
Because it is not an error but rather an informational message, this message should rather be output to stdout.

While it seems like a meaningless change, I have a use case where a script runs that command upon upgrade to ensure the system user's shell is set correctly.
However, to keep the upgrade output terse I do not wish to show the message "usermod: no changes" but would still like to report on actual errors (sent to stdout). Currently the only option I have to achieve that is to involve capturing the exit code and only showing error output based on its returned value.

**Comment by hallyn** [comment]
I wonder whether a '-q' option would be better.

**Comment by quent** [comment]
"no changes" is an informational message, I think the important change is to be able discriminate informational from error messages.
Only then '-q' could silence informational messages while still displaying potential errors.

**Comment by hallyn** [comment]
Ok - I agree, thanks.
