### ISSUE TITLE
home page invalid

### ISSUE THREAD

**Issue by avmaisak** [shadow-maint/shadow#114]
I can't access to specified home page http://pkg-shadow.alioth.debian.org/

**Comment by jubalh** [comment]
One alternative would be to use [GitHub pages](https://pages.github.com/)

**Comment by hallyn** [comment]
I'm definately open to it.

I wonder whether the source of the old page is cached somewhere.  I do see it on archive.org.

**Comment by jubalh** [comment]
https://lists.debian.org/debian-devel-announce/2018/06/msg00001.html
I can see several pkg-* things at https://alioth-archive.debian.org/releases/ but no pkg-shadow.

**Comment by jubalh** [comment]
I suspect we can update https://github.com/shadow-maint/shadow-www, use GitHub pages for the hosting, then only need to gather the missing tarballs from distributions archives of pristine sources.

**Comment by oimaasi** [comment]
@jubalh

> EDIT: contacted one of the people who did the backup. Result: Websites were not backed up.

So the tarballs do have backups? Do you tell me where to find them or how to contact the person who was responsible for that?
