### ISSUE TITLE
Upload more release tarballs

### ISSUE THREAD

**Issue by rossburton** [shadow-maint/shadow#115]
Over in the OpenEmbedded we use Debian's shadow package, would it be possible for you to upload more of the official tarballs from the Debian mirrors to github?  Specifically 4.2.1 would be great. :)

**Comment by glensc** [comment]
you can grab copy from pld linux distfiles:

- http://distfiles.pld-linux.org/distfiles/by-md5/2/b/2bfafe7d4962682d31b5eba65dba4fc8/shadow-4.2.1.tar.xz
- http://distfiles.pld-linux.org/distfiles/by-md5/6/7/6752051fb07fc4be58c3d7b929bf2341/shadow-4.2.1.tar.xz.sig

you can verify checkums from here: https://github.com/pld-linux/shadow/commit/84769f943fd8fc8db040d656a0ace6dd255e1ec2

or just verify the `.sig`

**Comment by hallyn** [comment]
(Note, I don't think I can get at the original verified tarballs.  Maybe @rbalint can? )

**Comment by rbalint** [comment]
@rossburton If OpenEmbedded would like to rely on signed tarballs and especially if it already relies on the Debian package I suggest getting the tarballs from http://snapshot.debian.org/package/shadow/ . 4.2.1 was not packaged in Debian, just earlier and later releases BTW.

**Comment by rbalint** [comment]
@rossburton In general I think it is easier to use snapshot.d.o than getting all GitHub projects to upload signed tarballs not to mention uploading them retroactively.

**Comment by glensc** [comment]
@hallyn i'm able to recover from pld linux distfiles following releases. as .asc included, these should be trustworhty:

----
- https://github.com/shadow-maint/shadow/releases/tag/4.1.2
- https://distfiles.pld-linux.org/distfiles/by-md5/2/b/2bfafe7d4962682d31b5eba65dba4fc8/shadow-4.2.1.tar.xz
- https://distfiles.pld-linux.org/distfiles/by-md5/6/7/6752051fb07fc4be58c3d7b929bf2341/shadow-4.2.1.tar.xz.sig

----
- 4.2 - no github tag present, but could be re-created using lightweight tag
- https://distfiles.pld-linux.org/distfiles/by-md5/9/1/912a5957c1471acccedbc2a635e36f5e/shadow-4.2.tar.xz
- https://distfiles.pld-linux.org/distfiles/by-md5/c/3/c345642a3a3daf3ff96b7542590f7706/shadow-4.2.tar.xz.sig
----

- https://github.com/shadow-maint/shadow/releases/tag/4.1.5.1
- https://distfiles.pld-linux.org/distfiles/by-md5/a/0/a00449aa439c69287b6d472191dc2247/shadow-4.1.5.1.tar.bz2
- https://distfiles.pld-linux.org/distfiles/by-md5/f/1/f16f31f6f5a607b1ffb1aa1aac4c37f2/shadow-4.1.5.1.tar.bz2.sig
----

so, if you have access in https://github.com/shadow-maint/shadow, upload the tarball and .asc

**Comment by glensc** [comment]
@rbalint what is `snapshot.d.o` ?

**Comment by jubalh** [comment]
> @rbalint what is snapshot.d.o ?

short for snapshot.debian.org - http://snapshot.debian.org/package/shadow/

**Comment by glensc** [comment]
@hallyn please upload the tarballs I recovered to GitHub releases

see:
- https://github.com/shadow-maint/shadow/issues/115#issuecomment-397646648
- https://github.com/shadow-maint/shadow/issues/115#issuecomment-413472472

these should be verifiable via `.asc` signatures that they are not tampered.

another duplicate: #145

**Comment by hallyn** [comment]
@jubalh Is there any chance of snapshots.d.o ever going away?

If not I'm tempted to close this and post a note at top of releases page, or just on shadow-maint.github.io, saying historical releases can be found there.

**Comment by glensc** [comment]
@hallyn can you upload the recovered tarballs noted here:
- https://github.com/shadow-maint/shadow/issues/115#issuecomment-450333711

**Comment by jubalh** [comment]
@hallyn unfortunately I can't say for sure.
Would be better to be safe than sorry? :)
