### ISSUE TITLE
4.17.0: su - does not invoke login shell

### ISSUE THREAD

**Issue by hdejin** [shadow-maint/shadow#1160]
After updating to 4.17.0, running su - no longer invokes a login shell.
I've built the source with --with-libpam and using the following pam config for su:

auth        required        pam_env.so
auth        required        pam_nologin.so successok file=/etc/nologin
auth        sufficient      pam_rootok.so
auth        sufficient      pam_unix.so likeauth nullok
auth        required        pam_deny.so

account     sufficient      pam_unix.so likeauth nullok
account     required        pam_deny.so

password    required        pam_unix.so nullok use_authtok md5 shadow
password    required        pam_deny.so

session     required        pam_unix.so

**Comment by dchmelik** [comment]
I and several other Slackware-current users have same problem.

**Comment by stoeckmann** [comment]
The PR https://github.com/shadow-maint/shadow/pull/1163 should fix this issue.

**Comment by alejandro-colomar** [comment]
Thanks for the report and the quick fix to all of you!  And sorry for the bug.
