### ISSUE TITLE
passwd command, add salt length option up to 16 characters

### ISSUE THREAD

**Issue by thaygiaoth** [shadow-maint/shadow#120]
Hi all

I read passwd command man page but i not found salt length option

I want to an option specify salt length up to 16 characters

passwd command default creates salt length 6 characters for sha512 ($6$... in /etc/shadow)
--> tested on CentOS 7.5

Anaconda installer (Red Hat/CentOS...) created salt lengh 16 characters

Do I right to suggest this option? Does it necessary?

Tks

**Comment by t8m** [comment]
passwd in Red Hat Enterprise Linux and CentOS does not come from shadow package. The salt length used by passwd is hardcoded in pam_unix. The hardcoded length is 8 characters (your statement that it is 6 characters is wrong) which is fully sufficient to prevent any rainbow table creation.

**Comment by hallyn** [comment]
If you wanted to post a patch to add the salt length to the manpage, I think that would be fine, thanks.
