### ISSUE TITLE
--force-badname

### ISSUE THREAD

**Issue by christianbundy** [shadow-maint/shadow#121]
Hello!

After reading [this mailing list thread](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=42874) I'm not sure whether it was intentionally removed, but is there a runtime option or compiler flag that I can use to force [`is_valid_name()`](https://github.com/shadow-maint/shadow/blob/6fbc11ce2178205968c37853db752729359c9893/libmisc/chkname.c#L49-L71) to always `return true`? If not, would you be open to having it added?

Thanks for your work on this project!

**Comment by hallyn** [comment]
I'm open to it, yes.
