### ISSUE TITLE
Log SSH_ORIGINAL_COMMAND in nologin

### ISSUE THREAD

**Issue by ivladdalvi** [shadow-maint/shadow#123]
Now `nologin` [logs the login attempt](https://github.com/shadow-maint/shadow/blob/master/src/nologin.c#L50). It could be used to block certain users from logging in. One of the cases would be to prevent interactive logins and remote command execution over ssh.

If an user tries to execute command remotely over ssh **and** `ForceCommand` directive applies to the user, `sshd` populates `SSH_ORIGINAL_COMMAND` environment variable with the requested command line. E.g., given the following snippet in `sshd_config`:

```
Match User baduser
ForceCommand /usr/sbin/nologin
```
if `baduser` will try to execute a command, `sshd` will set `SSH_ORIGINAL_COMMAND` to the requested command line and execute `/usr/sbin/nologin` denying the login. However, from the `nologin` logs it will be hard to figure out, if this `baduser` really tried to login interactively, execute a command, or just had Emacs TRAMP mode misconfigured.

To address this shortcoming I wrote a [special shell](https://github.com/ivladdalvi/forsh) some time ago. I realized later, that `nologin` might be a better and a more universal tool to do the job.

I am opening this issue as I hope to hear the feedback from developers if logging `SSH_ORIGINAL_COMMAND` in `nologin` makes sense. If the feedback is positive, I'll submit PR.

**Comment by hallyn** [comment]
It sounds good to me.
