### ISSUE TITLE
Creating /run/user/_uid_ on login

### ISSUE THREAD

**Issue by Sworddragon** [shadow-maint/shadow#124]
With systemd being more or less a thing applications begin to move from the usage of /tmp to /run/user/_uid_ (with permissions limited to the user). Some applications fallback to /tmp if /run/user/_uid_ does not exist and others just fail. Since the creation of /run/user/_uid_ relies on the existence of systemd-logind and dbus (with sufficient permissions) and a login interface is a better common denominator it might make sense that login creates this directory (and eventually deletes it on logout if possible).

**Comment by glensc** [comment]
might be better implemented as [PAM module](https://en.wikipedia.org/wiki/Pluggable_authentication_module) instead

**Comment by hallyn** [comment]
Shouldn't applications be using XDG_RUNTIME_DIR?  which is usually /run/user/uid...

But yeah like @glensc said PAM sounds right here.
