### ISSUE TITLE
parent directories are created with 777 when invokinguseradd -m 

### ISSUE THREAD

**Issue by kbabioch** [shadow-maint/shadow#127]
As pointed out in the original pull request #2 in a [comment](https://github.com/shadow-maint/shadow/pull/2#discussion_r73641579), parent directories are created with 777, which is probably not a good idea and should be changed to 755.

**Comment by kbabioch** [comment]
This has also been discussed in a bug over in the openSUSE world: https://bugzilla.suse.com/show_bug.cgi?id=1106914

**Comment by jubalh** [comment]
@kbabioch https://github.com/shadow-maint/shadow/blob/master/src/useradd.c#L2069

**Comment by kbabioch** [comment]
Ah, alright then, sorry for the noise :-1:
