### ISSUE TITLE
lastlog - GDPR violation

### ISSUE THREAD

**Issue by drexljo** [shadow-maint/shadow#129]
I'm not quite sure if I'm right here, but maybe you can forward the problem if your hands are tied. 

/var/log/lastlog contains the last login date of all users ever created on the system, no matter how old this information is. Since we're trying to stay compliant with the European GDPR, we have to get rid of login information older than x days (we chose 7 days as our threshold). Normally all we'd do is letting logrotate handle this sort of stuff, but then the manpage of lastlog clearly states 'You should not rotate it.' After all I've read there is no *right* way to clear the file, but no way at all. This clearly violates European law.

Since this issue will be important for all entities serving people from Europe (not only those entities residing in Europe), and the penalties for violations may come out quite hefty, I'd be glad if it could be priorized.

Temporary (maybe ugly) workaround:
We rotate the file, ignoring the statment in the manpage, as we do with btmp and wtmp. As far as we've seen it'll be recreated if existing (0 bytes), but not if not existing. Another solution would be using the immutable attribute, but at least sshd throws errors in debug mode in this case, so we didn't dig into it any further.

**Comment by hallyn** [comment]
Hi,

As near as I can tell, if all you wanted to do was clear them, you could just echo > /var/log/lastlog.

**Comment by drexljo** [comment]
Oh, I know how to clear them - it's just it should be cleared by design after some time, because it's the law and it affects all people running a Linux machine for something else than internal services. As I said: The law affects everyone who's serving a European citizen, regardles where the server and/or company is located.

I just thought I'd pipe that issue upstream, as a little reminder there's something that doesn't fit the description "privacy by design" and should be changed.
