### ISSUE TITLE
Discussion: subvolume capable filesystems, useradd homedir, hooks

### ISSUE THREAD

**Issue by jubalh** [shadow-maint/shadow#131]
With the rise of popularity of filesystems like btrfs, it's possible that users want their home directory to be on a (btrfs) subvolume.
If I create a new user via `useradd -m`, useradd will create the (standard) home directory for me.
However if I create the subvolume first, useradd detects that the directory already exists and won't adapt the permissions nor copy the skel files.

One could argue that on such a custom setup everything should be done customized by hand:
 * creating subvolume
 * call useradd
 * change permissions
 * copy skel files

Another possibility would be to add some kind of hooking mechanism into useradd. Then a distro could specify any behaviour for that hook. In this case calling btrfs to create a subvolume and then continuing with normal useradd behaviour.

Adding explicitly btrfs (subvolume) support into useradd probably is not a nice solution. The hooking is the one way I could think of to achieve some desired behaviour. Maybe someone else has a better idea?

**Comment by hallyn** [comment]
I like the hooking idea - could also be used to e.g. create an lvm lv.

**Comment by hallyn** [comment]
Well, I'm not sure.  It seems more accessible to just have useradd.c:create_home() check for $somexdgprefix/shadow/hooks/create_home, which it simply execs, passing along the needed info.  Though that info passing might be a source of cves, and might prove problematic when we want to extend it for things like selinux.  But then create_home could really just be a shell script.

**Comment by jubalh** [comment]
https://github.com/shadow-maint/shadow/pull/149 got merged now.
