### ISSUE TITLE
Expired password changed with `usermod -p` is not set to unexpired

### ISSUE THREAD

**Issue by sofar** [shadow-maint/shadow#14]
Hi,

The security policy in ClearLinux creates images where the root password is always set to be expired. This forces the first-time user to immediately change the root password.

However, we additionally need to allow programs such as cloud-init to set the password in a secure way through e.g. `usermod -p /encrypted pass/`. This changes the password properly, but never un-expires the password, causing `sudo` etc. to fail on first use (even with NOPASSWD in sudoers.d).

I'd like to be able to have `usermod -p $hash` also clear the expiry flag in shadow automatically. It seems logical that an expired password being changed (through whichever password change method there is) that the "password is expired" flag should be cleared as well.

Right now our users are overwriting the shadow file, which is a less desirable way of dealing with this. If this would be done automatically or with an optional flag, it would solve the problem for us.

I also couldn't find other methods to clear the flag.

**Comment by hallyn** [comment]
Hi,

the flag is cleared by doing:
```
usermod -e "" user
```
What you describe seems a sensible behavior, but I'm afraid changing that today is bound to bite a set of people who for whatever reason depend on passwd not unsetting expiry.
