### ISSUE TITLE
libmisc/getdate bison error

### ISSUE THREAD

**Issue by jubalh** [shadow-maint/shadow#140]
Compiling 42324e501768675993235e03f7e4569135802d18 with:

```
--disable-shadowgrp \
	--enable-account-tools-setuid \
        --with-audit \
        --with-libpam \
        --with-sha-crypt \
	--with-acl \
	--with-attr \
	--with-nscd \
        --with-selinux \
        --without-libcrack \
        --disable-shared \
	--with-group-name-max-length=32
```

I get:

```
make[2]: Entering directory '/home/michael/src/shadow/libmisc'
  YACC     getdate.c
/home/michael/src/shadow/libmisc/getdate.y: warning: 13 shift/reduce conflicts [-Wconflicts-sr]
bison: input/output error
make[2]: *** [Makefile:605: getdate.c] Error 1
```

**Comment by brauner** [comment]
On Tue, Nov 06, 2018 at 02:24:25AM -0800, Michael Vetter wrote:
> Compiling 42324e501768675993235e03f7e4569135802d18 with:
> 
> ```
> --disable-shadowgrp \
> 	--enable-account-tools-setuid \
>         --with-audit \
>         --with-libpam \
>         --with-sha-crypt \
> 	--with-acl \
> 	--with-attr \
> 	--with-nscd \
>         --with-selinux \
>         --without-libcrack \
>         --disable-shared \
> 	--with-group-name-max-length=32
> ```
> 
> I get:
> 
> ```
> make[2]: Entering directory '/home/michael/src/shadow/libmisc'
>   YACC     getdate.c
> /home/michael/src/shadow/libmisc/getdate.y: warning: 13 shift/reduce conflicts [-Wconflicts-sr]
> bison: input/output error
> make[2]: *** [Makefile:605: getdate.c] Error 1
> ```

Care to send a patch? :)

**Comment by jubalh** [comment]
> Care to send a patch? :)

I would have already. But not a bison expert ;)
So I wanted to report it first. And see whether I can solve it. But if someone else is quicker I don't mind ;)

**Comment by brauner** [comment]
On Tue, Nov 06, 2018 at 03:38:05AM -0800, Michael Vetter wrote:
> > Care to send a patch? :)
> 
> I would have already. But not a bison expert ;)
> So I wanted to report it first. And see whether I can solve it. But if someone else is quicker I don't mind ;)

He, @hallyn and I rather need maintenance help so patches always
welcome! :)
