### ISSUE TITLE
Feature wish: Let /bin/login start a session

### ISSUE THREAD

**Issue by zem** [shadow-maint/shadow#147]
Hello Together, 

by default login should start the default session (which is the users shell if nothing else is defined) 
but whenever the user presses a function key one of the different sessions can be selected for example: 

A tmux session 
A wayland session 
An Emacs session 
A Swaywm session 

Especially since a wayland compositor typically runs on the VT where it is started and does not change any graphics mode, i think it might be a good  idea to at least think about an extension of login.  

regards 

      Hans

**Comment by vapier** [comment]
this looks out of scope for login.  the login program is supposed to use whatever program is registered in `/etc/passwd` (or equiv).  if you want to run something use, try `chsh` to configure that setting.

higher level stuff like graphics management is best left to higher level login systems like lightdm.

**Comment by zem** [comment]
I am not sure if "out of scope" is not just a term for: We always did it that way, so it must be right. And we will never touch that scope. 

The shell registered in /etc/passwd is also started by each xterm, ssh login, so it is not the best idea to start tmux or screen instead of a shell. (rules out chsh) I also had a larger discussion recently to use .profile and I can almost constantly show the next tool doing something nasty which will make a selection in .profile very difficult. 

That higher level graphics stuff is a different thing, It starts off with how the old SystemV worked in a way that it recursively runs some gettys and a shell script to bring up the rest of the system. And the displaymanager is part of that rest of  the system shell script. It therfore runs as a daemon and starts xorg recursively which switched the computer into graphics mode and displayed a login screen there, and after a successful login it started a window manager. 

Now wayland comes it does _not_ switch modes and can run several times on several VTs and  the compositor is sort of wm and display server in one thing, so you cant just keep up an X or compositor session, you have to start a new compositor after login. GDM3 is solving that by  just starting a shell on an empty VT. 

Last but not least, there is quingy around, but that is doing even more than needed by setting up a graphical framebuffer for the login selection. 

Anyway, If it really is out of scope, i think it is best to try it with a /bin/login_session instead.  If nothing happens I will propably write something down during the next months, to see if it works.

**Comment by vapier** [comment]
you're describing "feature creep".

if you want to customize login behavior, the system can already support esoteric requests as this.  write a custom program that detects the active environment and adjusts accordingly.  or, if you've built shadow with pam, utilize the pam config files to change local login behavior so you don't have to deal with terminal emulators or remote logins starting the same kind of login session.

there are already login projects out there that are well versed in things like standing up graphics stacks or multiseat approaches that you can install and run now.  the question isn't whether it's technically possible, it's whether it makes sense to try and duplicate all those other projects and merge into the small/standalone login program.
