### ISSUE TITLE
libuseradd.so so useradd can be called from a C program

### ISSUE THREAD

**Issue by Reasoning-Technology** [shadow-maint/shadow#152]
I'm really not finding a secure way to call useradd.  system() invokes a shell.  exec() doesn't return when there is no error and I don't want to be spinning code on my own to beat race conditions or go hunting in process tables.  It would be great if I could just call useradd().   Perhaps it is already possible. Don't know. I'm about to pull code from here and give useradd call wrapper.  I'm concerned about compiling and making the lib.  I have programming experience (started programming in the 70s have used C for decades), but not with a project like this, and have not ever made a branch or such.  Looks like I start with a pull request if I'm wanting to perhaps share the result. ... I'm not even sure if I'm putting this note in the write place.  Probably not.

**Comment by glensc** [comment]
Looks like Unix is foreign to you then, you need to call `fork()` before you invoke `exec*()` family functions, because `exec` family functions replace current process with executed one.

Try:
- https://www.google.com/search?q=fork+exec+tutorial

ps: you can close the issue yourself if you see the issue itself is not appropriate.

**Comment by vapier** [comment]
there's also the [`posix_spawn()` API](http://pubs.opengroup.org/onlinepubs/9699919799.2016edition/functions/posix_spawn.html) that some people find easier to work with.

or the `popen()` and `system()` APIs.  those are very easy to integrate, but they're much more hacky because they take shell command strings rather than argv's.  depending on what you're going for, those might be OK.

if we had a library/API defined for all the shadow utilities, i'm doubtful about how much they'd actually be used.  puttying together those libraries would be a non-trivial amount of work.

**Comment by Reasoning-Technology** [comment]
The man page for exec(3), "The exec() functions only return if an error has occurred."  Which for the caller to fork()  begs the question, "is the process that I forked (and then execed) done yet?"  fork() returns the p_id, so one could go fishing around the process tables to get the answer.  spawn has " the functionality of a combined fork(2) and exec(3)" so the same thing. popen() invokes a shell the very can of worms I was hoping to avoid.

I forked shadow repository, and was thinking to try this:
useradd.c
`int main(int argc, char **argv, char **envp){ ...}`
--->
`int adduser(int argc, char **argv, char **envp){...}`
`int main(int argc, char **argv, char **envp){ useradd(arc, argv, envp);}`

And then link against useradd.o.  I might have to add some pound defines and get rid of the main, and compile separately to make the .o or library.

**Comment by vapier** [comment]
i think you should read the documentation @glensc pointed out.  using fork+exec+wait is trivial to write w/out race conditions, nor having to worry about when the child finishes executing.

**Comment by Reasoning-Technology** [comment]
The right choice depends on the application of course.  

Seems there will always be race conditions when using fork/exec/wait, as there are no guarantees about which other process first gets the information that the exec'ed process has done its work.  However, there  doesn't look to be a consequential race in the case of using adduser, as permission lock out all except root or the new user.  Perhaps that is what you intended to explain.

The fork/exec/wait also has a complication of signals, as a signal to the parent has to be handled and then affect the child appropriately.  In just one situation if the parent process ends first, then the child will become a zombie. 

Another complication with fork/exec/wait is environment variables.  It isn't a straightforward question as to which variables should be passed through and which should not, and if default behaviour is acceptable.  For one thing, it is not good to let a path go through as a different executable might get picked up other than that intended. 

Yet another complication looks to be that exec itself can have an error distinct from that of the child process having an error, and there is no direct means for handling that, which I'm aware of.  

Besides races, signals, environment issues, and exec errors, fork/exec/wait calls are heavy.  They are lighter than before because of copy on write for the forked data pages, but still heavy.  Probably doesn't matter in my application, but feels bad to waste for no reason.  

So while all that might be easy for you guys who play with this stuff all the time, it isn't for me.  Easy for me would be a documented function call.

And most all OS services have a C lang interface library where one can read the man page, see the options, the return value, and call within the same process space and it will block until done.  For example, the uid fields for a process table record,  getuid, geteuid, getsuid,  setuid .. etc.  Or for file objects,  open, close, fopen .. etc.   There is no equivalent language interface for manipulating users, yet they are an OS resource.  I've seen code where people directly manipulate the password files, but these days with all the extra stuff with pam and shadow, etc.  that just doesn't seem adequate.  It seems to me that the user resource has sort of graduated to the point it should have a C interface like other resources do.

Hence, my post here, and thinking now the approach would be, for example,  to turn useradd.c  to useradd_0.c  which contains the function, then have an useradd.c with a main that calls the function.  Then put the functions into a library.

However, do to your wise guidance here,  what I've done in my code is to put the calls in which I wished I had,  and then wrote separate local stubs with the fork/exec/waits to the current command files, with a comment at the top 'I wish this was a service interface function'.  Perhaps for grins I'll take my branch copy here and try out making a direct call function.  Still wondering if there is a reason useradd etc. needs to be in its own process space and that something would crash and burn.

And as I said at the top of this thing, I only ever wanted to chat with the developers at this point.  I just didn't see any other means for doing that other than this issues page.

**Comment by Reasoning-Technology** [comment]
the source code for this post may be found here:  
https://github.com/Reasoning-Technology/subu/tree/master/try/useradd_probs

Some issues using a dispatch methodology.  Firstly I should confirm I'm at the right upstream place.  I was developing on a Fedora 29 system today.  I wrote a little 'dispatch' program that does fork/exec/wait for a command passed in.  Here is the output with useradd:

```
2019-02-12T18:46:27Z user@host§~/subu_land/subu/try/useradd_probs§
> ./user-mk temp6
Checking we are running from a user and are setuid root.
uid 49972, gid 49972, euid 0 egid 49972
yes, uid is not zero, and euid is zero, so we are setuid to the root user.
making the home dir path
home dir path: "/home/temp6"
dispatching useradd to create the user
dispatching:
arg: 0x7ffebf3f6800 /usr/sbin/useradd
arg: 0x7ffebf3f6808 temp6
arg: 0x7ffebf3f6810 -d
arg: 0x7ffebf3f6818 /home/temp6

sss_cache must be run as root
useradd: sss_cache exited with status 1
useradd: Failed to flush the sssd cache.
sss_cache must be run as root
useradd: sss_cache exited with status 1
useradd: Failed to flush the sssd cache.
mkdir(/home/temp6, 0x0700)
user-mk: File exists

2019-02-12T18:46:33Z user@host§~/subu_land/subu/try/useradd_probs§

```
This is easily enough confirmed on your side with the code at the github link above.

So three issues with this:
1.  this is a setuid root program running as root, yet sss_cache can not run.  My guess is that instead if it were run as a bash script under sudo it would work.  I.e. sss_cache appears to be looking at the real uid rather than the effective uid. (but I'm interested in the case where the user does not have sudo, and also don't want folks mucking with the program as more nasty things than usual could happen.)

2. useradd makes the directory given with the -d option.  This can be seen on the last line before the prompt. Too bad for me, as we wanted to set facls on other directories before making this directory.  
Note https://linux.die.net/man/8/useradd:
```
-d, --home HOME_DIR
... The directory HOME_DIR does not have to exist but ** will not be created if it is missing. ** 
```
3. as a potential third issues, is there a race between calling 'useradd'  and then calling the C interface routine for the /etc/passwd file 'getpwnam',  or has someone already thought about that and somehow locked /etc/passwd file from access by getpwnam() until the exec of useradd is done?

Thanks again for your thoughtful replies.

**Comment by hallyn** [comment]
I'd actually bemore interested in p9 factotum code being brought in (which would go the opposite direction).  My worry here is that the more code links against tihs libuseradd.so, the more we'll get cases of programs with an odd context doing the wrong thing when they think they're doing the right thing, and hosing a system.

I'm not saying I wouldn't look at a patch that broke out a libuseradd.so.  But I am not planning to write one.
