### ISSUE TITLE
Release 4.6.1 (or 4.7)?

### ISSUE THREAD

**Issue by AkihiroSuda** [shadow-maint/shadow#159]
There has been a lot of changes since 4.6: https://github.com/shadow-maint/shadow/compare/4.6...master

**Comment by hallyn** [comment]
I'll do one in the next few weeks.

Should we do these on some sort of schedule?  4 times a year?  Every month?  Or do we go by when a certain number of commits go by?  What do downstreams prefer?

**Comment by t8m** [comment]
As Fedora downstream I'd prefer making the releases time-based or something like - have a fixed release date every 6 months but if there is a serious bugfix/security issue that needs to be fixed in-between add this minor release as an extra one.

**Comment by hallyn** [comment]
I'll aim for major releases December and June.  Intend to do a pre-release or release this week.
