### ISSUE TITLE
Any reasons to not include backup script in upstream?

### ISSUE THREAD

**Issue by BryanQuigley** [shadow-maint/shadow#166]
I'm working on prepping a fix for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922935, but realized I could just submit that upstream.   Is there a reason to keep the cronjob out of this tree and only in Debian?

IP: https://github.com/BryanQuigley/shadow/commit/6f6044bf653cbdb58721e2b2e68fe348c4d6dad9

**Comment by hallyn** [comment]
Hi Bryan,

I think I'd agree that the cronjob isn't really needed any more.  Let me know if you guys decide it needs to be kept, and then I don't really mind sticking it somewhere upstream.  Maybe under a /config or /contrib sub-dir?
