### ISSUE TITLE
running the tests (in vagrant)

### ISSUE THREAD

**Issue by oskude** [shadow-maint/shadow#168]
how do we run the tests?

i'm paranoid to run the tests in chroot on my host _(in case i screw-up and bork my host)_, so i created a quick vagrantfile:

```
Vagrant.configure(2) do |co|
	co.vm.box = "debian/stretch64"
	co.vm.provision "Setup", type: "shell",
		inline: <<-EOF
			apt-get -y update
			apt-get -y upgrade
			apt-get -y install autopoint xsltproc expect build-essential autoconf libtool gettext bison
		EOF
	co.vm.provision "Build", type: "shell",
		privileged: false,
		run: "always",
		inline: <<-EOF
			cd /vagrant
			./autogen.sh --without-selinux --disable-man
			make
		EOF
	co.vm.provision "Test", type: "shell",
		run: "always",
		inline: <<-EOF
			set -x
			cd /vagrant/tests
			./run_all
		EOF
end
```

during `vagrant up`, provisions "Setup" and "Build" seem to work, but "Test" fails with:

```
==> default: Running provisioner: Test (shell)...
    default: Running: inline script
    default: ++ cd /vagrant/tests
    default: ++ ./run_all
    default: +: test passed
    default: -: test failed
    default: find: '/root/build/shadow-4.1.5/': No such file or directory
```

what am i doing wrong?

> ps. i didn't find any documentation on how to run the tests, so i simply guessed `tests/run_all`.

**Comment by hallyn** [comment]
Yeah I've been looking for a good way to run the tests.  I was thinking I'd just use a temporary lxc or lxd container.  That way we actually should be able to run them in travis as part of CI, which would be nice.

I'll see what I can do in the next few days or weeks.

**Comment by oskude** [comment]
cool!

> FWIW, no need to hurry, my use-case is just for my personal setup. _(and heres a heat-wave so i'm not doing much on pc anyway)_

**Comment by rbalint** [comment]
@hallyn I planned running the tests as autopkgtests, but the tests are now gone from the release tarball. Having tests re-added would enable going this way.
https://salsa.debian.org/rbalint/shadow/commits/autopkgtest

**Comment by rbalint** [comment]
For the record the tests were failing when I tried running them. The failures can be observed here: https://salsa.debian.org/rbalint/shadow/pipelines

**Comment by hallyn** [comment]
Actually doing a new release in the next few weeks was on my agenda, so I'll aim to do that.

**Comment by hallyn** [comment]
The tests are a bit painful because they use such high subuids that normal unprivileged containers can't run them.

What I've done for now is enabled .travis.yml to run the tests.  Travis runs them under kvm.

Only some of the tests are enabled right now, I'll work on adding and fixing more.

This is done in github.com/hallyn/shadow#libsubid right now.  Once that merges I may have to finish enabling travis integration for PRs, but my branches in hallyn/shadow are already running travis tests.  Yay.

**Comment by hallyn** [comment]
Some tests are now running for PRs.  They are explicitly enabled
tests/run_some .  Pull requests to enable more tests definately
appreciated.  I need to spend a bit more time looking at results
and making prs fail when tests fail.  But these should now
definately run in a lxc container.
