### ISSUE TITLE
musl: bcrypt support

### ISSUE THREAD

**Issue by seitokaichou** [shadow-maint/shadow#174]
musl libc [supports bcrypt](https://git.musl-libc.org/cgit/musl/tree/src/crypt/crypt_blowfish.c) password hashing. 
Perhaps this crypt method could be supported if the compile-time check reveals musl being used?

**Comment by hallyn** [comment]
Would you like to propose a patch for that?

**Comment by seitokaichou** [comment]
Yes. In a week or so.

**Comment by seitokaichou** [comment]
Very late and far from complete, but maybe #179 can help get things started.

**Comment by chutz** [comment]
https://github.com/besser82/libxcrypt also supports bcrypt, and another one called yescrypt that would be nice to have.
