### ISSUE TITLE
Changing password is forced if it was set on Jan 1 1970

### ISSUE THREAD

**Issue by tpimh** [shadow-maint/shadow#178]
On boot I'm asked to change my password if password was set on Jan 1 1970. There is no such problem with passwords set on Jan 2 1970.

How to reproduce:
1. The contents of `/etc/shadow`: `root::0:0:99999:7:0::`
2. Reboot
3. Be greeted with `Your password has expired.  Choose a new password.` (unexpected)
4. Change the contents of `/etc/shadow` to `root::1:0:99999:7:0::`
5. Reboot
6. System boots normally, doesn't ask for a password (expected)

**Comment by jamescassell** [comment]
Pretty sure this is expected. When I need to force a password change, I typically run `chage -d 0 user`. Perhaps it should be better documented.

**Comment by edneville** [comment]
> Perhaps it should be better documented.

The definition of the password age is described in `man 5 shadow`, which is referenced at the end of the `chage` man page. This should be clearer IMHO.
