### ISSUE TITLE
vipw does not resume properly when suspended

### ISSUE THREAD

**Issue by millert** [shadow-maint/shadow#185]
If vipw is suspended (e.g. via control-Z) and then resumed, it often gets immediately suspended.  This is easier to reproduce on a multi-core system.

```
root@buster:~# /usr/sbin/vipw

[1]+  Stopped                 /usr/sbin/vipw
root@buster:~# fg
/usr/sbin/vipw

[1]+  Stopped                 /usr/sbin/vipw

root@buster:~# fg
[vipw resumes on the second fg]
```

The problem is that vipw forks a child process and calls waitpid() with the WUNTRACED flag.  When the child process (running the editor) is suspended, the parent sends itself SIGSTOP to suspend the main vipw process.  However, because the main vipw is in the same process group as the editor which received the ^Z, the kernel already sent the main vipw SIGTSTP.

If the main vipw receives SIGTSTP before the child, it will be suspended and then, once resumed, will proceed to suspend itself again.

There are two main ways to fix this.  I've attached patches for each approach.

1. Don't pass the WUNTRACED flag to waitpid() in vipw.c and just assume the main vipw will receive a stop signal from the kernel.  This is the simplest fix and works fine for stop signals generated due to ^Z.  However, if someone sends SIGSTOP to the vipw child process via the kill command, the parent vipw will not notice.

[vipw-resume-simple-fix.txt](https://github.com/shadow-maint/shadow/files/3805363/vipw-resume-simple-fix.txt)

2. The other option is to run the child process in its own process group as the foreground process group.  That way, control-Z will only affect the child process and the parent can use the existing logic to suspend the parent.

[vipw-resume-pgrp-fix.txt](https://github.com/shadow-maint/shadow/files/3805362/vipw-resume-pgrp-fix.txt)

**Comment by hallyn** [comment]
Thank you for opening the issue here.  I think that given the limitation of option 1, we'll have to opt for a version of patch number 2.  @brauner let me know if you have any other opinions on this.

**Comment by brauner** [comment]
The 2. options sounds good to me too.
