### ISSUE TITLE
All binaries are now always installed `/bin` and `/sbin`

### ISSUE THREAD

**Issue by chutz** [shadow-maint/shadow#196]
Some distros still care about `/bin` vs `/usr/bin`. The change https://github.com/shadow-maint/shadow/commit/e293aa9cfca0619a63616af75532637dab60d49d makes it so all binaries are always installed to `/bin`/`/sbin`. The only way to restore the previous behaviour of installing some binaries to `/usr/bin`/`/usr/sbin` is to revert the patch.

**Comment by hallyn** [comment]
Hm.  I'll have to look in a bit - I don't know why I didn't think it was doing that.

Please feel free to do a PR doing the revert.

**Comment by chutz** [comment]
Maybe the "right" solution to get the behaviour I suspect you were aiming for is to have a `--binprefix` configure flag. Have it default to `prefix`, but allow it to be overridden.

**Comment by hallyn** [comment]
Thanks, merged the revert, so closing this.

**Comment by hallyn** [comment]
If you need a 4.8.1 release with this revert, please shout.
