### ISSUE TITLE
User add logging

### ISSUE THREAD

**Issue by edneville** [shadow-maint/shadow#198]
On a multi-admin system it can be tricky to track down who added a user.

If a TTY exists when useradd is run, can that be logged in the syslog entry?

If this idea is acceptable, let me know and I'll raise a PR.

**Comment by vapier** [comment]
how would logging the tty help ?  that's going to be largely meaningless names like `/dev/pts/5`.

i'm guessing you want something like `last` that tracks back to the original user login.

**Comment by edneville** [comment]
Yes, that's exactly why. Using `last -t YYYYMMDDHHMMSS` will show 'gone' for the user on that TTY at that time.
