### ISSUE TITLE
useradd shell check and nologin

### ISSUE THREAD

**Issue by jubalh** [shadow-maint/shadow#207]
https://github.com/shadow-maint/shadow/pull/187 has a small drawback:

Sometimes we might want to point to nologin for some users:
```
useradd -r -s /sbin/nologin -c "nobody" -g nobody -d /var/lib/nobody -u 65534 nobody
```

AFAIK `/sbin/nologin` is provided by util-linux only. On some systems during initial setup it might be that util-linux is not installed yet.

So I'm thinking whether we should
* skip the check introduced in #187 for system users (`-r`)
* allow nologin always and don't check for it
* leave the responsibility for the user/distribution and don't change anything
* more ideas?

**Comment by hallyn** [comment]
https://github.com/shadow-maint/shadow/blob/master/src/nologin.c

**Comment by hallyn** [comment]
I'm going to close this, as it seems to me the underlying assumption is wrong.  Please re-open if I'm misunderstanding.
