### ISSUE TITLE
HOME_MODE.xml missing from 4.8.1 tarballs

### ISSUE THREAD

**Issue by 0strodamus** [shadow-maint/shadow#217]
The HOME_MODE.xml file is missing from the 4.8.1 tarballs which generates a "No rule to make target 'login.defs.d/HOME_MODE.xml', needed by 'man5/login.defs.5" error during compile.

**Comment by tpgxyz** [comment]
@hallyn Looks like tarball is broken.

**Comment by hallyn** [comment]
Hi,

looks like 085d04c3dd did not add that file to the login_defs_v definition in man/Makefile.  I'll push a patch to do that.

**Comment by hallyn** [comment]
Not sure whether it would be best to create a 4.8.2 branch which only has this commit on top of 4.8.1, to do the release, or just do a 4.8.2 from master with the few extra commits, though they carry risk of extra regression.
