### ISSUE TITLE
Make chpasswd SELinux aware

### ISSUE THREAD

**Issue by csanders-git** [shadow-maint/shadow#22]
Currently chpasswd, if set in a liberal context, can be used in order to modify /etc/passwd and /etc/shadow. If the user has (granted for some strange reason) set up the root user within an selinux sandbox environment, for instance user_u, chpasswd will not check if the user is restricted via selinux context, when PAM is not compiled. Currently investigating with @robopt - seems to be stock configuration in centos.

**Comment by hallyn** [comment]
Does it need to be selinux aware?  The kernel should enforce the policy without chpasswd's help, right?  i could see that updated (newly created) files by chpasswd might need a custom context set, but I haven't heard any other bug reports about this.

Closing as I suspect it was in fact found to be a centos configuration error, please re-open if appropriate.
