### ISSUE TITLE
configure error in non-selinux gnu/linux

### ISSUE THREAD

**Issue by sulincix** [shadow-maint/shadow#220]
![Screenshot_2020-02-09_00-31-00](https://user-images.githubusercontent.com/55052890/74094101-80f02c80-4ad3-11ea-8f65-f537633be60f.png)
```
./autogen.sh
./configure --prefix=/usr \
		--sysconfdir=/etc \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--localstatedir=/var \
		--disable-nls \
		--with-libpam \
		--without-audit \
		--without-selinux \
		--without-acl \
		--without-attr \
		--without-tcb \
		--without-nscd \
		--without-group-name-max-length

```

**Comment by sulincix** [comment]
I found fix
`./autogen.sh --help` fixed :D

**Comment by sulincix** [comment]
I think We must remove systemd header checking in autogen.sh

**Comment by sulincix** [comment]
https://github.com/shadow-maint/shadow/pull/221

**Comment by jubalh** [comment]
The above mentioned PR got closed due to confusion. I believe this issue can be closed as well.
