### ISSUE TITLE
question: default hash value

### ISSUE THREAD

**Issue by donovank** [shadow-maint/shadow#222]
Why in `useradd.c` is the default password set to '!' instead of '*' (see [here](https://github.com/shadow-maint/shadow/blob/2cc7da6058152ec0cd338d4e15d29bd7124ae3d7/src/useradd.c#L112))? It seems like given the symbolic meaning of a bang the hash would be better suited being an asterisk. Is there any specific reason it's defaultly a bang?

Thanks

**Comment by edneville** [comment]
I think `!` is preferred for locking the password crypt, though both `*` and `!` will suffice as neither are computable. Probably just a matter of opinion though. usermod understands a `!` prefix to mean locked, but not a `*` in the same way.

What would be the benefit of using `*` for empty passwords? usermod doesn't remove a `!` to leave the field empty. Maybe `*` should be used for accounts within the SYS_UID range, but this is not likely to bring much.

**Comment by jubalh** [comment]
This was a rather short discussion, which I believe can be closed now.
