### ISSUE TITLE
Code documentation: comment at #endif does not match condition of #if

### ISSUE THREAD

**Issue by hagman** [shadow-maint/shadow#223]
The comment at https://github.com/shadow-maint/shadow/blob/master/src/passwd.c#L285 says `/* USE_SHA_CRYPT */` when it shoud rather say `/* USE_BCRYPT */` in order to match the condition in https://github.com/shadow-maint/shadow/blob/master/src/passwd.c#L283

**Comment by seitokaichou** [comment]
Nice catch. I feel bad for asking, but did https://github.com/shadow-maint/shadow/pull/179 actually receive any code review? I might have made more mistakes, and it seems to me that it got merged rather hastily.

**Comment by seitokaichou** [comment]
I should add to this: there is still work to be done on the bcrypt support (at the minimum, documentation and tests, and possibly more).
