### ISSUE TITLE
Why not add the function of deleting users in batch?

### ISSUE THREAD

**Issue by blueskycs2c** [shadow-maint/shadow#225]
I found the command newuser to add users in batches, but did not find the function to delete users in batches.Why not add the function of deleting users in batch?

**Comment by edneville** [comment]
I think the reason for this is perhaps:
1. `newusers` reads colon separated input, deletions requires only the login
2. `newusers` has a plural name
3. deletions are destructive, there is less call to delete accounts than to create, it happens less. Deleting a user can make it harder to track down who did what if you can a UID and no name to relate it to, therefore it is more common to lock the account (with chage -E, for example) and leave the account. File ownership remains with the user who created it and you don't get the oddities of inherited /home/ directories.

It wouldn't take much work to read batch input to perform removals:

```
while IFS= read -r LOGIN; do
    userdel -f -r "$LOGIN"
done < logins
```

I don't know if it makes sense to add a program that doesn't bring much that the three lines above can't do.

Maybe I'm missing something, if there is a strong need, I wouldn't mind putting the time in, but I think it could easily be usurped by similar scripts as the above.

**Comment by blueskycs2c** [comment]
Thanks for your reply.
it's for safety reasons, I agree with you.
