### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by DavidKCalnex** [shadow-maint/shadow#238]
Don't know if this has been answered but I'm confused by the licensing on this project that's available [here](https://github.com/shadow-maint/shadow/blob/master/COPYING) it says:

> This license has been obsoleted by the change to the BSD-style copyright.

Does this mean this is licensed under BSD and if so what variant of BSD is it ? I don't want to presume. If this is the wrong place can you redirect me to the correct place to ask this question.

**Comment by DavidKCalnex** [comment]
Ok thanks for responding I've used the exact wording that's in the license on GitHub for the moment.

**Comment by hallyn** [comment]
What do people think?  Should we

1. Leave it as is
2. Remove the note about replacing with BSD license
3. Honor that comment and replace the LICENSE file with a BSD style license?

**Comment by vapier** [comment]
should replace it with the appropriate BSD license and be done.  then people won't get confused :).

**Comment by hallyn** [comment]
Yeah i'll do that, thanks.  Someone please shout if i don't remember to do it soon.

**Comment by ariel11** [comment]
@hallyn - sounds great.  Did you decide which BSD license you are going to use?

**Comment by hallyn** [comment]
No I did not :(

Every time I sit down to read up on license details, I accidentally end up grabbing a pair of pliars and pulling out toenails instead.  Not sure how this happens.

**Comment by ariel11** [comment]
@hallyn - Well, looks like someone added the BSD-3-Clause license to the file headers?

![image](https://user-images.githubusercontent.com/17935946/91789685-fe8c9e80-ebc3-11ea-8643-dc0085c85a01.png)

**Comment by jfhaugh** [comment]
This package predates both Linux and really widespread use of the GPL. When it was written a lot of people just said "Hey, use this!".

If someone needs me to officially say "Rip out the Artistic License", I can say "Rip out the Artistic License".

**Comment by jfhaugh** [comment]
> @hallyn - sounds great. Did you decide which BSD license you are going to use?

If forget why you want to use the 3-Clause BSD license, but I believe that's the one you want to use. I'd have to look in all of my files at the house to see when Tomasz (he wasn't the original maintainer after I stopped) actually started contributing. I'm pretty sure he is the one who went from "shadow 3" to "shadow 4", though I believe I have files from when he released 4.0.1.

I'm not sure how _*this*_ collection of code wound up with the _Artistic_ license in it since what Marek got from me didn't, as I recall. And what Tomasz sent me for 4.0.1 didn't either. But I did, at one time, do a release with Larry Wall's license, just not sure how this got to be what it is.

**Comment by hallyn** [comment]
See https://github.com/shadow-maint/shadow/issues/324 .

So I'll put the three clause BSD license in COPYING and point out there the four clause license for those four files.

**Comment by ErikBergfurInfor** [comment]
Any progress on this @hallyn? I looked at it briefly and to me it seemed we could just "upgrade" to a simple 2-clause BSD license and be done with it.

**Comment by rbalint** [comment]
Next shadow will need an FTP Master review due to the addition of the new library. The review will include reviewing the license and if re-licensing takes place I'd appreciate if that could happen before releasing 4.10. Otherwise I have to revisit every file for the proper license and update https://salsa.debian.org/rbalint/shadow/-/blob/master/debian/copyright just to update it again. :-(

**Comment by andrewshadura** [comment]
@rbalint, FYI: https://gitlab.apertis.org/pkg/shadow/-/blob/apertis/v2023dev0/debian/apertis/copyright

**Comment by jfhaugh** [comment]
Please update my email address. That might be a nice thing to do!

**Comment by hallyn** [comment]
> Please update my email address. That might be a nice thing to do!

In the AUTHORS file?  Or is it elsewhere?  What email address would you like it to show?

**Comment by jfhaugh** [comment]
> > Please update my email address. That might be a nice thing to do!
> 
> In the AUTHORS file? Or is it elsewhere? What email address would you like it to show?

AUTHORS. I'm the original AUTHOR ;)

Replace ` jockgrrl@ix.netcom.com` with `julie78787@gmail.com`.

I've not grep'd the repo to see if any out outdated email addresses are still in there, but if someone could do that before putting up a PR that would be much appreciated as well.

**Comment by hallyn** [comment]
> Any progress on this @hallyn? I looked at it briefly and to me it seemed we could just "upgrade" to a simple 2-clause BSD license and be done with it.

That drops the endorsement clause which seems like it might upset people.  I've known sleazy enough people to not want to drop that.

**Comment by hallyn** [comment]
> Replace ` jockgrrl@ix.netcom.com` with `julie78787@gmail.com`.

Done in a separate commit, thanks.

**Comment by hallyn** [comment]
Started a branch for this.  Comments appreciated, notwithstanding the fact that deleting the github project would be more fun.

**Comment by hallyn** [comment]
While my original plan had been to use the spdx default of bsd 3 clause license to just remove the text from all files, most of them had (all slightly varying) copyright statements which it doesn't feel right to remove.

**Comment by jfhaugh** [comment]
> > Any progress on this @hallyn? I looked at it briefly and to me it seemed we could just "upgrade" to a simple 2-clause BSD license and be done with it.
> 
> That drops the endorsement clause which seems like it might upset people. I've known sleazy enough people to not want to drop that.

Not sure why someone would be "sleazy" for wanting to keep the "no endorsements" clause.

Is there a reason for wanting the "upgrade"? I greatly prefer the 3-clause license over the 2 or 4 clause ones.

**Comment by hallyn** [comment]
> > That drops the endorsement clause which seems like it might upset people. I've known sleazy enough people to not want to drop that.
> 
> Not sure why someone would be "sleazy" for wanting to keep the "no endorsements" clause.

Hah, no, someone would be sleazy to try and use your name to endorse say a bad linux distro because it had the shadow package.

> Is there a reason for wanting the "upgrade"? I greatly prefer the 3-clause license over the 2 or 4 clause ones.

Thanks for your input.  I agree,  am sticking with the 3-clause.

**Comment by jfhaugh** [comment]
I do like the SPDX cleanup I'm seeing. Nice work. Trying to keep all of the text consistent would be a full-time job without that.

I'm off to breakfast. Ping me when #451  is done and I'll put my approval thing on it.

**Comment by hallyn** [comment]
Thanks.  The last commit or two were a bit too rushed.  I want to look over them again tonight before calling it ready for review.

**Comment by hallyn** [comment]
Ok @jfhaugh , #451 should be ready for review.  Thanks.
