### ISSUE TITLE
Allow directory "/nonexistent" or the like

### ISSUE THREAD

**Issue by lifecrisis** [shadow-maint/shadow#239]
Greetings:

I use Debian, so robot users on my system have home directory set to `/nonexistent` in the `/etc/passwd` file.

Normally this is fine, but when my team builds custom Debian FAI images, we would like to be able to run `pwck` as part of the process.  This becomes problematic because users with `/nonexistent` home directories are flagged as having bad `/etc/passwd` entries (causing exit status 2).

I would like to submit a patch that allows for explicitly setting the home directory to `/nonexistent` when a user is not supposed to have a home.

Would such a patch be accepted?  I want to ask before doing the work...

Thanks!

**Comment by vapier** [comment]
this doesn't sound like it has wider distro/*NIX usage, so adding it to the canonical package sounds inappropriate to me.

how about adding a configure flag or runtime config option for it instead ?

**Comment by lifecrisis** [comment]
That sounds fine to me.  I think a runtime configuration option makes the most sense, so that no one has to re-build if they want to change it.

Would it be okay if I worked on a PR to add it?

**Comment by vapier** [comment]
i think it sounds fine, but i'm not the one who would be merging the PR :)

**Comment by hallyn** [comment]
The earlier part of your description makes sense, but I'm not sure I'm following this part:

```
I would like to submit a patch that allows for explicitly setting the home directory to /nonexistent when a user is not supposed to have a home.
```

Are you wanting for pwck to simply ignore a nonexisting homedir if it matches a particular path (which can be passed to ./configure), or for pwck to actually set the homedir to that path?  If the latter, how would pwck decide which accounts to do this for?

**Comment by lifecrisis** [comment]
@hallyn:  Definitely the former.  If the home directory path matches a particular string set either at compile-time or in runtime config file, then `pwck` will not return an error when a user has this home directory and it doesn't exist.

**Comment by hallyn** [comment]
I'm fine with this - you could even add it to login.defs?

**Comment by lifecrisis** [comment]
@hallyn Great!

Sure, adding it to `login.defs` sounds like a good idea.  I'll get to work on a patch. :)

**Comment by lifecrisis** [comment]
@hallyn -- Friendly update: See the PR that mentions this issue.

I think there is a lot that could be done here.  Of course, how much more _needs_ to be done is up for debate.  I went for the minimal solution in the PR that fixes the issue for Debian-based systems.
