### ISSUE TITLE
 Stop the operation or print a warning from useradd if -u is used with uid number outside range.

### ISSUE THREAD

**Issue by blueskycs2c** [shadow-maint/shadow#240]
eg:
     $ useradd -u 456 test456 
     $ useradd -r  -u 1050 test1050

    In the manual
     -r, --system 
     System users will be created with no aging information in /etc/shadow, and their numeric identifiers are chosen in the SYS_UID_MIN-SYS_UID_MAX range
     UID_MAX (number), UID_MIN (number)
           Range of user IDs used for the creation of regular users by useradd or newusers.
     

test456 is a regular users,but 456 outside of the UID_MIN and UID_MAX range.
1050 is a system user ,but 1050 outside of the SYS_UID_MIN and SYS_UID_MAX range. 
It is better to stop the operation or print a warning from useradd if -u is used with uid number outside range.

**Comment by blueskycs2c** [comment]
@t8m  please take a look. Thanks

**Comment by t8m** [comment]
I do not think stopping the operation would be appropriate as that would break existing use-cases. But printing a warning makes sense to me.

**Comment by blueskycs2c** [comment]
> 
> 
> I do not think stopping the operation would be appropriate as that would break existing use-cases. But printing a warning makes sense to me.

Thanks for your reply! @t8m  and I will prepare a patch for this.

**Comment by superlazyname** [comment]
Hello, what is the problem that can occur if a uid is provided to useradd that is outside of UID_MAX?

It's not clear from the docs what exactly UID_MAX is used for in useradd.

Most man pages say: 
> Range of user IDs used for the creation of regular users by useradd or newusers.
> The default value for UID_MIN (resp.  UID_MAX) is 1000 (resp. 60000).

Some [unofficial posts](https://serverfault.com/questions/105260/how-big-in-bits-is-a-unix-uid#comment807745_105265) have interpreted this as
> The [manpage](http://linux.die.net/man/5/login.defs) for login.defs indicates that in that context, UID_MAX only controls the highest uid that will automatically be assigned for new users created with useradd

Taking a cursory glance of the source, I don't see anything that will obviously break if somebody tries to specify a uid that's bigger than UID max, and it seems like the main thing UID_MAX does for useradd is just print this warning.

Are there any other, more sneaky issues I should be aware of? Thanks,
