### ISSUE TITLE
Would like to be able to map GID Maps of users into user namespace with newgidmap

### ISSUE THREAD

**Issue by rhatdan** [shadow-maint/shadow#260]
Currently newgidmap blocks access to any GIDs not listed in /etc/subgid, or the GID of the user running newgid.  We would like to also map the other GIDs that the user running newgid is currently using.

The reason we need this is for rootless podman to have access to files that a user has GID access to.
For example if a user volume mounts into a container a directory owned by a specific gid or setgid to that group and the user running podman has is in the gid group, we would like to be able to map that gid to the container

`--gidmap 10:10:1` for example to map the wheel group into a container.

Is there a security issue that prevents this?

**Comment by rhatdan** [comment]
@giuseppe FYI

**Comment by rhatdan** [comment]
@vrothberg FYI

**Comment by hallyn** [comment]
I do seem to recall Eric Biederman having a reason to not do that, but I'm not sure what it was.  It seems trivial to circumvent if the user wanted to do something bad.

So to be clear, you mean that newgidmap would support mapping any of the calling user's aux groups, right?

**Comment by rhatdan** [comment]
Correct.  We would add a flag like --keep-groups.

**Comment by alexey-tikhonov** [comment]
Is this a duplicate of #135 ?

**Comment by rhatdan** [comment]
Yes
