### ISSUE TITLE
grpck: questionable warning

### ISSUE THREAD

**Issue by patrakov** [shadow-maint/shadow#261]
Hi,

I have an intention to set up a system as follows:

* User `me` should not have `test-sg` in his list of auxiliary groups when logging in
* User `me` should be able to explicitly assume this group when needed, using `sg`, without password

This intention is satisfied by making `me` a member of `test-sg` in `/etc/gshadow`, but not in `/etc/group`. Even more, such group transitions are properly logged in `auth.log`.

The only problem is that this (valid) setup triggers a warning from grpck:

    'me' is a member of the 'test-sg' group in /etc/gshadow but not in /etc/group

As explained above, this is a setup that has a 100% valid use case. So please make this check optional, or completely remove it.

Note: in this issue, I express no firm opinion regarding the opposite warning. Let's assume it is still valid, until someone proves otherwise.

**Comment by hallyn** [comment]
Thanks for the patch.

I wonder whether we should turn it around - and instead have a "--paranoid" option which enables the check?  That's under the pessimistic assumption that we'll find other such cases.

**Comment by hallyn** [comment]
Or if you want to just remove the check, that's fine too.
