### ISSUE TITLE
groupadd and groupmod should be able to add members

### ISSUE THREAD

**Issue by sjvudp** [shadow-maint/shadow#265]
`groupadd` and `groupmod` both have no option to _provide a list of **group members**_ (the list after the GID).
Suggested options could be "`-a|--append`" (append names) and "`-U|--users`" (provide list of users, similar to "`-G`" of `usermod`).

**Comment by hallyn** [comment]
This sounds good.  Do you mind posting a PR for it, or do you prefer that I do it?

**Comment by sjvudp** [comment]
>>> Serge Hallyn <notifications@github.com> schrieb am 25.07.2020 um 02:22 in
Nachricht <shadow-maint/shadow/issues/265/663781915@github.com>:
> This sounds good.  Do you mind posting a PR for it, or do you prefer that I 
> do it?

Hi!

Feel free do so so!

Regards,
Ulrich
