### ISSUE TITLE
suggest to use --badnames in case of invalid username

### ISSUE THREAD

**Issue by Estirp** [shadow-maint/shadow#266]
In case of
`useradd é`
`useradd: invalid user name 'é'`

I think the message should be 
`useradd: invalid user name 'é' : You should conform to the regex ... or use --badnames.`

**Comment by hallyn** [comment]
Good idea - would you mind making a PR for this or do you prefer I do it?

**Comment by Estirp** [comment]
I prefer you do it.
Thanks.

Le 25/07/2020 à 02:20, Serge Hallyn a écrit :
