### ISSUE TITLE
uknown login.defs options

### ISSUE THREAD

**Issue by karelzak** [shadow-maint/shadow#276]
Hi guys, 

as you know the file /etc/login.defs is shared between more packages. I'd like to ask how problematic for shadow-utils is new foreign options in the file? For example, if we add in util-linux something (a new option) to the file --  do you want to be informed about such change or your login.defs parser silently ignores unknown options? 

From lib/getdef.c:def_find() it seems that in some cases it prints 
     _("configuration error - unknown item '%s' (notify administrator)\n")

I can prepare PR with the missing options (if you want it/need it).

**Comment by brauner** [comment]
Hm, good question. I think we should probably coordinate on adding new options so being informed about such a change is probably a good way to go. That's what my gut tells me.

**Comment by hallyn** [comment]
PR would be appreciated, thanks.

**Comment by karelzak** [comment]
What about to make shadow-utils login.defs a little bit more promiscuous and do not report unknown options at all? We use the same solution in util-linux.

**Comment by karelzak** [comment]
OK, PR to add foreign items (util-linux in this case) created.

**Comment by hallyn** [comment]
Thanks.
