### ISSUE TITLE
Inaccurate description about ID range in man newuidmap and newgidmap

### ISSUE THREAD

**Issue by towerpark** [shadow-maint/shadow#280]
Hi all,

The man page of `newuidmap` says:
> ... and that for each of the above sets, each of the UIDs in the range **[loweruid, loweruid+count]** is allowed to the caller according to /etc/subuid before setting /proc/[pid]/uid_map.

Generally a notation in form of [A, B] implies the end of the range is inclusive, which was what I believed until I dug into the source code. Since the last available ID is loweruid+count-1 (if I read the code correctly), I think [loweruid, loweruid+count) should be better.

The same for `newgidmap`.

The source code of man is here:
https://github.com/shadow-maint/shadow/blob/9a10373ddb8e0a302d791cbfb6a44a841fe5d83d/man/newuidmap.1.xml#L130
https://github.com/shadow-maint/shadow/blob/9a10373ddb8e0a302d791cbfb6a44a841fe5d83d/man/newgidmap.1.xml#L130

**Comment by hallyn** [comment]
Yeah, that sounds good - would you like to post a pr for that or do you prefer that we do it?

**Comment by towerpark** [comment]
Yeah, I can do that. I will make a PR for it.
