### ISSUE TITLE
Incorrectly denies valid usernames

### ISSUE THREAD

**Issue by swe-nidan** [shadow-maint/shadow#283]
Sorry if I'm mistaken, but I think this line is incorrect, as well as the similar checks further down in the file:

https://github.com/shadow-maint/shadow/blob/9d3546c695baf6111dab8140e8c83010aaf6e2ed/libmisc/chkname.c#L62

I've checked the Linux Standard Base where I cannot find anything about limitations to usernames, other than that it defers to POSIX.

Some small chunks from POSIX:
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_437

> 3.437 User Name
> A string that is used to identify a user; see also User Database. To be portable across systems conforming to POSIX.1-2017, the value is composed of characters from the portable filename character set. The <hyphen-minus> character should not be used as the first character of a portable user name.
> 

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282

> 3.282 Portable Filename Character Set
> The set of characters from which portable filenames are constructed.
> 
> A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
> a b c d e f g h i j k l m n o p q r s t u v w x y z
> 0 1 2 3 4 5 6 7 8 9 . _ -
> 
> The last three characters are the <period>, <underscore>, and <hyphen-minus> characters, respectively. See also Pathname.
> 

Maybe someone, 13 years ago according to git blame, mistook the definition of "Name" for
the definition of "User Name":
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_235

> 3.235 Name
> 
> In the shell command language, a word consisting solely of underscores, digits, and alphabetics from the portable character set. The first character of a name is not a digit.
> 
> Note:
>     The Portable Character Set is defined in detail in Portable Character Set.
> 
> 

as the code matches the Name section instead of the "User Name" section. (Almost, the code also incorrectly denies uppercase characters, unless there is some squashing done somewhere before the function.)
The current code thus denies valid (according to POSIX) usernames such as "0c0ff1e", "0c001" or even "Aaron". These default limitations are too stringent, for no apparent reason.

As a side note, the default limitation of 32 characters is too low imho. (But wouldn't help my current case anyway as my system's utmpx ut_user entry happens to have the same size.)

**Comment by jubalh** [comment]
This was solved in https://github.com/shadow-maint/shadow/pull/551and is with https://github.com/shadow-maint/shadow/commit/cfc981df2 part of shadow since 4.13.
