### ISSUE TITLE
Compile break due to xfree

### ISSUE THREAD

**Issue by masmullin2000** [shadow-maint/shadow#284]
xfree is undefined

Steps to Reproduce (Fedora 32)

1) git clone https://github.com/shadow-maint/shadow.git
2) ./autogen.sh
3) ./configure
4) make

Expected Results:
Clean compile

Actual Results
/usr/bin/ld: gpasswd.o: in function `main':
/home/masmullin/code/shadow/src/gpasswd.c:1209: undefined reference to `xfree'
/usr/bin/ld: /home/masmullin/code/shadow/src/gpasswd.c:1212: undefined reference to `xfree'
/usr/bin/ld: /home/masmullin/code/shadow/src/gpasswd.c:1216: undefined reference to `xfree'

**Comment by masmullin2000** [comment]
Issue introduced in 

https://github.com/shadow-maint/shadow/commit/46ad1856ac68f1e0b0c9199211e5bc80e08f21e7

**Comment by masmullin2000** [comment]
Temporary Fix
[0001-temp-fix-for-xfree-issue.patch.txt](https://github.com/shadow-maint/shadow/files/5322114/0001-temp-fix-for-xfree-issue.patch.txt)

**Comment by JonasMatos0** [comment]
Reproducible on Ubuntu 18 ^
