### ISSUE TITLE
useradd: turn off subuid/subgid allocation

### ISSUE THREAD

**Issue by aw32** [shadow-maint/shadow#289]
It would to be nice to be able to turn off allocation of subuids/subgids in `useradd` while having `/etc/subuid` and `/etc/subgid` files.
Defining `SUB_GID_COUNT=0` and `SUB_UID_COUNT=0` in `/etc/login.defs` leads to the error message:
```
useradd: Can't get unique subordinate UID range
useradd: can't create subordinate user IDs
```

**Comment by hallyn** [comment]
Thanks, that does look like a bug.

In addition to fixing that bug, it might be nice to have a --no-subuids --no-subgids option  (maybe only a --no-subids, not sure anyone would ever want just one or the other).
