### ISSUE TITLE
libtool error: shared libsubid library cannot be linked to static library libmisc.a

### ISSUE THREAD

**Issue by fariouche** [shadow-maint/shadow#297]
Hello,

When compiling on one of my systems, I see the following warning:
make[2]: Entering directory '/home/fariouche/apps/src/shadow/shadow/libsubid'
  CC       api.lo
  CCLD     libsubid.la

*** Warning: Linking the shared library libsubid.la against the
*** static library ../libmisc/libmisc.a is not portable!

On an other machine, this is an error (pure 64bits)

Indeed, libmisc/Makefile.am is a static local library and libsubid/Makefile.am is a shared library linking to libmisc.a directly.

A solution is to replace libmisc.a in libmisc/Makefile.am:
--> noinst_LTLIBRARIES = libmisc.la
And replace libmisc_a by libmisc_la in the file and libmisc.a by libmisc.la in libsubid/Makefile.am and everywhere libmisc is used.

Not tested, so some other modifications may be needed too.
For now I'm disabling this feature.

**Comment by hallyn** [comment]
Indeed, I was able to reproduce this.  Odd.  Moving the libmisc library inclusion to the last LD_ADD entry seems to fix it, so I'll push that.

Thanks for reporting this.
