### ISSUE TITLE
Default subuid/subgid file for all uids in the range of 1000-65535

### ISSUE THREAD

**Issue by brianv0** [shadow-maint/shadow#298]
I'm really not sure the best place to ask this, but in an issue related to #154, I really want to be able to synchronize subuid/subgid values across a collection of servers, so I can ideally use podman rootless, and since there's not really nsswitch.conf plugin for subuid/subgid right now (unless I am mistaken), I was was just going to generate a default file for all possible uids and be done with it.

e.g. for max_user_namespaces 10000 - 
```
1000:10000000:10000
1001:10010000:10000
1002:10020000:10000
1003:10030000:10000
1004:10040000:10000
1005:10050000:10000
1006:10060000:10000
...
65535:655350000:10000
```

or for max_user_namespaces 65536:
```
1000:65536000:65536
1001:65601536:65536
1002:65667072:65536
1003:65732608:65536
1004:65798144:65536
1005:65863680:65536
...
65535:4294901760:65536
```

1. Is this a reasonable thing to do in this circumstance? I read there are performance issues with this many entries but they aren't so bad when using the uid numbers
2. I don't have 65535 users, will I have possible issues with useradd if I do this?

**Comment by hallyn** [comment]
I haven't tested this scenario, but it's interesting.  Have you tested it by now, and found performance issues?  (i.e. increased login time, adduser time, etc).  If you haven't, then I'll set up a test case.

By "possible issues" are you asking about performance, or do you mean because you'll run out of subuids and not be able to create more new users?

**Comment by brianv0** [comment]
I tried to do some testing on this.

I ran a centos 7 VM, writing out the files as such:

```
f = open("/etc/subuid", "w")
for uid in range(1000, 65536):
    f.write("%d:%d:65536\n" %(uid,uid*65536))

f = open("/etc/subgid", "w")
for uid in range(1000, 65536):
    f.write("%d:%d:65536\n" %(uid,uid*65536))
```

I added a user, and then would test `sudo su -l foo -c "echo 1"` several times.

I saw no appreciable login delay, and I was able to run podman (rootless, which relies on subuid/subgid) seemingly with no significant startup delay (after image download). I then deleted the subuid/subgid files and ran `su -l` again.

In both cases, on my VM, the real time was ~0.040 seconds.

The main issue I was worried about was what might happen is when subsequently adding a user - you've preallocated this and you'd want the the process of adding a user to skip modifying subuid/subgid (by default) if the uid number or username is already in subuid/subgid.

In that case, you get something like this with the current defaults for login.defs:

```
1000:65536000:65536
1001:65601536:65536
...
65534:4294836224:65536
65535:4294901760:65536
foo:65536000:65536
```

I tried to set SUB_UID_COUNT to 0 and it didn't like that. So, it'd be nice if you could disable /etc/subuid modification (since the files subuid/subgid exist) via login.defs in some way.

**Comment by brianv0** [comment]
Any thoughts on this - e.g. being able to set SUB_*ID_COUNT to 0 to prevent further modification of the subid files when the files exist and adding a new (local) user? I could try to work on a PR, probably won't get to it for a couple of months.

I think this, if working, is a possible solution/hack/alternative for
https://github.com/shadow-maint/shadow/issues/154

**Comment by hallyn** [comment]
Hi,

login.defs already has SUB_UID_COUNT and SUB_GID_COUNT.  However setting them to 0 is broken right now.  That should be a simple fix to libmis/find_new_sub_uids.c:find_new_sub_uids().  Do you have time to tackle that?  IIUC that should do what you want.

**Comment by hallyn** [comment]
This should be doubly fixed now :)   https://github.com/shadow-maint/shadow/pull/342  fixes SUB_UID_COUNT=0, and nss plugin now exists.
