### ISSUE TITLE
Add yescrypt as ENCRYPT_METHOD

### ISSUE THREAD

**Issue by ghen2** [shadow-maint/shadow#300]
Could `yescrypt` (with prefix `$y$`) be added as a choice for /etc/login.defs ENCRYPT_METHOD?
(This is the default hash generated by `crypt()` nowadays, and is supported by linux-pam since 1.4.0.)

**Comment by hallyn** [comment]
If someone provides a patch linking against an acceptable library implementation, we'll definitely take a look.
