### ISSUE TITLE
Why can gid mappings only be created when running under the user's primary group?

### ISSUE THREAD

**Issue by martijndegouw** [shadow-maint/shadow#304]
I'm trying to use rootless podman, but when I'm trying to run podman when I changed my primary group using either newgrp or runuser, newgidmap returns an error due to the following check:
https://github.com/shadow-maint/shadow/blob/e84df9e163e133eb11a2728024ff3e3440592cf8/src/newgidmap.c#L231

Now I'm wondering why this check is here and why newgidmap/newuidmap is only allowed when the passwd entry is verified.

If I disable this check and modify https://github.com/shadow-maint/shadow/blob/c917ed7b76c31a9aa100477c6c4d281c7d835c93/src/newgidmap.c#L63 from 
`if ((range->count == 1) && (pw->pw_gid == range->lower)) {`
to
`if ((range->count == 1) && (getgid() == range->lower)) {`
everything works as I expect.

Is this check here for security reasons (since we are running with setuid bit) or is it only a sanity check?

**Comment by hallyn** [comment]
Arguably, when you are running a setgid application you may well not want it to have privilege over all your subgids.  There may be cases where that is ok, but if there are cases where it's not ok, then we have to limit it.

Can you say more about why you need to do this after changing your primary group?

**Comment by martijndegouw** [comment]
In my case this we are using a 'service' account as user to the run build agents of our CI environment.

In our environment service accounts all have their primary group set to the service accounts group. This build service account is a member of several other projects (groups). We switch the primary group when running the build agents so files created during the builds have the group set correctly, instead of the service-accounts group.

Recently people requested the usage of docker/podman to create container images as well during their project builds. That's when we found out that the runuser/newgrp trick breaks the usage of rootless podman for us.

**Comment by hallyn** [comment]
For the NFS restrictions, could they simply newgrp back to their original group before running builds?  The container images are presumably not sitting on NFS, right?

It's possible that relaxing this will be the best way forward, but I want to make sure we are not overlooking a simpler, safer solution.

**Comment by martijndegouw** [comment]
I tested if newgrping back to the primary group is possible, once inside the project directory, but that only results in Permission denied errors. The container images are not stored on NFS whatsoever.

**Comment by hallyn** [comment]
@brauner what do you think?

@martijndegouw my sense is to say we are better off not doing this:  giving me access to one additional group id arguably should not automatically give privilege over all subids which may have been added to that group id.  I may have just wanted you to be able to read a few files I own.  Although I find it very hard to come up with a case where those use cases would merge.  I can't think of any real system where one would use group id X as a shared group for >1 user, but also have it be some user's primary id *and* then also give it subids intended for that single user.

So as I type this I've talked myself again into saying this is fine.

**Comment by hallyn** [comment]
Okay given that I don't have a good workaround for you, how about if we add a /etc/login.defs option, default no, called something like GRANT_AUX_GROUP_SUBIDS ?

**Comment by martijndegouw** [comment]
Yes. Any method to enable/disable this behavior would be very welcome.

**Comment by hallyn** [comment]
Do you mind adding that to PR#308?

**Comment by martijndegouw** [comment]
No, not at all. I'll update the PR. Hopefully I can find some time to implement and test it later this week.

**Comment by martijndegouw** [comment]
I updated the PR, please let me know how you feel about this approach. I added some tests as well, since there is a switch to control the behavior now.
