### ISSUE TITLE
compilation error in su.c

### ISSUE THREAD

**Issue by userwithuid** [shadow-maint/shadow#32]
Commit https://github.com/shadow-maint/shadow/commit/8f1836bad9340670ca071f76c84350dcb4e6c712 causes a compiler error in su.c , because 2 `snprintf` statements are missing a max length.

https://github.com/shadow-maint/shadow/blob/6fbc11ce2178205968c37853db752729359c9893/src/su.c#L375

should probably be

```
snprintf (kill_msg, sizeof kill_msg, _(" ...killed.\n"));
snprintf (wait_msg, sizeof wait_msg, _(" ...waiting for child to terminate.\n"));
```

**Comment by falconindy** [comment]
Seems fixed since 67d2bb6e0a5ac124ce1f026dd5723217b1493194 and 924cc346475dea7dc394316cd7c3d5d0414e538e
