### ISSUE TITLE
BSD-4-clause license in some files

### ISSUE THREAD

**Issue by andrewshadura** [shadow-maint/shadow#324]
Hi,

I noticed some files in this package are under the four clause BSD license:

* `contrin/atudel`
* `man/ko/man8/vipw.8`
* `man/hu/man1/chsh.1`
* `man/hu/man1/passwd.1`

Apart from the first one, these seem to be an oversight of a supposed license change — could you please check whether these copyright notices are still up-to-date?

Thanks!

**Comment by hallyn** [comment]
I'm not aware of any history wherein those authors agreed to the three clause license, so IMO we should either attempt to contact the authors, drop those files, or leave them as is.

https://github.com/shadow-maint/shadow/issues/238 has not been resolved, so as part of that we should have a central file which at least points out these four files.  Thank you.

**Comment by jfhaugh** [comment]
I don't believe the translation of a work can change the license of the work it's derived from. I don't remember when Shadow went from Larry Wall's "Artistic License" to the 3-Clause BSD License, but anything derived from 3-Clause source should still be 3-Clause licensed.

Not a lawyer. I just wrote all this stuff ages ago.

**Comment by hallyn** [comment]
Yeah, that makes sense, thanks Julie.  I'll update the sections in the manpage translations.

As for the contrib/atudel case, I wonder whether anyone uses that.  In any case, "contrib/" advertises itself as a bit of a wild west anyway.  I'm tempted to leave that alone.

**Comment by hallyn** [comment]
Then again, that feels weird.  Each of those files has not changed since at least 2012.

It might be better to have those pages re-translated from the original.  Then tweaking the copyright would make sense.  Removing a clause by itself, just because I don't seem to have the full source history, just feels wrong.

**Comment by jfhaugh** [comment]
(Commenting so this history isn't lost)

I'm 99% sure a language translation cannot affect the copyright. I don't know about `vipw` (hated it so I didn't implement it) or `atudel` (never heard of it). I still have the SCCS files for `chsh.1` and `passwd.1` going back to 1989.

**Comment by vapier** [comment]
depends on whether the translations contain additional content not in the original. they shouldn't, but who knows.

if we're confident they're only translations, then change the license and drop a note to the author. if they object, just delete it and wait for someone else to translate.

**Comment by andrewshadura** [comment]
My limited knowledge of Hungarian (without trying Google Translate) and the overall structure of the manpages suggest they’re both translations of old versions of the manpages, some sections are there but others are missing (e.g. **OPTIONS**). I’m not sure without looking into that deeper how much the translations themselves match, but a cursory check of random sentences suggests they are indeed close.

**Comment by andrewshadura** [comment]
I’d say the fact that two manpages were translated by different people and both contain the fourth clause suggests that it was not intentional but it was the same license as the original manpage at the time.
