### ISSUE TITLE
`libsubid` shouldn't log to `stderr`

### ISSUE THREAD

**Issue by alexey-tikhonov** [shadow-maint/shadow#325]
Currently 'libsubid' can log to `stderr`:
`get_subuid_ranges()` -> `list_owner_ranges()` -> `get_subid_nss_handle()` -> `nss_init()` -> `fprintf(stderr, ...)`

For `new?idmap` this is fine to print to `stderr`, but I think `libsubid` shouldn't.

([reference](https://github.com/shadow-maint/shadow/pull/321#issuecomment-826855274) for a context)

UPD: #329 was merged here

**Comment by hallyn** [comment]
I agree libraries should not do that.

Where do you think the errors should go?  Just /dev/null, if done through libsubid?

**Comment by alexey-tikhonov** [comment]
IMO, ideally `libsubid` API could provide a method to setup user supplied logger function (defaults to /dev/null if not set explicitly).
This could help debugging.
But if that's not feasible at this point, than /dev/null...

**Comment by hallyn** [comment]
Both this and the Prog issue amount to a re-working of the whole logging system - such as it is - in shadow.

I don't like how it currently is, so I'll do something, but it'll take a bit of time.
