### ISSUE TITLE
`libsubid.so` shouldn't require symbol `Prog`

### ISSUE THREAD

**Issue by alexey-tikhonov** [shadow-maint/shadow#329]
```
$ grep Prog lib/prototypes.h 
extern /*@observer@*/ const char *Prog;

$ nm -D /usr/lib64/libsubid.so | grep Prog
                 U Prog
```

This is quite unexpected for applications linking with `libsubid`: `.../lib64/libsubid.so: undefined reference to 'Prog'`

**Comment by hallyn** [comment]
Hm, yes, but that could be painful to undo as it's pretty deeply entrenched.  Will need to think if there's a nice way to handle that.

**Comment by alexey-tikhonov** [comment]
Probably `libsubid` could define this symbol locally (to some stub value like "shadow-utils:libsubid")?

**Comment by hallyn** [comment]
I was also thinking of supporting some sort of subid_init("myprog") call (which later might support other configurations...  but I doubt people would want to add such a call.

The (deeply entrenched) uses of Prog tend to be in the same places as use of stderr, so I think a generally logging infrastructure might be the best answer to both.
