### ISSUE TITLE
Inconsistency: "nsswitch:subid has network source configured" vs "local user manipulation are being done"

### ISSUE THREAD

**Issue by alexey-tikhonov** [shadow-maint/shadow#331]
What is our general approach to a case: "nsswitch:subid has network source configured" and "local user manipulation are being done"?

1) `newusers`: sub_uid_assigned() -> nsswitch::has_any_range(), so if network source is configured in `nsswitch.conf` then `newusers` consults network source for a **local** user instead of /etc/subid, and this doesn't make much sense, imo.
And this is the only use of `has_any_range()` I've found. Do we need this function in a plugin at all if only local user manipulation tools use it?

2) `useradd`: sub_uid_add() -> "if network source is configured" => -EOPNOTSUPP. Again, if network source is configured in `nsswitch.conf` then `useradd` will fail to update /etc/subuid for a **local** user. Is this expected?

3) (somewhat relevant) if we suppose that a given subid can be used by multiple users (uids), then probably usage of has_range() in user_busy.c is wrong (subrange doesn't uniquely identify owner).

**Comment by hallyn** [comment]
1. We can drop has_any_range.  I thought libsubid had that method, but i see
that it does not (or maybe I just removed it).  So maybe newusers.c should do

    bool want_subuids() {
        if (get_subid_nss_handle() != NULL)
            return false;
        if (getdef_ulong ("SUB_UID_COUNT", 65536) == 0)
            return false;
        return true;
    }

    if (is_sub_uid && want_subuids() && !sub_uid_assigned(fields[0])) {
        ...
    }

2. useradd *should* only fail, when network source enabled, if login.defs sets
SUB_UID_COUNT to something other than 0.  If it's set to something other than
0, then it should fail.  If it's not working with that set to 0, then that's
just a bug (which I know there are some of).

By the way, if you feel that there is a safe/sane way to ask the NSS service to
add a subid range, I'm happy to implement it.  I just figured SSSD/LDAP/whoever
wouldn't want to just take the word of a random network client.

3. is an interesting problem, I'm not sure how best to address it. It should be
a rare case, though, and we have the force flag to work around it, so I'm not
sure it's urgent.

**Comment by alexey-tikhonov** [comment]
>        So maybe newusers.c should do
>        bool want_subuids() {
>        if (get_subid_nss_handle() != NULL)
>        return false;
...
>     2. useradd _should_ only fail, when network source enabled, if login.defs sets
>        SUB_UID_COUNT to something other than 0.  If it's set to something other than
>        0, then it should fail.

`I just figured SSSD/LDAP/whoever wouldn't want to just take the word of a random network client.`  --  that's correct.

But: `If it's set to something other than 0, then it should fail.`  --  this is exactly what I question.

On any host we can have users coming from different sources. It's quite usual to have both `local` and `domain` (LDAP backed) users at the same time. For NSS services this is achieved thru support of multiple plugins in /etc/nsswitch.conf - this way `getpwnam()` works transparently for a user from any listed source.

"Delegated sub-id range(s)" is very similar to yet another one NSS-like user attribute, IMO.
Even if we have LDAP users (whose subid ranges are defined in LDAP), ideally that shouldn't change things for local users (whose subid ranges are defined in /etc/subid files).
But to achieve this shadow-utils should support multiple nsswitch.conf plugins, and that's not the case.

So this is where I started: what is a message to users?
Is it: "you can only configure support of subid ranges related functionality for a single source; i.e. if you configure subid ranges support for LDAP users, then anything subid related is disabled for local users"?
If this is a message, then probably your solutions to (1) & (2) are fine, but this should be highlighted somewhere: release notes, man pages, ...

CC: @ikerexxe

**Comment by hallyn** [comment]
> On any host we can have users coming from different sources.

Currently, we are very strictly saying that all subid information comes from either files or nss. Yes, users may be defined anywhere, but the subid delegations come from one place . And the reason for that is that the files and nss are likely to trip over each other in the very limited subid space.

I'm open to expanding on that in the future, but in general it seems unsafe and so for now, first iteration, it's all or nothing.
