### ISSUE TITLE
Allow dots (`.`) in user/group names

### ISSUE THREAD

**Issue by anarchocurious** [shadow-maint/shadow#34]
Is there a technical reason why dots (`.`) are not allowed in user/group names?

And if not, would a PR to allow them be accepted? It seems like a simple enough change to [`is_valid_name` in libmisc/chkname.c](https://github.com/shadow-maint/shadow/blob/e6b23e1431d8d798bb3c620bc26557ea44a30b98/libmisc/chkname.c#L49).

**Comment by hallyn** [comment]
Quoting Alec Larsen (notifications@github.com):
> Is there a technical reason why dots (`.`) are not allowed in user/group names?
> 
> And if not, would a PR to allow them be accepted? It seems like a simple enough change to [`is_valid_name` in libmisc/chkname.c](https://github.com/shadow-maint/shadow/blob/e6b23e1431d8d798bb3c620bc26557ea44a30b98/libmisc/chkname.c#L49).

Hi,

this is the kind of thing which seems to me like it should be perfectly
safe, but for which i suspect there is a strong historical (or even
current) reason why it's refused.  I'm cc:ing the mailing list so
hopefully someone less ignorant than I can answer.

thanks,
-serge

**Comment by anarchocurious** [comment]
@hallyn I agree. Thank you for passing it along. I'm curious what the reason might be.

From my experience, Fedora allows dots by default, Debian can be configured to allow them easily, and manually editing `/etc/{passwd,shadow,group}` works with no visible adverse effects in Arch (aside from `pwck` complaints).

I suspect that this may be something that can be allowed upstream.

**Comment by hallyn** [comment]
Hi,

is_valid_name() is one of the functions that varies depending on the
distributions.

One historical reason for forbidding periods in user/group names is that it
was used by BSD's chown to separate username and groupname.
I could find this reference:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/chown.html

Also any program could have its own regex and reject / accept usernames (I
don't know any standard username regex definition). Although, since much
more relaxed policy have been used for a while (for example on Debian:
https://github.com/Distrotech/shadow-utils/blob/distrotech-shadow-utils/debian/patches/506_relaxed_usernames)
allowing periods should be quite safe.

Best Regards,
-- 
Nekral

2016-09-12 13:48 GMT-07:00 Serge E. Hallyn <serge@hallyn.com>:

> Quoting Alec Larsen (notifications@github.com):
> > Is there a technical reason why dots (`.`) are not allowed in user/group
> names?
> >
> > And if not, would a PR to allow them be accepted? It seems like a simple
> enough change to [`is_valid_name` in libmisc/chkname.c](https://
> github.com/shadow-maint/shadow/blob/e6b23e1431d8d798bb3c620bc26557
> ea44a30b98/libmisc/chkname.c#L49).
>
> Hi,
>
> this is the kind of thing which seems to me like it should be perfectly
> safe, but for which i suspect there is a strong historical (or even
> current) reason why it's refused.  I'm cc:ing the mailing list so
> hopefully someone less ignorant than I can answer.
>
> thanks,
> -serge
>
> _______________________________________________
> Pkg-shadow-devel mailing list
> Pkg-shadow-devel@lists.alioth.debian.org
> http://lists.alioth.debian.org/cgi-bin/mailman/listinfo/pkg-shadow-devel
>

**Comment by vapier** [comment]
not just BSD -- that's a link to POSIX, and GNU chown supports it as well:
https://www.gnu.org/software/coreutils/manual/html_node/chown-invocation.html

although it recommends against using the syntax since user/group names can have a dot.

Gentoo has patched in support for dots for over 11 years.  RedHat/Fedora has done it for almost 12 years.

**Comment by hallyn** [comment]
On Mon, Sep 12, 2016 at 05:12:43PM -0700, Nicolas François wrote:
> Hi,
> 
> is_valid_name() is one of the functions that varies depending on the
> distributions.
> 
> One historical reason for forbidding periods in user/group names is that it
> was used by BSD's chown to separate username and groupname.
> I could find this reference:
> http://pubs.opengroup.org/onlinepubs/9699919799/utilities/chown.html
> 
> Also any program could have its own regex and reject / accept usernames (I
> don't know any standard username regex definition). Although, since much
> more relaxed policy have been used for a while (for example on Debian:
> https://github.com/Distrotech/shadow-utils/blob/distrotech-shadow-utils/debian/patches/506_relaxed_usernames)
> allowing periods should be quite safe.
> 
> Best Regards,
> -- 
> Nekral

Thanks!  So it sounds like a patch which allows '.' but adds a
configure option to enable that would be the way to go.

thanks,
-serge

**Comment by anarchocurious** [comment]
Thank you for the prompt responses.

@hallyn Please forgive my ignorance, but when you say a "configuration option" do you mean a value that is runtime configurable (perhaps in [`etc/login.defs`](https://github.com/shadow-maint/shadow/blob/6fbc11ce2178205968c37853db752729359c9893/etc/login.defs)) or some sort of compile time option?

**Comment by vapier** [comment]
we could make the entire function into a login.defs option.  make it a regex and then just run against it.  the default would be `^[a-z_][a-z0-9_-]*$`.  anyone who wants to change it can add the dots however they like.

have to be careful to run the regex with `LC_CTYPE` set to `C` (or `C.UTF8` if it's available).

**Comment by hallyn** [comment]
Hi Serge,

Even with such patch, I assume that there will still be the need for a
Debian patch, and another one on fedora, ...
That's what does not make me so confortable here.

-- 
Nekral

2016-09-13 6:36 GMT-07:00 Serge E. Hallyn <serge@hallyn.com>:

> On Mon, Sep 12, 2016 at 05:12:43PM -0700, Nicolas François wrote:
> > Hi,
> >
> > is_valid_name() is one of the functions that varies depending on the
> > distributions.
> >
> > One historical reason for forbidding periods in user/group names is that
> it
> > was used by BSD's chown to separate username and groupname.
> > I could find this reference:
> > http://pubs.opengroup.org/onlinepubs/9699919799/utilities/chown.html
> >
> > Also any program could have its own regex and reject / accept usernames
> (I
> > don't know any standard username regex definition). Although, since much
> > more relaxed policy have been used for a while (for example on Debian:
> > https://github.com/Distrotech/shadow-utils/blob/distrotech-
> shadow-utils/debian/patches/506_relaxed_usernames)
> > allowing periods should be quite safe.
> >
> > Best Regards,
> > --
> > Nekral
>
> Thanks!  So it sounds like a patch which allows '.' but adds a
> configure option to enable that would be the way to go.
>
> thanks,
> -serge
>

**Comment by hallyn** [comment]
Hm, if we support enabling it through configure that won't suffice?
Do fedora and debian not support it quite the same way?

**Comment by hallyn** [comment]
On St, 2016-09-14 at 22:54 -0500, Serge E. Hallyn wrote:
> Hm, if we support enabling it through configure that won't suffice?
> Do fedora and debian not support it quite the same way?

The Debian patch severally relaxes the rules - it just disallows some
particular characters.

On the other hand Fedora uses the same approach as the shadow upstream
but allows a little bit more - the '.', and uppercase letters.

We recently got a request to disable the "." and ".." usernames.

-- 
Tomas Mraz
No matter how far down the wrong road you've gone, turn back.
                                              Turkish proverb
(You'll never know whether the road is wrong though.)

**Comment by hallyn** [comment]
On Tue, Sep 13, 2016 at 08:45:43AM -0700, Alec Larsen wrote:
> Thank you for the prompt responses.
> 
> @hallyn Please forgive my ignorance, but when you say a "configuration option" do you mean a value that is runtime configurable (perhaps in [`etc/login.defs`](https://github.com/shadow-maint/shadow/blob/6fbc11ce2178205968c37853db752729359c9893/etc/login.defs)) or some sort of compile time option?

I meant compile-time, but maybe login.defs makes more sense for this.

**Comment by hallyn** [comment]
If a patch is submitted which makes thie (default-off) configurable, I'll consider it, but for now I'm going to close this issue.
