### ISSUE TITLE
libsubid.so shouldn't require symbol `shadow_logfd`

### ISSUE THREAD

**Issue by alexey-tikhonov** [shadow-maint/shadow#346]
This is similar to #329:

```
libsubid/api.c:43:extern FILE * shadow_logfd;

$ nm -D /usr/lib64/libsubid.so | grep shadow_logfd
                 U shadow_logfd

lib64/libsubid.so: undefined reference to `shadow_logfd'
```

I guess `shadow_logfd` should not be `extern` in `libsubid/api.c`..?

Another very minor note not worth dedicated ticket: I think `subid.h` should ‘#include <stdio.h>’ due to 'FILE' used in API.

**Comment by hallyn** [comment]
Indeed that shouldn't be extern, thanks.
