### ISSUE TITLE
login.defs: PASS_MIN_DAYS value to disable is inconsistent

### ISSUE THREAD

**Issue by tzccinct** [shadow-maint/shadow#349]
https://github.com/shadow-maint/shadow/blob/087112244327be50abc24f9ec8afbf60ae8b2dec/etc/login.defs#L218

https://github.com/shadow-maint/shadow/blob/087112244327be50abc24f9ec8afbf60ae8b2dec/man/login.defs.d/PASS_MIN_DAYS.xml#L32-L39

Which is 0 or -1 official value to disable `PASS_MIN_DAY`? Are both OK? To be consistent, we might want to update the man page and/or default login.defs.

**Comment by hallyn** [comment]
Well looking at lib/shadow.c, effectively anything <= 0 is ok, but it looks like there is a case where it matters for nis.  In that case if sp_min is 0 it sets it to -1, then still returns 0.

So yes, one more sentence to say that both 0 and -1 mean no minimum perios between password changes would be ok.  Do you want to submit that patch?

**Comment by tzccinct** [comment]
I want the value to be standardized one, ideally 0 because chage command uses 0 to disable MIN_DAYS. According to `man chage`:

> -m, --mindays MIN_DAYS
>            Set the minimum number of days between password changes to MIN_DAYS. A value of zero for this field indicates that the user may change their password at any time.

But if there is a case where the value 0 is not good for nis, I give it up. Thank you for your investigation.

**Comment by hallyn** [comment]
But the code will take care of 0 vs -1 for you, so we could standardize on simply saying 0 for disabled, and not mention -1 anywhere.

**Comment by tzccinct** [comment]
@hallyn If I understand correctly, it is OK to simply update shadow/man/login.defs.d/PASS_MIN_DAYS.xml to say 0 for disabled. I'll try to submit the patch.

**Comment by hallyn** [comment]
Right.  Thanks.
