### ISSUE TITLE
Missing 4.2.1 tag

### ISSUE THREAD

**Issue by samuelson** [shadow-maint/shadow#35]
The 4.2 tags are missing on the repo, which makes it hard to compile an rpm.

It looks to me like it should point to 8b4e03b99440f35550118f0d102b3ffc1622586f

**Comment by hallyn** [comment]
Hi,

that commit doesn't show up in my git tree.

Looking at the Changelog in the 4.2 release tarball, it seems to me
that

commit 5e87ff0615bbd8de2b709eb3d53d12dfaedb4dbc
Author: Nicolas François <nicolas.francois@centraliens.net>
Date:   Sun Aug 25 16:27:58 2013 +0200

    Improve vipw error report when editor fails

        * src/vipw.c: After waitpid(), use errno only if waitpid returned
        -1. Debian#688260
        * src/vipw.c: Likewise for system().

would be a good candidate.  Do you agree?

**Comment by jubalh** [comment]
I also missed this tag and said so on the mailing list severl months ago.
It would be very nice if it could be added, and I am actually curious why it wasn't initially.

**Comment by jschleus** [comment]
The according contents page on the server fossies.org

  https://fossies.org/linux/misc/shadow-4.4.tar.gz/

has a link to a "Diffs report" against 4.2.1 

  https://fossies.org/diffs/shadow/4.2.1_vs_4.4/

that may help a little bit.

By the way there is also a link to  the (experimental) Doxygen generated source code documentation

 https://fossies.org/dox/shadow-4.4/

Sorry, if this a little bit house advertising but I am "accidentally" also the maintainer of the  mentioned site.

**Comment by hallyn** [comment]
Pushed a 4.2.1 tag.

**Comment by samuelson** [comment]
@hallyn sorry I didn't see your reply back in Sept, thanks for resolving it.
