### ISSUE TITLE
ChangeLog

### ISSUE THREAD

**Issue by jubalh** [shadow-maint/shadow#37]
Is there a reason why the ChangeLog file is not updated anymore?

Some projects started to not use their ChangeLog anymore when they switched to GitHub. They just wrote the Changelog in the description of the GitHub release. However when the description contains `tag 4.4` only this isn't very helpful.
Some projects propose to look at `git log`.
Of course one could do that but:
- Sometimtes there are fixup commits so actually several commits give one new functionality, so one cant automate generating the ChangeLog from `git log`
- If upstream does it all distributions can use it instead of each distribution writing their own ChangeLog

Generally I had the impression that http://pkg-shadow.alioth.debian.org/ was the upstream website of shadow., and also being the Debian site about it.
As [get involved](http://pkg-shadow.alioth.debian.org/getinvolved.php) states:

```
The pkg-shadow project on Alioth is used for upstream maintenance of shadow and for the maintenance of the Debian shadow package.
```

Thus I would have thought that the news is up to date regarding the upstream version of things and not the debian specific things. Meaning `2014-05-09 - New release: 4.2.1` is the last one on the website but on GitHub there are 4.3.0, 4.3.1 and 4.4.

So the website sais 4.2.1 is the latest, and funny enough this on is not even tagged in git, so in this case its very hard to go to `git log` and just see what was added since last tag. So in this case it would even be more a reason to have a ChangeLog provided by upstream.

I tried to adress this partly in an [email](http://lists.alioth.debian.org/pipermail/pkg-shadow-devel/2016-July/011024.html).

**Comment by hallyn** [comment]
On Fri, Sep 23, 2016 at 02:23:36AM -0700, Michael Vetter wrote:
> Is there a reason why the ChangeLog file is not updated anymore?
> 
> Some projects started to not use their ChangeLog anymore when they switched to GitHub.

Yeah I haven't been, but it's probably worth doing.

>  They just wrote the Changelog in the description of the GitHub release. However when the description contains `tag 4.4` only this isn't very helpful.

Yeah to me the tag has always just been the tag, I never even thought of using
that commit msg for anything (have always been kind of annoyed at having to
add one)

> Some projects propose to look at `git log`.
> Of course one could do that but:
> * Sometimtes there are fixup commits so actually several commits give one new functionality, so one cant automate generating the ChangeLog from `git log`
> * If upstream does it all distributions can use it instead of each distribution writing their own ChangeLog
> 
> Generally I had the impression that http://pkg-shadow.alioth.debian.org/ was the upstream website of shadow. Hosted on alioth but still being upstream. Thus I would have thought that the news is up to date regarding the upstream version of things and not the debian specific things. Meaning `2014-05-09 - New release: 4.2.1` is the last one on the website but on GitHub there are 4.3.0, 4.3.1 and 4.4.

That's because I don't know how to update most of that.  I *think* I have
the permissions needed to do so, but I haven't had time to look into how,
and actually making a proper updated release has to take priority.  Hoping
this weekend - waiting on a few patch contributions.

> So the website sais 4.2.1 is the latest, and funny enough this on is not even tagged in git, so in this case its very hard to go to `git log` and just see what was added since last tag. So in this case it would even be more a reason to have a ChangeLog provided by upstream.

4.2.1 was a bit of an odd release.  It never made its way into debian;  the
upstream release tarball has some extra gorp in it that has complicated
making a release.  And there are several commits which look like they
could be considered the release.  So yes I don't even know which commit to tag.

**Comment by jubalh** [comment]
> On Fri, Sep 23, 2016 at 02:23:36AM -0700, Michael Vetter wrote:
>  Is there a reason why the ChangeLog file is not updated anymore?
>  Some projects started to not use their ChangeLog anymore when they switched to GitHub.
> Yeah I haven't been, but it's probably worth doing.

Thanks! I suppose this would also make it more easy for yourself when writing the Debian ChangeLog.


> That's because I don't know how to update most of that. I *think* I have the permissions needed to do so, but I haven't had time to look into how, and actually making a proper updated release has to take priority. Hoping this weekend - waiting on a few patch contributions.

So all the releases from 4.1.5 on weren't good?
How should users of shadow find this out? :-) Fedora for example uses 4.3.1 as it seems. For this reason I think it would be good if the website would be up to date. So in case releases that arent actually meant to be releases but are on GitHub still can get ignored and users can rely on the news of the website.

**Comment by hallyn** [comment]
On Fri, Sep 23, 2016 at 10:54:17AM -0700, Michael Vetter wrote:
> > On Fri, Sep 23, 2016 at 02:23:36AM -0700, Michael Vetter wrote:
> >  Is there a reason why the ChangeLog file is not updated anymore?
> >  Some projects started to not use their ChangeLog anymore when they switched to GitHub.
> > Yeah I haven't been, but it's probably worth doing.
> 
> Thanks! I suppose this would also make it more easy for yourself when writing the Debian ChangeLog.
> 
> 
> > That's because I don't know how to update most of that. I *think* I have the permissions needed to do so, but I haven't had time to look into how, and actually making a proper updated release has to take priority. Hoping this weekend - waiting on a few patch contributions.
> 
> So all the releases from 4.1.5 on weren't good?

No, the upstream git tree is fine.

> How should users of shadow find this out? :-) Fedora for example uses 4.3.1 as it seems. For this reason I think it would be good if the website would be up to date. So in case releases that arent actually meant to be releases but are on GitHub still can get ignored and users can rely on the news of the website.

Sure - we need someone who can update the website then :)

Ok, so I suppose I've been *privately* trying to get help with the
packaging but haven't done an official wnpp (because it didn't seem
like my place to do so until now).  But as private isn't working, I
guess I should go to wnpp.

-serge
