### ISSUE TITLE
UIDs below `1000` don't get an entry in `/etc/subuid`

### ISSUE THREAD

**Issue by tobwen** [shadow-maint/shadow#379]
## What am I trying to do?
I'm trying to add a UID below `1000` and get an entry in `/etc/subuid`.

## What happens?
The user gets created, but there's no entry in `/etc/subuid`.

## What OS?
Debian Bullseye

## How to reproduce?
```
root@debian:~# cat /etc/subuid
tobwen:100000:65536
```

```
root@debian:~# adduser --system systemuser
Adding system user `systemuser' (UID 106) ...
Adding new user `systemuser' (UID 106) with group `nogroup' ...
Creating home directory `/home/systemuser' ...

root@debian:~# cat /etc/subuid
tobwen:100000:65536
```

```
root@debian:~# adduser --uid 666 --disabled-password systemuser
Adding user `systemuser' ...
Adding new group `systemuser' (666) ...
Adding new user `systemuser' (666) with group `systemuser' ...
Creating home directory `/home/systemuser' ...
Copying files from `/etc/skel' ...
Changing the user information for systemuser
Enter the new value, or press ENTER for the default
        Full Name []:
        Room Number []:
        Work Phone []:
        Home Phone []:
        Other []:
Is the information correct? [Y/n]

root@debian:~# cat /etc/subuid
tobwen:100000:65536
```

**Comment by hallyn** [comment]
We can discuss command line API to make this a one step action, but this is by design, not a bug.  If you want that system user to have subuids, you can just add them:


```
usermod -v 100000-200000 -w 100000-200000 systemuser
```

**Comment by GerardoGR** [comment]
Hey @hallyn sorry for necrobumbing this issue, but I've had a hard time to find an explanation as to why is that the system users do not get subuid and subgid. Could you explain or point to the docs where it explains why system users do not get subuids and subgids automatically with the adduser/useradd command?

**Comment by hallyn** [comment]
> Hey @hallyn sorry for necrobumbing this issue, but I've had a hard time to find an explanation as to why is that the system users do not get subuid and subgid. Could you explain or point to the docs where it explains why system users do not get subuids and subgids automatically with the adduser/useradd command?

I think it was just because most system users - like ntp, sudo, daemon, lp, man, games, etc, do not need it.

If you find you need one, I suspect that will by far be the exception, in which case you can always add a subid range using usermod.

**Comment by hallyn** [comment]
(I say "I think" because I don't believe I was involved in that decision, but it makes sense to me)
