### ISSUE TITLE
Incompatible chmod -f option

### ISSUE THREAD

**Issue by selkfoster** [shadow-maint/shadow#39]
Hello,

The option -f is used in chmod(1) on the files src/Makefile.am and src/Makefile.in.  This is incompatible with the implementation of chmod provided by Busybox.  The build will fail.

**Comment by hallyn** [comment]
Looks like this was added in 2007.  Probably not a big problem
to drop it.

Quoting selkfoster (notifications@github.com):

**Comment by vapier** [comment]
it's not in POSIX, so prob best to drop it

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/chmod.html

**Comment by selkfoster** [comment]
Exactly, it's not POSIX. It works fine without -f.

**Comment by hallyn** [comment]
A PR would be welcome, thanks.

**Comment by selkfoster** [comment]
Hi Serge.  Sorry but, What do you mean by "PR"?

**Comment by selkfoster** [comment]
PR = Pull request? Which branch I must choose to create a pull request? (Sorry I'm new in github)

**Comment by vapier** [comment]
a pull request.  fork this github (GH) repo, make the change, push the branch to your fork in GH, and then send a pull request (PR) to this one for Serge to click "merge" on.

**Comment by jubalh** [comment]
@selkfoster Maybe reading some GitHub documentation :)
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/creating-a-pull-request/

**Comment by hallyn** [comment]
On Mon, Oct 17, 2016 at 11:53:44AM -0700, Matias A. Fonzo wrote:
> PR = Pull request? Which branch I must choose to create a pull request? (Sorry I'm new in github)

Yeah, exactly - thanks!

**Comment by selkfoster** [comment]
Ehm.. Thanks to all, but for some reason I can't click on "Create pull request", maybe is my browser or a Java thing, I need permissions from the upstream side?, I have the change here: https://github.com/selkfoster/shadow/commit/b7fffe8f7e13c9ad83d5380b5f742cb4776ee58b

**Comment by vapier** [comment]
github doesn't use Java anywhere, so not sure why that'd matter

you start a request from the downstream repo, not from the upstream one.  i.e. this page: https://github.com/selkfoster/shadow

**Comment by selkfoster** [comment]
Finally, it was my old web browser (Icecat 10). I've used Seamonkey this time.  Thanks Mike.
