### ISSUE TITLE
`userdel -f` can pose a security threat

### ISSUE THREAD

**Issue by bubakazouba** [shadow-maint/shadow#404]
## Ubuntu Distro
`root@dopeDroplet:~# lsb_release -a`
```
No LSB modules are available.
Distributor ID:  Ubuntu
Description:  Ubuntu 14.04.6 LTS
Release:  14.04
Codename:  trusty
```

## Security Threat
1. System Admin creates group `G`.
2. System Admin creates `userB` and `userE` under the same group `G`.
3. `userE` creates a process `P` which is a backdoor that receives commands and runs it using `nohup &`.
4. System Admin deletes `userE` using `userdel -f`.
5. Linux would delete `userE` but keep the process `P` running with user id of the group `G`.
5. System Admin later inspects group `G` and only finds `userB` in it, then decides to repurpose group `G` and gives it more permissions.
6. Deleted `userE` has a backdoor to the computer.

### Real use case
1. Schools creates users for students that have CS classes, then deletes these users automatically (potentially with `userdel -f`) when they leave the school.
2. Company has a shared server, employee leaves and still has access to company's server.

### Patch suggestion
* `userdel -f` should kill all processes for user

## Setup user
`root@dopeDroplet:~# useradd sahmoud`
`root@dopeDroplet:~# passwd sahmoud`
`root@dopeDroplet:~# su sahmoud`

## Setup script
`sahmoud@dopeDroplet:/$ vim /tmp/sahmoud.sh`
```
while [ true ]
do
  echo `whoami` `id -g` `date` >> /tmp/sahmoudoutput
  sleep 30
done
```

`sahmoud@dopeDroplet:/$ chmod 777 sahmoud.sh`
`sahmoud@dopeDroplet:/$ nohup ./sahmoud.sh &`
## Test script
wait a few minutes
`sahmoud@dopeDroplet:/$ cat /tmp/sahmoudoutput`
```
sahmoud 1004 Tue Aug 17 00:51:07 EDT 2021
sahmoud 1004 Tue Aug 17 00:51:38 EDT 2021
sahmoud 1004 Tue Aug 17 00:52:08 EDT 2021
sahmoud 1004 Tue Aug 17 00:52:38 EDT 2021
sahmoud 1004 Tue Aug 17 00:53:08 EDT 2021
```

## Check PID
`sahmoud@dopeDroplet:/$ ps -aux | grep sahmoud.sh`
```
sahmoud   5789  0.0  0.0   4448   672 pts/1    S    00:51   0:00 /bin/sh ./sahmoud.sh
sahmoud      6287  0.0  0.0  11752   924 pts/1    S+   00:53   0:00 grep sahmoud.sh
```

## Delete user
Exit as user `sahmoud`: `exit`
`root@dopeDroplet:~# userdel sahmoud`
```
userdel: user sahmoud is currently used by process 5789
```

`root@dopeDroplet:~# userdel -f sahmoud`
```
userdel: user sahmoud is currently used by process 5789
```

`root@dopeDroplet:~# userdel -f sahmoud`
```
userdel: user 'sahmoud' does not exist
```

`root@dopeDroplet:~# cat /tmp/sahmoudoutput`
```
sahmoud 1004 Tue Aug 17 00:51:07 EDT 2021
sahmoud 1004 Tue Aug 17 00:51:38 EDT 2021
sahmoud 1004 Tue Aug 17 00:52:08 EDT 2021
sahmoud 1004 Tue Aug 17 00:52:38 EDT 2021
sahmoud 1004 Tue Aug 17 00:53:08 EDT 2021
sahmoud 1004 Tue Aug 17 00:53:38 EDT 2021
sahmoud 1004 Tue Aug 17 00:54:08 EDT 2021
sahmoud 1004 Tue Aug 17 00:54:38 EDT 2021
sahmoud 1004 Tue Aug 17 00:55:08 EDT 2021
 1004 Tue Aug 17 00:55:38 EDT 2021
 1004 Tue Aug 17 00:56:08 EDT 2021
```

`root@dopeDroplet:~# ps -aux | grep sahmoud.sh`
```
1004      5789  0.0  0.0   4448   676 pts/1    S    00:51   0:00 /bin/sh ./sahmoud.sh
buba      7792  0.0  0.0  11752   924 pts/1    S+   01:01   0:00 grep sahmoud.sh
```

**Comment by hallyn** [comment]
Perhaps we should instead add a -k option to kill the user's processes, to avoid changing behavior that someone is relying upon.

**Comment by edneville** [comment]
I wondered about proposing a PR for this, but this feels like it would be a good case for a userdel-pre.d script.
