### ISSUE TITLE
configure.ac: mismatched parentheses

### ISSUE THREAD

**Issue by dilyanpalauzov** [shadow-maint/shadow#419]
The line https://github.com/shadow-maint/shadow/blob/master/configure.ac#L348:
 
> AS_IF([test "$with_su" != "no"], AC_DEFINE(WITH_SU, 1, [Build with su])])

has an unmatched `]`.

This is upstream and in version 4.9.

**Comment by vapier** [comment]
want to send a PR for it ?  should have a `[` at the start of the 2nd arg.

fwiw, usually `[` and `]` are referred to as "square brackets" to differentiate from `(` and `)` parentheses.  especially since that line has both ;).

**Comment by dilyanpalauzov** [comment]
I don’t want to send anything.
