### ISSUE TITLE
Su error message is misleading

### ISSUE THREAD

**Issue by michaelpulis** [shadow-maint/shadow#427]
If you are running a terminal without root access, and you try to use the `su` command, using it will return the following error _(after it prompts you to type in your password)_: `su: Authentication failure`

This is misleading, as you might have written the correct password and you will still receive this message. Running `sudo su` in this case solves the issue as the terminal is then running with elevated permissions, and `su` will function normally again.

Should the error message be fixed to tell the user what the actual issue is?

**Comment by hallyn** [comment]
There are countless reasons why it might fail.  It looks to e as if su.c only reports an Authentication failure if pw_auth fails, which truly means an authentication error.

You say you run 'su' and typed in "your" password.  Did you type in the user password or the root password?

**Comment by jubalh** [comment]
I don't see a mistake in the code. And since @michaelpulis didn't reply I assume this issue can be closed.
