### ISSUE TITLE
actions are misbehaving in run: section

### ISSUE THREAD

**Issue by hallyn** [shadow-maint/shadow#431]
It appears that when forking a child from within a run: section in github actions, all open fds are closed.  This is breaking expect scripts, of course.  I tested it here  https://github.com/hallyn/shadow/actions/runs/1384173863   by doing

```
echo "in a child:
bash -c 'set -ex; ls -l /proc/self/fd' || true
echo "END OF in a child:
```
@vapier do you have any idea what's causing this?

**Comment by hallyn** [comment]
Ok, thanks - I guess I'll try open-coding run_some

**Comment by hallyn** [comment]
Just open-coding run_some doesn't appear to be sufficient.

I'm tempted to move shadow to sr.ht.

**Comment by jubalh** [comment]
I'm not aware that we currently still have problems with CI. @hallyn I guess this can be closed?
