### ISSUE TITLE
Request: move `list_subid_ranges` from `noinst_PROGRAMS` to regular `ubin_PROGRAMS`

### ISSUE THREAD

**Issue by AkihiroSuda** [shadow-maint/shadow#438]
Currently the [`list_subid_ranges`](https://github.com/shadow-maint/shadow/blob/v4.9/src/list_subid_ranges.c) program is not installed to `/usr/bin`, as it belongs to `noinst_PROGRAMS` in `Makefile.am`:  https://github.com/shadow-maint/shadow/blob/387da46d73524c9fea48f5a949eb5220d40440e6/src/Makefile.am#L161-L165

Would it be possible to move  `list_subid_ranges` from `noinst_PROGRAMS` to regular `ubin_PROGRAMS`?

My motivation is to get the list of available subids without depending on libsubid / libnss.
Especially I'd like to exec the command from [RootlessKit](https://github.com/rootless-containers/rootlesskit) without relying on any C library.

Installing  `list_subid_ranges` to `/usr/bin` will be helpful for sysadmins, too.

**Comment by jubalh** [comment]
Did you see https://github.com/shadow-maint/shadow/pull/436 ?

**Comment by AkihiroSuda** [comment]
Ah, nice, didn't notice the PR! 😅
