### ISSUE TITLE
Building issues with 4.9 around libsubid

### ISSUE THREAD

**Issue by gzpapp** [shadow-maint/shadow#448]
Trying to build 4.9 release with --disable-subordinate-ids --with-nscd=no --with-sssd=no
If building outside of source directory, getting the following error:

In file included from ../../libmisc/addgrps.c:37:
../../lib/prototypes.h:267:10: fatal error: libsubid/subid.h: No such file or directory
 #include <libsubid/subid.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:565: addgrps.lo] Error 1

If I fix the problem manually, correcting the include path of libsubid/subid.h file, getting the next error:

../../lib/run_part.c:10:10: fatal error: lib/prototypes.h: No such file or directory
 #include <lib/prototypes.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:687: libshadow_la-run_part.lo] Error 1

4.8.1 compiled fine outside of source tree.

**Comment by hallyn** [comment]
Can you try from the latest git?  There were some fixes after the 4.9 release.

If that fixes it for you, then I'll do a 4.10 release to get that out there.

**Comment by gzpapp** [comment]
Yes, seems like current git (dce030ffb8ebb40f7c3ff5b634669e0c41308773) configures and compiles fine. The above problems are fixed.

**Comment by hallyn** [comment]
Great, thanks for checking.
