### ISSUE TITLE
Simplify usermod.c

### ISSUE THREAD

**Issue by alejandro-colomar** [shadow-maint/shadow#454]
In parsing the argument to the `--expiredate` option, there's a special case for `""`: <https://github.com/shadow-maint/shadow/blob/7687ae4dbd995f4042e375f750c75953568a2444/src/usermod.c#L1076>

```
			case 'e':
				if ('\0' != *optarg) {
					user_newexpire = strtoday (optarg);
					if (user_newexpire < -1) {
						fprintf (stderr,
						         _("%s: invalid date '%s'\n"),
						         Prog, optarg);
						exit (E_BAD_ARG);
					}
					user_newexpire *= DAY / SCALE;
				} else {
					user_newexpire = -1;
				}
				eflg = true;
				break;
```

However, (the new version of) `strtoday()` already handles that special case: <https://github.com/shadow-maint/shadow/blob/7687ae4dbd995f4042e375f750c75953568a2444/libmisc/strtoday.c#L77>

```
	if ((NULL == str) || ('\0' == *str)) {
		return -1;
	}

	...
```

So the calling code could be simplified to the following:

```
			case 'e':
				user_newexpire = strtoday (optarg);
				if (user_newexpire < -1) {
					fprintf (stderr,
					         _("%s: invalid date '%s'\n"),
					         Prog, optarg);
					exit (E_BAD_ARG);
				}
				user_newexpire *= DAY / SCALE;
				eflg = true;
				break;
```

---

There are 2 versions of `strtoday()` (actually 3), and at first I thought that the old ones might not handle correctly the special case.  However, I found what could be a bug, which I think would handle `""` correctly by accident.  Instead of returning -2 on error, the old functions return -1, and since they don't handle `""` specially, they will report an error.  Since `-1` is handled not as an error but as a 'never' by the calling code, it would work.

I'll send a pull request soon and link to this issue.

**Comment by ikerexxe** [comment]
As the PR was merged I guess you could close this issue. Am I right?

**Comment by alejandro-colomar** [comment]
Ahh, I forgot.  Sure
