### ISSUE TITLE
Please check manual page login.1.xml / login.defs.5.xml

### ISSUE THREAD

**Issue by mlh85386** [shadow-maint/shadow#457]
Hello,
I am about to update the German message catalogue for the manual pages and doubt whether this string is correct:

#: login.defs.5.xml:40(para) login.1.xml:40(para)
msgid "By default, the ownership of the terminal is set to the user's primary group "
"and the permissions are set to 0600."

Assume passwd contains a user name user1 which has primary group group1
As a understand the explanation above, after a login on tty1, the device tty1 would appear in the list of devices as such
-rw- --- --- group1 somegroup /dev/tty1
I would expect
-rw- --- --- user1 somegroup /dev/tty1

Consider that there are more group-IDs than user-IDs. Therefore, a group-IDs in a place where a user-ID is expected leads to a situation where the owner of the terminal is not known

Best regards
Markus

**Comment by hallyn** [comment]
Good point, this is not clear.  What it is trying to say is that if TTYGROUP is not defined, THEN the tty will be group-owned by the user's primary group.  Otherwise it will be group-owned by TTYGROUP.

This should be clarified.

**Comment by mlh85386** [comment]
Hi Serge
Do you want me to improve the explanation on the two variables? I think, now I would be able to provide it to this platform github. A technical problem with my browser has been solved recently.
Markus

**Comment by hallyn** [comment]
I had it on my list to do, but please feel free.

**Comment by mlh85386** [comment]
Hi Serge
I edited TTYGROUP.xml and try to attach this file to this post.
... 
No success to attach this xml file by selecting it. Probably due to restrictions for the file format. I' going to try a pull request.

Remarks on the file content: The text was modified as I suppose it makes sense. Probably I'm wrong. Your feedback would be appreciated. My guideline was:
a) purpose of the two variables b) hints on their usage c) default behavior d) hints on a reasonable setting.
Best regards
Markus

**Comment by mlh85386** [comment]
Hi Serge,

Serge Hallyn schrieb am  2. Februar 2023 um 00:24

> I had it on my list to do, but please feel free.

I failed to attach the edited file to issue thread #457 and I do not
know how to make a pull request / to upload a patch.

Therefore attached to this mail the edited file and a simple diff
file. See the remarks in the latest issue post.

Best regards
Markus

**Comment by hallyn** [comment]
Sorry @mlh85386  I don't see any patch by you, but I created a PR with my proposal.  I'll merge that in a bit.

I gather, based on your experience, that *you* would be perfectly happy with shadow moving to sr.ht where we could have purely email based flow for those who want it? :)

**Comment by mlh85386** [comment]
Hi Serge,

Serge Hallyn schrieb am  2. Februar 2023 um 19:36

> Sorry @mlh85386 I don't see any patch by you,

uploading a file in the issue #457 thread failed. But the file
TTYGROUP.xml and a diff file were attached to the previous mail. A CC
mail on my computer proves it. Probably github suppresses attachments.


> but I created a PR with my proposal. I'll merge that in a bit.

Although you will not need my files, I uploaded them to my web space

  https://hiereth.de/tmp/TTYGROUP.xml
  https://hiereth.de/tmp/TTYGROUP.xml.diff


> I gather, based on your experience, that you would be perfectly
> happy with shadow moving to sr.ht where we could have purely email
> based flow for those who want it? :)

In fact. But, a year ago, I assumed that the email correspondence was
more intense than you wished.

The proof reading of the German po file for the manual pages comes to
an end within the next days. I'll pass it in an Debian bug report. I
would not be astonished whether the result of applying po-translate
needs to be checked thoroughly (which I would do.)

I considered to introduce the changes and corrections to flaws or
mistakes fount afterwards into the xml files.

I just had a look on sr.ht. I would give it a try as soon as your
project has migrated.

Best regards
Markus
