### ISSUE TITLE
can't get unique subordinate uid range

### ISSUE THREAD

**Issue by stoforest** [shadow-maint/shadow#459]
The default value of SUB_UID_MAX and SUB_GID_MAX is 600100000. With this limit  when creating a user I get an error "can't get unique subordinate uid range".I have more than 9000 users.
It is possible to raise this limit and is there maximum?

**Comment by hallyn** [comment]
You can change the values by setting them in login.defs.  If I understand your question right, the absolute max should be 4294967295 .
