### ISSUE TITLE
Sign release tags

### ISSUE THREAD

**Issue by AdamMajer** [shadow-maint/shadow#46]
Could you please sign GPG release tags and/or tarballs? And ideally, also list the fingerprints of the authorized signing GPG key(s) in the README?

Thank you.
Adam

**Comment by hallyn** [comment]
We really should do that.

**Comment by hallyn** [comment]
Ok I've signed the upstream/4.4 tag.  I did not put the gpg key in the readme, but it is the gpg key listed for me on launchpad.net.  I don't *mind* putting the fingerprint there if you think it's worthwhile.

I'm not sure yet what the deal will be with tarballs.  I think a signed tag plus 'git-archive' should give you what I need (that's what I just used to create a new debian source tarball).

**Comment by AdamMajer** [comment]
Thank you!

Signing tarballs would be great too, as then those checks can be automated in Debian's watch file. With OBS, tarball checks with known project keyring are then also automated. But at least with signed tags, a manual verification is then possible too.
