### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jirutka** [shadow-maint/shadow#462]
Can you please release a new version?

The latest release (4.9) is quite buggy (look how many patches Fedora had to backport [here](https://src.fedoraproject.org/rpms/shadow-utils/blob/rawhide/f/shadow-utils.spec#_19)) and doesn’t even build on musl.

**Comment by hallyn** [comment]
I was hoping to wait until https://github.com/shadow-maint/shadow/pull/451 was merged.  Which, since @jfhaugh had said she would review, I feel I should not merge yet.  But maybe I'll go ahead and release now anyway.

**Comment by jirutka** [comment]
#451 is just about clarification of the licensing, it doesn’t change API or any CLI, so I think it can be in a subsequent patch release.

**Comment by hallyn** [comment]
Yes it's just that the licensing would've simplified new debian packaging.  But I've gone ahead and released 4.10.

**Comment by jirutka** [comment]
Thanks! :+1:
