### ISSUE TITLE
A comment in pwck incorrectly describes a check

### ISSUE THREAD

**Issue by ofurkusi** [shadow-maint/shadow#484]
The following comment in the source for `pwck` is missing a "not". It should read:
```
If uid is not system and has a home directory, then check
```
https://github.com/shadow-maint/shadow/blob/6761cf2d7e9defeed7f915c668a87b84bac2c9c3/src/pwck.c#L524

**Comment by hallyn** [comment]
Actually I think that code is wrong, and could lead to null deref.  (Luckily it's not setuid-root).

Indeed the intent of the author of that commit was to "only check home dirs if set and not a system user".  But that's not what this does.

**Comment by hallyn** [comment]
@edneville Do you want to submit a patch to fix that (c4e8b41: pwck.c: only check home dirs if set and not a system user) or do you prefer I do it?
