### ISSUE TITLE
message is unclear

### ISSUE THREAD

**Issue by crayxt** [shadow-maint/shadow#49]
Hello,

In kk.po file I see new message
```%s: failed to add uid range %lu-%lu from '%s'\```
is the phrase```from '%s'``` correct here? Shouldn't it be ```to '%s'```?

Thanks,

**Comment by crayxt** [comment]
Lines
https://github.com/shadow-maint/shadow/blob/master/src/usermod.c#L2151
https://github.com/shadow-maint/shadow/blob/master/src/usermod.c#L2177

**Comment by hallyn** [comment]
Hi - good catch, I think indeed those should be 'add to', and were
presumably wrongly copied from 'remove from'.

**Comment by crayxt** [comment]
@hallyn ok, I am waithing for this and then updating the Kazakh translation, thanks
