### ISSUE TITLE
Please make siging public key publicly available

### ISSUE THREAD

**Issue by rbalint** [shadow-maint/shadow#497]
Hi,

I tried verifying the signature of 4.11.1 but I could not download the signing key from well known key servers:

```
$ gpg ../shadow-4.11.1.tar.xz.asc 
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: assuming signed data in '../shadow-4.11.1.tar.xz'
gpg: Signature made 2022. jan. 3., hétfő, 04:16:26 CET
gpg:                using RSA key A9BD3FF17072B6DB780FCF943570DA17270ACE24
gpg: requesting key 3570DA17270ACE24 from hkp server keys.gnupg.net
gpg: Can't check signature: No public key

```

**Comment by jubalh** [comment]
Since 4.10 a different key is used.

In https://github.com/shadow-maint/shadow/blob/master/SECURITY.md the new key is mentioned.
It's certainly available on the key servers.

**Comment by rbalint** [comment]
Thanks, I've found it on pgp.mit.edu.
