### ISSUE TITLE
Is it good to default to creating mail spool dirs?

### ISSUE THREAD

**Issue by rbalint** [shadow-maint/shadow#501]
I think less and less people use mail on their systems and those directories just end up being unused.
Debian ships a different configuration file for adduser which defaulted to not creating those mail directories and I plan sticking to this default in the package to minimize the disruption of updates. 
The reason I'm raising this topic is that bbf4b79bc49fd1826eb41f6629669ef0b647267b changed the hardcoded default in useradd and I'm wondering if other distros find the hardcoded values right for them or they override them, too.

**Comment by doverride** [comment]
Fedora useradd creates mail spool file by default. I kind of like that and I do not see a huge problem with it. The upside of doing this is that you have a central place because sometimes properly creating a mail spool file is not as straight forward as one may think.

**Comment by rbalint** [comment]
Thanks for the comments! With Fedora shipping with that default it is probably better to keep it in the upstream project.
