### ISSUE TITLE
/etc/sub{u:g}id

### ISSUE THREAD

**Issue by riesebie** [shadow-maint/shadow#504]
The manpage of both `subgid 5` and `subuid 5` mention `Note, that {group:user}add will only create entries in /etc/sub{g:u}id if subid delegation is managed via subid files.` What are the subid files and how can I manage to not create the /etc/sub files?

**Comment by ikerexxe** [comment]
The subid files track the subordinate id ranges allocated locally. As an example you can `cat /etc/subuid` to check which ranges have already been allocated.

If you are the package maintainer for a distribution you can disable the whole subid feature, including the subid files, by using `enable_subids=no` when configuring the build. If you aren't a package maintainer but you are a system administrator, I guess you could build the package on your own with the aforementioned option, but this could be difficult to do and maintain.

Can you explain why do you want to disable it?

**Comment by riesebie** [comment]
Well the idea is to implement a "disk quota" based upon the userid. Unfortunately a user can grab a uid form /etc/subuid to sidetrack his uid from /etc/passwd and use disk space no matter what the quota is.

**Comment by ikerexxe** [comment]
Can't you use the username? Or better still, the groupname?

**Comment by hallyn** [comment]
Setting SUB_UID_COUNT and SUB_GID_COUNT to 0 in /etc/login.defs should do what you want.  If that's not working (there were issues in the past), please open a bug.

**Comment by MichaelHierweck** [comment]
Setting  SUB_UID_COUNT and SUB_GID_COUNT to  0 does not work:

useradd: Can't get unique subordinate UID range
useradd: can't create subordinate user IDs
