### ISSUE TITLE
Usermod ignores malformed options ?

### ISSUE THREAD

**Issue by BillDietrich** [shadow-maint/shadow#506]
I ran the badly-formed command ```sudo usermod -append -G mail user1``` and got no error message (should be ```--append```).  Instead of appending group mail to user user1, it made mail the sole group of user user1.  [Please confirm; I am writing from memory, and reluctant to test again because it put my account into a bad state.]

Do other commands in this package act the same way ?  This is dangerous.

Also notice that there is no --version option on the command.

I'm using shadow-utils 4.11.1 on Endeavour 2021.12.17 LXQt.

**Comment by ikerexxe** [comment]
Thanks for the feedback. I haven't been able to reproduce the behaviour that you mentioned, but there's something wrong because using append with just one hyphen (-append) allows to append the group.

Test:
```
# id testuser
uid=1000(testuser) gid=1000(testuser) groups=1000(testuser)
# usermod -append -G testgroup testuser
# id testuser
uid=1000(testuser) gid=1000(testuser) groups=1000(testuser),1001(testgroup)
```

I've also user shadow-utils 4.11.1 but in my case it was the Fedora version.

**Comment by edneville** [comment]
The first `p` in `-append` treats the rest of the word as the encrypted password, like `-p` were used. I believe that's normal behaviour for getopt_long.

`user1` and `testuser` above will have `pend` as their encrypted password hash.

Personally, short single letter options are nice if typing from a mobile device is tedious, but long `--` options are good as they're easier to read back later in command history or when copy/paste to script.
