### ISSUE TITLE
Please remove debian packaging related tags from the repository

### ISSUE THREAD

**Issue by rbalint** [shadow-maint/shadow#51]
They are most likely confusing for most people. There is a packaging repository referenced from the Debian package where the tags are present and expected:
https://anonscm.debian.org/gitweb/?p=pkg-shadow/shadow.git

**Comment by hallyn** [comment]
Thanks, I *think* I've deleted them.

**Comment by hallyn** [comment]
Actually I also managed to delete some (two?) "upstream/*" tags.  Do you by any chance have those in your tree?

**Comment by rbalint** [comment]
@hallyn Yes, but it is OK, they did not belong here either

**Comment by rbalint** [comment]
upstream/4.2 was identical to the one in the packaging repo

**Comment by rbalint** [comment]
upstream/4.4 contained manually generated files which were not OK IMO

**Comment by hallyn** [comment]
Great - thanks.
