### ISSUE TITLE
Kernels < 3.17 not supported? No fallback to /dev/urandom

### ISSUE THREAD

**Issue by jcchong17** [shadow-maint/shadow#512]
I have encountered an issue with Shadow 4.11.1 not salting the passwords at all if running a Linux kernel 3.2 (or anything under 3.17) host. Everything builds correctly, but running passwd root or any other username results in "Unable to obtain random bytes."

The code is in libmisc/salt.c. (Lines 155-177.) It tries to get random bytes from arc4random_buf (BSD systems), getentropy(), getrandom(), and finally /dev/urandom in that order, but only chooses ONE of those before exiting/failing. This is presumably for security reasons.

Getentropy and getrandom have been defined since glibc 2.25. (https://sourceware.org/bugzilla/show_bug.cgi?id=17252) However, if they lack kernel support, (i.e. < 3.17) the read_random_bytes routine exits without getting any random bytes. If running a 3.2 kernel, running even a current current glibc fails to get random bytes.

Attempting to build Shadow on with kernel 3.2 AND glibc < 2.25 doesn't have the same issue. The old glibc doesn't define getentropy and getrandom at all, and the fallback /dev/urandom is used. This is not the case with a >= glibc 2.25 inside a chroot. (Trying to build LFS.)

Any thoughts on this? Can't /dev/urandom be used as a catch-all fallback for systems with a mixed 3.2 and newer glibc?

Thank you.

**Comment by hallyn** [comment]
Yes, agreed, urandom should be a catchall if the others are there but fail.  I think that case was just not considered.  Would you like to provide a patch to do that?
