### ISSUE TITLE
non-Unix-like behaviour, adduser infinite output loop

### ISSUE THREAD

**Issue by dchmelik** [shadow-maint/shadow#516]
When I upgraded to Slackware GNU/Linux 15, I found passwd (and script using it, adduser) is no longer Unix-like: requires  certain style/length passwords.  This isn't Unix-like.  Though some server-/security-oriented Unixes (OpenBSD) do similar, ones more traditional also for other usage such as desktops & virtual environments & clusters including without external ports open to Internet, such as FreeBSD (still as of 13, and probably NetBSD 9.2 also) don't force passwords, when you install nor when using passwd, and even ask if you want blank password (though probably default no: ) even root.
&nbsp;&nbsp;&nbsp; I doubt Patrick Volkerding (Slackware creator) broke this, as tends to keep software as-is from upstream, so I suppose you did this (but if I'm wrong, just close this) and if I'm right please give root power back such as in a configuration file whether they want to allow blank or force passwords, and certain length or not, and certain style or not, or whatever else you think might help cases needed such as servers.  I know root can still blank with an argument/flag/switch (and editing /etc/passwd) but isn't as good.

**Comment by hallyn** [comment]
can you give an example of the changed behavior?

**Comment by dchmelik** [comment]
Here are excerpts; same for root though apparently root has exceptions (used to work without message on first try but now second try, just annoying if root didn't decide/implement such standards for their own system.)
```
d@cosmos:~$ passwd
New password: 
BAD PASSWORD: No password supplied
New password: 
BAD PASSWORD: No password supplied
New password: 
BAD PASSWORD: No password supplied
passwd: Have exhausted maximum number of retries for service
passwd: password unchanged
d@cosmos:~$ passwd
New password: 
BAD PASSWORD: The password is a palindrome
New password: 
BAD PASSWORD: The password is a palindrome
New password: 
BAD PASSWORD: The password is a palindrome
passwd: Have exhausted maximum number of retries for service
passwd: password unchanged
d@cosmos:~$ passwd
New password: 
BAD PASSWORD: The password is shorter than 6 characters
New password: 
BAD PASSWORD: The password is shorter than 6 characters
New password: 
BAD PASSWORD: The password is shorter than 6 characters
passwd: Have exhausted maximum number of retries for service
passwd: password unchanged

```
None this happens on standard Unixes unless root makes it setup, or a few Unixes (OpenBSD) more oriented to servers than desktops.  NetBSD & FreeBSD kept tradition users (even root) can do this on first try with no message, though I think newer *BSD/OpenSolaris derivatives, such as some/all IllumOS, have require initial (but removable) passwords (since maybe PAM originated on Solaris.)
        It's up to root whether they allow blank passwords and what style/length of passwords and whether they want to restrict number of retries, which didn't happen before either.  Even strictly Unix-like GNU/Linux like Slackware are using PAM now but it seems you're forcing non-Unix-like behaviour for all GNU/Linux distributions that feel forced to jump on the bandwagon. It's good enough ssh, etc. forbid remote blank password logins by default, and if an organization/company offers shell accounts they presumably require passwords (other than perhaps guests on public access Unix like FreeShell.org) but often use real Unix and have ways to require.

**Comment by hallyn** [comment]
This is all configurable via /etc/login.defs.  See OBSCURE_CHECKS_ENAB and PASS_MIN_LEN.
