### ISSUE TITLE
useradd requires SUB_{UG}ID_COUNT > 0

### ISSUE THREAD

**Issue by MichaelHierweck** [shadow-maint/shadow#517]
It seems it's not possible to skip the assignment of sub{ug}ids when invoking useradd, especially setting SUB_UID_COUNT and SUB_GID_COUNT to 0 does not work:

useradd: Can't get unique subordinate UID range
useradd: can't create subordinate user IDs

See also: #504 

However it is possible to remove all sub{ug}ids by invoking usermod afterwards.

Please make the (inital) assignment of subids optional.

**Comment by hallyn** [comment]
This is fixed since https://github.com/shadow-maint/shadow/commit/663824ef4ca927aa2b4319b69e0bfa68282ec719 .
