### ISSUE TITLE
login doesn't update /var/log/btmp when using PAM

### ISSUE THREAD

**Issue by fatherMatrix** [shadow-maint/shadow#521]
When I configure shadow-utils with "--with-pam", then the failed login doesn't append a log to /var/log/btmp. I read the source code and find that it seems login assume PAM will handle it?

**Comment by hallyn** [comment]
Correct.  If you look at the PAM code, it suggests that it will only happen when you pass 'showfailed' argument to pam_lastlog.

**Comment by fatherMatrix** [comment]
But there is not codes in pam_lastlog to append a log to /var/log/btmp when login failed?
