### ISSUE TITLE
chsh should check whether shell is listed in /etc/shells for root

### ISSUE THREAD

**Issue by CamberLoid** [shadow-maint/shadow#535]
Currently, `chsh` will check whether the shell is listed in `/etc/shells` for non-root users but not for root.

https://github.com/shadow-maint/shadow/blob/1f84142915809713c920c8c01ccaca6835bca179/src/chsh.c#L517-L530

This may lead to a login failure when, for example, user sets shell to `/bin/bash` instead of `/usr/bin/bash`, which the former is not listed in `/etc/shells`. `chsh` should warn user that the possible invalid shell is provided. 

An expected behavior is to warn the root user that `Warning: $SHELL is not present in /etc/shells`.

**Comment by hallyn** [comment]
Yeah I suppose that would be polite.

**Comment by hallyn** [comment]
Did you want to post a PR for this?

**Comment by jubalh** [comment]
Honestly I feel like the current settings and warnings are fine.
However I created https://github.com/shadow-maint/shadow/pull/759 to change according to this PR.
I leave it up to the maintainers to decide which way they prefer and close this issue without merging the PR or with merging it.
