### ISSUE TITLE
useradd - [libsemanage]: MLS is disabled, but MLS range s0 was found - Cannot commit SELinux transaction

### ISSUE THREAD

**Issue by genbtc** [shadow-maint/shadow#552]
Shadow v. 4.11.1 - (useradd)
OS: Gentoo amd64.
SELinux 3.4 (also tested 3.2, the same), Policy: Strict (not MLS)

Description: 
All I wanted to do was make a user, with the -Z option, but it fails with this:

`genr8too ~ # useradd -m -Z staff_u superuser7`
`[libsemanage]: MLS is disabled, but MLS range s0 was found for Unix user superuser7`
`[libsemanage]: seuser mapping [superuser7 -> (staff_u, s0)] is invalid`
`[libsemanage]: could not iterate over records`
`Cannot commit SELinux transaction`
`useradd: warning: the user name superuser7 to staff_u SELinux user mapping failed.`
`useradd: /home/superuser7 was created, but could not be removed`

FIX: shadow-useradd-selinux-MLS-option.patch
really just two lines, adding a `if (semanage_mls_enabled(handle)) {` check guarding around the part where it calls semanage_seuser_set_mlsrange() requesting a DEFAULT_SERANGE of s0, so it just skips this part unless MLS already active

```

From a0870a771b2ae371a65ac0b2d105646b744dd46c Mon Sep 17 00:00:00 2001
From: genbtc <genbtc+NOBOTS@gmx.com>
Date: Tue, 16 Aug 2022 17:54:41 -0400
Subject: [PATCH] MLS is optional, check active policy first

---
 lib/semanage.c | 30 +++++++++++++++++-------------
 1 file changed, 17 insertions(+), 13 deletions(-)

diff --git a/lib/semanage.c b/lib/semanage.c
index 1240160..b66d00b 100644
--- a/lib/semanage.c
+++ b/lib/semanage.c
@@ -121,12 +121,14 @@ static int semanage_user_mod (semanage_handle_t *handle,
 		goto done;
 	}
 
-	ret = semanage_seuser_set_mlsrange (handle, seuser, DEFAULT_SERANGE);
-	if (ret != 0) {
-		fprintf (shadow_logfd,
-		         _("Could not set serange for %s\n"), login_name);
-		ret = 1;
-		goto done;
+	if (semanage_mls_enabled(handle)) {
+		ret = semanage_seuser_set_mlsrange (handle, seuser, DEFAULT_SERANGE);
+		if (ret != 0) {
+			fprintf (shadow_logfd,
+			         _("Could not set serange for %s\n"), login_name);
+			ret = 1;
+			goto done;
+		}
 	}
 
 	ret = semanage_seuser_set_sename (handle, seuser, seuser_name);
@@ -178,13 +180,15 @@ static int semanage_user_add (semanage_handle_t *handle,
 		goto done;
 	}
 
-	ret = semanage_seuser_set_mlsrange (handle, seuser, DEFAULT_SERANGE);
-	if (ret != 0) {
-		fprintf (shadow_logfd,
-		         _("Could not set serange for %s\n"),
-		         login_name);
-		ret = 1;
-		goto done;
+	if (semanage_mls_enabled(handle)) {
+		ret = semanage_seuser_set_mlsrange (handle, seuser, DEFAULT_SERANGE);
+		if (ret != 0) {
+			fprintf (shadow_logfd,
+			         _("Could not set serange for %s\n"),
+			         login_name);
+			ret = 1;
+			goto done;
+		}
 	}
 
 	ret = semanage_seuser_set_sename (handle, seuser, seuser_name);
-- 
2.35.1

```

Now it works as expected.
Ive found reports on google of this being this way for some time, so if this is like this for some reason, please say.

**Comment by ikerexxe** [comment]
The change looks good to me. Do you mind opening a PR?
