### ISSUE TITLE
Avoid nss warning/error with musl

### ISSUE THREAD

**Issue by agherzan** [shadow-maint/shadow#557]
The libnss configuration file is only installed when glibc is used. The inexistence of it on a musl-based rootfs, will make shadow complain
about it:

> Failed opening /etc/nsswitch.conf

This is because shadow will try to use `nsswich.conf` when dealing with subordinate IDs and the message is just a warning as the tool will still generate them correctly in subuid/subgid files. To avoid confusion and needless errors on a musl system, could we do the nss support glibc specific?

**Comment by hallyn** [comment]
What would be the best way to detect that?  Detect during configure?

Or should we just get rid of that warning?

**Comment by agherzan** [comment]
I would keep it simple for now and just drop the warning. I don't see much of its value at this point.
