### ISSUE TITLE
How to build and install?

### ISSUE THREAD

**Issue by alejandro-colomar** [shadow-maint/shadow#567]
Hi!

Please add an INSTALL file that explains how to compile and install.

Cheers,
Alex

**Comment by flyxyz123** [comment]
```sh
git clone git@github.com:shadow-maint/shadow.git
cd shadow
./configure
make
sudo make install
```

**Comment by hallyn** [comment]
Well, I guess the INSTALL file still isn't there.  Should we still create one?  Just add this to README.md?

**Comment by alejandro-colomar** [comment]
I would like to see it.  I'd do it myself if I knew all the details of building and testing this project.  Please have a look at the files I added recently to the Linux man-pages, and take whatever you like from there:

<https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/CONTRIBUTING>
<https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/INSTALL>
<https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/RELEASE>
<https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/README>

I'm very interested in review of those files, so if you think anything from there can be improved, or is good, please tell me.  I'm especially proud of the RELEASE file, since very few projects document how that is done, and there's hidden knowledge of what a new maintainer has to do for taking over.  In fact, I wrote that because I felt the need for it when Michael got AWOL, and didn't want some future maintainer to have the same problem when I decide to leave.

As a newcomer to this project (okay, not so much after so many patches, but still :p), I can tell you what I miss:

Steps for testing the entire build locally, without risk of damaging my system.  I know there are some recommendations, mentioning `chroot`, but they are quite vague for someone who has never run a chroot.  I'd like to see a list of steps that a highschool kid could follow, similar to my release steps (those assume you have a GPG and SSH set of keys already trusted by kernel.org, but apart from that, they are quite complete).  I also wrote some relatively complete set of commands to run linters on patches to the man pages.

If you feel like documenting the release process too, that'd be great.

**Comment by jubalh** [comment]
> Steps for testing the entire build locally, without risk of damaging my system

@alejandro-colomar since you now have quite some PRs here I wondered whether you might have a workflow regarding this that could be worth sharing?

**Comment by alejandro-colomar** [comment]
> > Steps for testing the entire build locally, without risk of damaging my system
> 
> @alejandro-colomar since you now have quite some PRs here I wondered whether you might have a workflow regarding this that could be worth sharing?

Sure.  For some time, I've been thinking of moving to a more structured setup, such as the one I use for the Linux man-pages or NGINX Unit, but was lazy for doing it.  So far, for shadow, I only had a simple clone with many branches, and I switched from branch to branch.  It wasn't ideal, but it works.  Anyway, I've now moved to worktrees (which is what I've been using for the man-pages and nginx, which are more comfortable, so I'll detail that.

Here are some steps to reproduce the directory structure I have, and prepare the branch "readpassphrase" (my latest PR):

```sh
alx@debian:~$ mkdir -p src/shadow/shadow
alx@debian:~$ cd src/shadow/shadow
alx@debian:~/src/shadow/shadow$ git clone --bare git@github.com:shadow-maint/shadow.git .bare.git
alx@debian:~/src/shadow/shadow$ cd .bare.git
alx@debian:~/src/shadow/shadow/.bare.git$ git worktree add ../master
alx@debian:~/src/shadow/shadow/.bare.git$ cd ../master
alx@debian:~/src/shadow/shadow/master$ git worktree add ../readpassphrase
alx@debian:~/src/shadow/shadow/master$ cd ../readpassphrase
alx@debian:~/src/shadow/shadow/readpassphrase$ git remote add gh git@github.com:alejandro-colomar/shadow.git
alx@debian:~/src/shadow/shadow/readpassphrase$ git remote add alx ssh://www.alejandro-/srv/src/alx/shadow/shadow.git
alx@debian:~/src/shadow/shadow/readpassphrase$ vi libmisc/agetpass.c
alx@debian:~/src/shadow/shadow/readpassphrase$ git add -p
alx@debian:~/src/shadow/shadow/readpassphrase$ git commit -s
alx@debian:~/src/shadow/shadow/readpassphrase$ git push -u gh
```

In other projects in which I have more experience, I test locally before pushing.  In this one, however, since I still don't know very well how to do it without breaking my system, I rarely do so.  So far, I rely on the CI to detect most issues.  Every now and then, I compile locally without testing.

**Comment by jubalh** [comment]
> In other projects in which I have more experience, I test locally before pushing. In this one, however, since I still don't know very well how to do it without breaking my system, I rarely do so

Same here. Sometimes putting the binary in a VM or chroot.

**Comment by hallyn** [comment]
I fire up a container or vm and run the following as root:

https://gist.github.com/hallyn/b3334ac19f3e3edf05f805ff49cfa981

Then I can make install, run tests, etc.

**Comment by jubalh** [comment]
I believe this issue can be closed due to above mentioned PR.
See https://github.com/shadow-maint/shadow/blob/master/doc/contributions/build_install.md
