### ISSUE TITLE
Tests are not included in the release tarballs

### ISSUE THREAD

**Issue by dvzrv** [shadow-maint/shadow#585]
Hi! I'm packaging shadow for Arch Linux.

To ensure that we can integrate software into our ecosystem we usually run tests. This project seems to have a lot of tests, but they are not included in the release tarballs. Is there a particular reason for excluding them? If not, could they be added to the tarballs of upcoming releases? That would be really helpful, thank you! :)

**Comment by dvzrv** [comment]
> Probably mainly because they're not safe to run on your system

What does this mean though? Do they require root? Do they alter the system's state?

We run our packaging environment in a pristine systemd-nspawn based container for each package, which might mitigate any issues towards the host. However, maybe if you can elaborate on what you mean by "not safe" it would become easier to assess, whether running the tests is worth it or not.
From a packaging perspective I guess it is always very welcomed to be able to run some form of test suite to ensure integration.

> Would a separate tarball help?

If you would not want to integrate it with the standard source tarball, sure!

**Comment by hallyn** [comment]
From tests/README:

```
  1 This testsuite is NOT SECURE: it will temporarily change your passwords file
  2 with known passwords.
  3 You should run it on a chroot, or on a secured dedicated system.
```

It works pretty hard to not leave your system in a bad state (though if, being a testsuite, it hits bugs, I suppose it might fail to do that), but while it's running the system will be in an insecure state.

**Comment by ikerexxe** [comment]
My opinion as a fedora maintainer is that the tests won't work in a non-Ubuntu environment. That's because the test framework replaces the existing `/etc/password` file leaving the system unconsistent. However, it may work in arch-Linux, but I doubt it.

**Comment by rbalint** [comment]
> From tests/README:
> 
> ```
>   1 This testsuite is NOT SECURE: it will temporarily change your passwords file
>   2 with known passwords.
>   3 You should run it on a chroot, or on a secured dedicated system.
> ```
> 
> It works pretty hard to not leave your system in a bad state (though if, being a testsuite, it hits bugs, I suppose it might fail to do that), but while it's running the system will be in an insecure state.

As the Debian maintainer I'd very much welcome having the tests in the original tarball to let it be used in an autopkgtest suite. I planned integrating them for a long time and I was quite sad when they were gone from the tarball.

The `tests/` dir could be renamed to `destructive-tests`, `system-breaking-tests` or something similar to make it harder for inexperienced developers to break their system accidentally. I also believe that developers working with the shadow code base are likely experienced enough and can be trusted to have the tests in the release tarball.

**Comment by jubalh** [comment]
> I also believe that developers working with the shadow code base are likely experienced enough and can be trusted to have the tests in the release tarball.

Most likely even experienced users/developers don't expect the tests to potentially break your system.

**Comment by hallyn** [comment]
Shipping them as 'destructive-tests' would be acceptable to me, if someone wants to do a PR.

**Comment by zeha** [comment]
I think this was done on master?
