### ISSUE TITLE
Proposal to change SUB_UID_MIN and SUB_GID_MIN

### ISSUE THREAD

**Issue by ikerexxe** [shadow-maint/shadow#597]
systemd has changed its minimum id for container's user ranges to 524288, thus breaking any `chown` attempt in the home directory to UIDs outside of the ranges defined by systemd (UIDs 65536-524287 are unmapped). From [systemd's NEWS document](https://github.com/systemd/systemd/blob/1d679b208d982bd5b8ba893981774cac5959b4b4/NEWS#L789):
```
Starting with v250 systemd-homed uses UID/GID mapping on the mounts
of activated home directories it manages (if the kernel and selected
file systems support it). So far it mapped three UID ranges: the
range from 0…60000, the user's own UID, and the range 60514…65534,
leaving everything else unmapped (in other words, the 16bit UID range
is mapped almost fully, with the exception of the UID subrange used
for systemd-homed users, with one exception: the user's own UID).
Unmapped UIDs may not be used for file ownership in the home
directory — any chown() attempts with them will fail. With this
release a fourth range is added to these mappings:
524288…1879048191. This range is the UID range intended for container
uses...
```

Taking into account the previous information and the default value for SUB_UID_MIN (100000), this will affect any container in an environment that uses shadow-utils and systemd.  So, my proposal would be to change SUB_UID_MIN and SUB_GID_MIN to 524288 to avoid any compatibility issue with systemd in distributions that uses this software. I don't think it will impact other distributions.

I'd also like to change SUB_GID_MIN to be consistent with the value of SUB_UID_MIN.

Some additional information as to how systemd understands UIDs and GIDs: https://systemd.io/UIDS-GIDS/

**Comment by ikerexxe** [comment]
@hallyn any opinion? Can I move forward and open a PR to change the defaults?

**Comment by hallyn** [comment]
So the point is users who create unpriv containers under ~/.local/share/lxc won't have uid 100k mapped at the filesystem level?

I'm not entirely opposed, but I would think it would be better to let distros which configures things this way and with this systemd set higher values in their /etc/login.defs.  These numbers may change again, and keeping shadow's shipped defaults in sync with that doesn't seem doable in a timely fashion.  (By the time the upstream change is synced into distro packages, some time will likely have passed).

Incidentally (while I was trying to find background information) if I'm reading this right, https://github.com/systemd/systemd/blob/1d679b208d982bd5b8ba893981774cac5959b4b4/NEWS#L815 seems like bad advice.  The general idea is good, but a (preallocated, static) uid offset other than 0 should be used.

**Comment by ikerexxe** [comment]
> These numbers may change again, and keeping shadow's shipped defaults in sync with that doesn't seem doable in a timely fashion. (By the time the upstream change is synced into distro packages, some time will likely have passed).

Makes sense. So, I won't make any change in the defaults.
 
> Incidentally (while I was trying to find background information) if I'm reading this right, https://github.com/systemd/systemd/blob/1d679b208d982bd5b8ba893981774cac5959b4b4/NEWS#L815 seems like bad advice. The general idea is good, but a (preallocated, static) uid offset other than 0 should be used.

I'm having problems understanding that paragraph :( I understand what they are trying to achieve, but I don't know how they are doing it.
