### ISSUE TITLE
Raise minimum ISO C to C99, or even further to POSIX.1-2001 (or 2008) and C11

### ISSUE THREAD

**Issue by alejandro-colomar** [shadow-maint/shadow#600]
Hi!

Supporting C89 is burdensome.  I did a lot of cleanup in the last year dropping support for pre-ISO C, which we can assume to be dead.  However, there are still lots of code (and configure code too) for supporting C89, like for example conditionals on having <stdbool.h>.  Since these days all compilers support C99, would you agree that we can raise the bar to ISO C99, and fail to compile on anything older than that?

Even the oldest Debian and CentOS that are on extended LTS have partial support for ISO C11, and full support for ISO C99 (the oldest compiler alive on those systems is some gcc 4.x, as I checked some time ago).

Moreover, ISO C23 will make `true` and `false` be predefined macros (no need to include `<stdbool.h>` for having them), so most pre-C99 code that defines them will turn Undefined Behavior.  Why is it UB?  Redefining macros is valid in C, except that the redefinitions must be identical (excluding comments and whitespace); since we wrap them in parentheses and glibc doesn't, our redefinition is invalid.  We could address this by wrapping our redefinitions in yet more ifdef preprocessor, but I'd rather burn it all, and require C99.

Would you like a round of cleanup based on this?

Cheers,
Alex

**Comment by ikerexxe** [comment]
I like this idea, and I think it would be good to move forward to more actual standards.

I'd like to ask something though, what's your exact proposal? Move to ISO C99 and POSIX.1-2001? I don't see any issue for the latter. I'm not implying that you should open one, as we could perfectly use this issue for both efforts. Is there any additional work that you have in mind? I'd like to have a clear idea before starting to review anything in this area.

**Comment by alejandro-colomar** [comment]
Hi Iker!

> I like this idea, and I think it would be good to move forward to more actual standards.
> 
> I'd like to ask something though, what's your exact proposal? Move to ISO C99 and POSIX.1-2001? I don't see any issue for the latter. I'm not implying that you should open one, as we could perfectly use this issue for both efforts. Is there any additional work that you have in mind? I'd like to have a clear idea before starting to review anything in this area.

Heh, I didn't even had POSIX.1-2001 in mind when I opened this issue.  It was while doing the C99 cleanup when I realised that POSIX.1-2001 would bring a much greater cleanup, so I did it.  The next standards are:

-  POSIX.1-2008.  It doesn't allow for any further cleanups in this project, AFAICS.  We could even claim POSIX.1-2008 minimum, but the code wouldn't change.  Also, POSIX.1-2008 removes some good functions, such as `bzero(3)`, so I'm happy with the good ol' POSIX.1-2001.

- C11 is the next C standard that brings important features, and in fact, I'll probably need some of them for my string handling improvements (`static_assert(3)`).  However, there are still some systems alive where C11 is not fully supported, so we need to discuss that more carefully.  We can discuss that after the C99 / POSIX.1-2001 cleanups, as a separate topic.

Does that make sense?

Cheers,

Alex

**Comment by vapier** [comment]
I'd say C99 is absolute bare minimum.  Even requiring C11 is completely reasonable.

**Comment by alejandro-colomar** [comment]
Thanks Mike!  Yep, IMO, C89 is dead, and should be buried.  C11 is also quite reasonable, and only projects that need extreme backwards compatibility need waiting till CentOS 7 is dead.  I didn't know how much of that shadow-utils needs, but I tend to believe that C11 is reasonable to ask these days.

So, if there's consensus that we can also go that far, I'll check if there are any things that we can simplify/improve with C11 as a requirement.

**Comment by alejandro-colomar** [comment]
We now require C11 and POSIX.1-2008.
