### ISSUE TITLE
Proposal: Add shadow utils translations to  Translation Project

### ISSUE THREAD

**Issue by hanklank** [shadow-maint/shadow#61]
As an active translator, I see that it's much easier for us if different core translations are somewhat gathered at the same place, and as there already exists an place for free software, Translation Project, (https://translationproject.org/html/welcome.html) that has important projects like for example coreutils. I wonder if it would be possible to also make use of that service for Shadow utils in future translations. The benefits would be: easier overview for translators, and maybe it would attract more active  translators.

I found an old proposal for this, https://lists.debian.org/debian-l10n-spanish/2008/03/msg00038.html but nothing happened back then.

**Comment by hallyn** [comment]
I'm all for this.

**Comment by hallyn** [comment]
So I should do a pre-release and send an email to coordinator@translationproject.org as per https://translationproject.org/html/maintainers.html ?

**Comment by hallyn** [comment]
Sent an email about the 4.7 (pre-?)-release.

**Comment by hanklank** [comment]
Great, hope to see it there soon. Thanks.

**Comment by hallyn** [comment]
It might not happen.  They want full ownership of the translations.  I need information about the debian translation project's relation here.  translationproject.org may not be an option.
