### ISSUE TITLE
<utmpx.h>, POSIX and the XSI extension, and OS requirements

### ISSUE THREAD

**Issue by alejandro-colomar** [shadow-maint/shadow#610]
Hi!

Sorry, I made some mistake when upgrading to POSIX.1-2001.  I didn't realize that utmpx(5) is not required by POSIX.1-2001.  It's defined by POSIX as an XSI extension, so some systems may chose to not support it.  I checked that OpenBSD doesn't support it (FreeBSD does support it).

So, the questions would be, how portable do we need to be?  Should we revert that change?  Is OpenBSD a target for this project?

**Comment by hallyn** [comment]
I don't believe openBSD is a target for this project.  AFAIK it explicitly is Linux only.  Hopefully someone will speak up if I'm wrong about that.
