### ISSUE TITLE
__int128 is not available on all platforms

### ISSUE THREAD

**Issue by atsampson** [shadow-maint/shadow#634]
Commit 1a0e13f94edc08d4c773a00d710d56fac966e818 ("Optimize csrand_uniform()") makes shadow unconditionally use GCC's `__int128` extension type. However, this doesn't exist on all platforms - armv7, ia32 and m68k at least don't have it, so shadow now fails to build on those platforms:

```
csrand.c: In function 'csrand_uniform':
csrand.c:81:18: error: '__int128' is not supported on this target
```

**Comment by ikerexxe** [comment]
@alejandro-colomar can you take a look at this one? I think you already suggested a method to avoid this problem?

**Comment by alejandro-colomar** [comment]
Yup, I'll take it :)

**Comment by atsampson** [comment]
Great - that builds again on all my platforms. Thanks very much!
