### ISSUE TITLE
Unifying --prefix behaviour

### ISSUE THREAD

**Issue by jubalh** [shadow-maint/shadow#657]
(I actually intended to open a PR for this, but since I didn't get around to it I at least wanted to create this issue now)

The following commands support the `--prefix` flat:
useradd, userdel, usermod, groupadd, groupdel and groupmod
Other commands don't, like:
passwd, chpasswd and chage

I think to be consistent all our commands should support the `--prefix` option.

I only took a quick look at the code. And it seems like in the first group of commands we use helper functions from `libmisc/prefix_flat.c` like `process_prefix_flag()` and wrappers like `prefix_getgrnam()` instead of `getgrnam()`.

**Comment by ancorgs** [comment]
Any news about this?

**Comment by ikerexxe** [comment]
I'd definitely welcome this functionality in all commands. Unfortunately, I can't do it myself, so I'll review patches if anybody is interested in providing them.

**Comment by jubalh** [comment]
Unfortunately I don't have much time for this yet.
I made a tiny start though, a couple of weeks ago. It doesn't do anything meaningful yet since I still needed to wrap my head around the current code.

If anybody wants to continue: https://github.com/jubalh/shadow/tree/feat/prefix
