### ISSUE TITLE
Add SSH key from file/stdin when creating user

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [shadow-maint/shadow#663]
#### Background

It happens to me that adding an ssh public key when creating a user becomes a common practice in my daily sysadmin work.

Usually, I have to type several commands to correctly set up a user account, e.g.

```bash
useradd -m username
su - username
mkdir .ssh && chmod 700 .ssh && cd .ssh
curl example.com/key -o authorized_keys
chmod 600 authorized_keys
exit
# especially authorized_keys is prone to be spelled wrongly
# I then need to look up the sshd log and find that mistake
```

Of course, it could be solved by some ad-hoc script that invokes the command above.

It may also be done by adding the script to `/etc/shadow-maint/useradd-post.d/` 

However, when it comes to different clusters of machines, that script also has to be distributed, and `scp`ing it around is annoying, unless it is distributed with the software package.

Also, I believe many other users have repeated similar behavior and a convenient way is helpful.

#### Expected behavior

```bash
# from file
curl example.com/key -o /tmp/key && useradd -m -sshkey /tmp/key username
# then key is in ~username/.ssh/authorized_keys with permission setup correctly

# or from stdin
curl example.com/key | useradd -m -sshkey - username

# or even further (not recommended as this will add dependencies on HTTP request libs, like libcurl)
# this one is really convenient for users
useradd -m -github githubname username
```

#### Why it is not in `/etc/shadow-maint/useradd-post.d/`

It is hard to satisfy all user needs with a shell script, given the different user environments.

With a binary program, the behavior is the cleanest and most deterministic.

Also, we have to pass the URL or the file path of the public key to the script, which can not be done now.

#### Is this acceptable

I'm willing to implement this feature. It seems that there is needed infrastructure like copying a file, making a directory, and setting up the permission.

However, I do not know whether such a change is acceptable, so I open an issue here for comments and feedback.

This feature may have security implications, but I think it is as secure as copying the `skel` directory.

**Comment by ikerexxe** [comment]
mmm I'm against this idea because it goes against the Unix philosophy:
```
Make each program do one thing well. To do a new job, build afresh rather
than complicate old programs by adding new "features".
```

Did you consider using [Ansible](https://en.wikipedia.org/wiki/Ansible_(software)) (or some other alternative) to do this job? You could create a playbook to set up user accounts. It would be short and easy to do.

**Comment by ZenithalHourlyRate** [comment]
> Did you consider using [Ansible](https://en.wikipedia.org/wiki/Ansible_(software)) (or some other alternative) to do this job? You could create a playbook to set up user accounts. It would be short and easy to do.

Thanks for the suggestion. I've found a oneliner for this job.
https://gist.github.com/shohey1226/9283994?permalink_comment_id=2142845#gistcomment-2142845
