### ISSUE TITLE
Security Vulnerability Submission Per Security Policy

### ISSUE THREAD

**Issue by twdave** [shadow-maint/shadow#682]
Hello,

I've sent an initial email to Serge and Christian, as directed by https://github.com/shadow-maint/shadow/security/policy, regarding a potential security vulnerability.

Can you please respond at your earliest convenience?

Thank you.
David

**Comment by twdave** [comment]
I've received your reply and will forward the details. Thank you.

**Comment by hallyn** [comment]
My apologies, I can't even tell what happened to that email.  It's like it got dropped by the spam filters entirely.  It was only in my catch-all-pre-filtered box.
