### ISSUE TITLE
an error is reported when the grpconv command is executed

### ISSUE THREAD

**Issue by wyj611** [shadow-maint/shadow#686]
![image](https://user-images.githubusercontent.com/22022968/227149679-fda4b235-88f1-43e6-9287-0bbbb781678c.png)

**Comment by wyj611** [comment]
Maybe there's something wrong with this PR:[changing lock mechanism](https://github.com/shadow-maint/shadow/commit/65470e5c7ddbc2885ad35fbd0218b91a75626c2f), should O_CREAT be added to the second parameter of function open in the function do_fcntl_lock?

**Comment by jubalh** [comment]
@wyj611 did the changes fix your issue?
If yes we can close this.

**Comment by wyj611** [comment]
> @wyj611 did the changes fix your issue? If yes we can close this.

yes, of course
