### ISSUE TITLE
Password strength

### ISSUE THREAD

**Issue by alejandro-colomar** [shadow-maint/shadow#688]
https://github.com/shadow-maint/shadow/blob/53a4bda9ba560db52da475bb27b88b0291fe2835/man/passwd.1.xml#L97

Hi!

Today I had to register in an official administration website in my country.  To my surprise, when I tried to paste the result of my usual `makepasswd --char 64`, it didn't accept more than 20 characters (but they of course mandated the usual upper+lower+num+symbol, d'oh).  I think that advice in passwd(1) is actively harmful to society, and is one of the reasons MFA is being enforced in some places: most passwords are crap.

Ignoring the possibility of bugs in password handling when it includes special characters, which is more than likely (not talking of shadow, but of software in general, especially in random websites), there's the issue that perceived strength of passwords is bogus.

My keyboard has 27 letters, so counting upper, lower, and nums, I have 62 different characters in non-weird passwords.  For a reasonable length of 64 chars, that's a strength of `log2(62^64) = 381 bits of entropy`.  Now, apart from those 62 different chars, my keyboard can write 32 extra different characters, which amounts to a total of 94 different chars; for a maximum length of 20 chars, I'm limited to a strength of `log2(94^20) = 131 bits of entropy`.  For a length of 8, as suggested in passwd(1), the strength is `log2(94^8) = 52 bits of entropy`, which is the same as a password of only lowercase letters of length 11: `log2(27^11) = 52`.  Can we please remove that bogus advice?  The exponent is the key in password strength, not the base.  Even a school child should know that exponential.

Can we please completely rewrite that paragraph to only recommend password length?

Of course, I can't submit this without referencing the relevant: <https://xkcd.com/936/>

And to all that, sum the chance that I may need to use a different keyboard at some point, and maybe some symbols have no key.

**Comment by vapier** [comment]
that's quite the monstrous leap of faith to claim this one bit of obscure advice is a significant factor in the rise of MFAs.  i can guarantee you that the vast majority of the internet population has never read this text, and MFAs make sense even if people had better password hygiene.

**Comment by alejandro-colomar** [comment]
> i can guarantee you that the vast majority of the internet population has never read this text

"this" as in read passwd(1), probably not.  "this" as in any other repetition of this message, which seems to be everywhere (including most sign up pages), I'd say even my mom has read or at least heard about it (after asking, she confirms: from sign up pages).
