### ISSUE TITLE
Y2038: overflow in strtoday with 32-bit long and 64-bit time_t

### ISSUE THREAD

**Issue by dtaylor84** [shadow-maint/shadow#704]
I think there's a missing pair of parentheses in strtoday():

https://github.com/shadow-maint/shadow/blob/master/libmisc/strtoday.c#L76

> return (long) (t + DAY / 2) / DAY;

should be

> return (long) ((t + DAY / 2) / DAY);

to avoid the intermediate calculations overflowing with a 32-bit long.

(Noted here https://rachelbythebay.com/w/2023/01/26/shadow/)

**Comment by jubalh** [comment]
Regarding Y2038: today I became aware of https://github.com/thkukuk/lastlog2

**Comment by dtaylor84** [comment]
That would be simpler, yes.
