### ISSUE TITLE
Please add myself as old maintainer

### ISSUE THREAD

**Issue by marekm72** [shadow-maint/shadow#708]
I was a maintainer of this code long long ago (1995-2000), fixing some bugs and probably adding some new ones too, the exact commits lost in history but traces of me can still be found as "marekm" in some places of the code, NEWS and ChangeLog files.  I've since moved on and changed e-mail addresses, but I'm still alive.  May I kindly ask to be added in AUTHORS?  Thanks.

Marek Michałkiewicz - marekm72@gmail.com

**Comment by hallyn** [comment]
Happy to!  Hope all's going great.
