### ISSUE TITLE
new version of shadow overdue 

### ISSUE THREAD

**Issue by fjaell** [shadow-maint/shadow#73]
version 4.4 is from September 2016 and we had a lot of important fixes since that, including some security fixes. It would be very helpful if a new tarball, let's say 4.4.1, would be available.

Thanks.

**Comment by SeventhSonOfASeventhSon** [comment]
+!

**Comment by SeventhSonOfASeventhSon** [comment]
+1

**Comment by hallyn** [comment]
Wow, it's been that long?  I'll do a new release.  Any reason not to make it 4.5?

**Comment by hallyn** [comment]
4.5 released.  Thanks for the poke.  Time flies.
