### ISSUE TITLE
drop error message for unknown /etc/logins.def item

### ISSUE THREAD

**Issue by hallyn** [shadow-maint/shadow#746]
lib/getdev.c:def_find() logs a LOG_CRIT message for any unknown configuration item found in login.defs.  If you downgrade to an older shadow, or just partially upgrade, you'll get these warnings (which were reported to a debian bug).

There are two reasons we might log these:

1. To warn against a maliciously modified login.defs
2. To warn against accidental unintended typos.

It seems like a linter (passwd --check-login-defs) would be a better way to handle this.

But, as always, on a venerable project like this, I generally prefer to err on the side of fewer changes.  So, perhaps the better thing to do is just add "shadow: " as a prefix to that message.

(I'd say let's use /proc/self/cmdline instead of 'shadow:', but then parsing that could introduce its own bugs and isn't entirely reliable anyway, so I didn't)

What do people think?

**Comment by ikerexxe** [comment]
> But, as always, on a venerable project like this, I generally prefer to err on the side of fewer changes. So, perhaps the better thing to do is just add "shadow: " as a prefix to that message.

This seems the simplest solution, which would still provide useful information.
