### ISSUE TITLE
How to help translate manpages?

### ISSUE THREAD

**Issue by zica87** [shadow-maint/shadow#747]
I noticed that zh_tw translations of the manpages have not been updated for many years, and contain many meaningless spaces and some typos.

How do I help translate the manpages?

**Comment by hallyn** [comment]
Please feel free to post a github pull request with the updates to man/zh_TW/ .  If you're asking more practically how to build and test the result first, please let us know (we could probably stand to post some dev-howto documents under doc/.

**Comment by zica87** [comment]
I haven't start translating. I just want to first clarify what should I do.

I see there is a `po` directory in the `man` directory.
So I should translate `shadow-man-pages.pot` and add a zh_TW.po and delete the old manpage files, right?

It seems there is a large amount of text, so I don't think I can finish all of them.
I will try to translate them partly.

**Comment by hallyn** [comment]
Thank you - any bit will help.

**Comment by zica87** [comment]
So I should translate `shadow-man-pages.pot` and add a zh_TW.po and delete the old manpage files.

Is that correct?
Anything missing or wrong?

**Comment by hallyn** [comment]
I believe so - though I'm really not sure what the recommended way to start a new translation is.

In https://github.com/shadow-maint/shadow/pull/532 , @yurchor added Ukrainian translations. Yuri, what did you use as the base for your man/po/uk.po?

**Comment by yurchor** [comment]
> In #532 , @yurchor added Ukrainian translations. Yuri, what did you use as the base for your man/po/uk.po?

Hi,

shadow-man-pages.pot is 4 years old now. It should be updated before starting your translation (make po-update after reconfiguring shadow). Thus,

./autogen.sh
cd ./man/po
make update-po

Hope this helps.

**Comment by hallyn** [comment]
Thanks @yurchor

**Comment by hallyn** [comment]
https://github.com/shadow-maint/shadow/pull/751 as a first step to help out future contributors.

**Comment by zica87** [comment]
Closing this since I found I don't have time for this.
I am sorry for taking up your time and creating false expectations.
I will create PR if I have time in the future.
