### ISSUE TITLE
Why are files in the /etc/shadow-maint directory removed from the shadow-4.13.tar.gz tar package of the official version 4.13?

### ISSUE THREAD

**Issue by wyj611** [shadow-maint/shadow#784]
![image](https://github.com/shadow-maint/shadow/assets/22022968/25d21be0-fa49-47f6-aef4-cc88a223fdb5)

**Comment by wyj611** [comment]
The source code contains the folder:
![image](https://github.com/shadow-maint/shadow/assets/22022968/893948bd-b47e-4f27-aceb-55e8e49c2c7d)

**Comment by hallyn** [comment]
'removed' implies that earlier releases had them.  Can you confirm an earlier release had these files?

Looking at the git history, it looks like those files were just never added to the list of files to distribute, in etc/Makefile.am
