### ISSUE TITLE
Consider adding an option to remove user journals on userdel

### ISSUE THREAD

**Issue by hussamT** [shadow-maint/shadow#79]
Maybe systemd should be handling this itself but just in case,
would it be possible to have userdel have an option to remove /var/log/journal/<machine_id>/user-1001*.journal when the user with id 1001 is deleted?
This would prevent the next user with the same id from reading the old user's data.
For example, when doing userdel testuser2 and useradd testuser3 since they will have the same user id.
userdel already offers to remove mail spool data through an option.

**Comment by hallyn** [comment]
Something like /etc/shadow/userdel.d/* ?

It's not a small undertaking and not one i have time for, but i support the idea.
