### ISSUE TITLE
After shadow 4.14, utmp is never updated at an initial login 

### ISSUE THREAD

**Issue by NaofumiHonda** [shadow-maint/shadow#805]
I compile shadow 4.14 with --disable-logind (i.e.,  ENABLE_LOGIND == 0).
When I login into the system,  no new entry is added in utmp with shadow 4.14.

In 4.14, the function update_utmp() is moved from login.c to utmp.c.
And it is modified a little bit, which causes the different behavior from the one in 4.13:
For example, if get_current_utmp() in update_utmp() returns NULL,
a new entry is added in utmp with 4.13, but  just return with 4.14.
Hence a new entry is never added at the initial login.

Another problem is that,
the caller of update_utmp() expects 0 if success, but
it really returns 1 when success. 
Thus the caller always thinks update_utmp() fails.

**Comment by ikerexxe** [comment]
Can you check if https://github.com/shadow-maint/shadow/pull/808 fixes the problem?

**Comment by NaofumiHonda** [comment]
It's perfect. Thanks!
