### ISSUE TITLE
4.14.1: Missing chain of trust for release

### ISSUE THREAD

**Issue by dvzrv** [shadow-maint/shadow#815]
Hi! I package shadow for Arch Linux.
We verify OpenPGP signatures of upstreams to increase the security of our supply chain. This also happens with this project.

All releases up to 4.14.1 have been signed by @hallyn using `66D0387DB85D320F8408166DB175CFA98F192AF2`, which is locked in our build script: https://gitlab.archlinux.org/archlinux/packaging/packages/shadow/-/blob/16ecf814a48dce4c56adb501b304e2207e78b21b/PKGBUILD#L65

4.14.1 has been signed by @alejandro-colomar using `A9348594CE31283A826FBDD8D57633D441E25BB5`. However, there are neither signatures available by `66D0387DB85D320F8408166DB175CFA98F192AF2` on one of the user IDs on `A9348594CE31283A826FBDD8D57633D441E25BB5` (at least not with any key I could find on any of the keyservers I use for that: https://keyserver.ubuntu.com/ and https://keys.openpgp.org/), nor is @alejandro-colomar listed as maintainer in the authors file: https://github.com/shadow-maint/shadow/blob/0d50e1e15f749467fa3f93386d15b8651dd5d2bf/AUTHORS.md?plain=1#L5-L11

The use of this new (and so far untrusted) certificate for signing releases blocks us from updating shadow.

Please establish cryptographic trust between the two certificates by either having `A9348594CE31283A826FBDD8D57633D441E25BB5` sign a user ID on `66D0387DB85D320F8408166DB175CFA98F192AF2` and publishing this updated certificate here and/or on the relevant keyservers, or by adding @alejandro-colomar  (specifically mentioning `66D0387DB85D320F8408166DB175CFA98F192AF2` as valid certificate for signing releases) in a *signed* commit.

Thank you!

**Comment by ikerexxe** [comment]
I guess Serge could sign our keys to establish a trust, and then add those keys to a file in this repository, so that anybody can check them when the time comes.

**Comment by hallyn** [comment]
Sign your keys and push them to some public keyserver?

**Comment by dvzrv** [comment]
> Sign your keys and push them to some public keyserver?

Yes, signing and publishing the signatures would already help.
Making the AUTHORS file more future proof (e.g. by providing relevant info in there including key fingerprints in a signed commit), would also be very good.

**Comment by dvzrv** [comment]
@hallyn this issue is blocking upgrades on downstream distributions right now. Would it be possible for you to create the signatures and push them? Thank you! :)

**Comment by hallyn** [comment]
Sorry, will do it this afternoon.  If I have not done in in 8 hours please scold me.

**Comment by hallyn** [comment]
How about https://github.com/shadow-maint/shadow/pull/825 ?

**Comment by dvzrv** [comment]
Apart from missing the certificate files (and your own fingerprint?) this already lets me proceed. Thank you!
