### ISSUE TITLE
RFC: nss module for automatically give all users a full sub(u/g)id range

### ISSUE THREAD

**Issue by AndersBlomdell** [shadow-maint/shadow#819]
We want all our users to be able to run containers, hence I wrote the [subid_maximal.txt](https://github.com/shadow-maint/shadow/files/12866207/subid_maximal.txt) nss plugin that gives all users with uid between 1-65533 the full range of (65536) of sub(u/g)id's

Sorry for placing C code in a .txt file...

[subid_maximal.txt](https://github.com/shadow-maint/shadow/files/12866216/subid_maximal.txt)

**Comment by ikerexxe** [comment]
Is this a bug, or a way of sharing your code? It's not clear to me.

In any case, your proposal would exhaust the subid's range, so if you had any centrally managed user they would be unable to use subids.

**Comment by AndersBlomdell** [comment]
A way of sharing my code.

As long as the centrally administered users uid falls within 1-65533 they will have subids on systems where /etc/nsswitch.conf has a `subid: maximal` entry (this is the case here where some users [students] are centrally administered but without centrally administered subid's)

**Comment by hallyn** [comment]
Thanks - maybe we should have a shadow discuss instance or subreddit or something for sharing things like this.
