### ISSUE TITLE
groups(1) optional at configure?

### ISSUE THREAD

**Issue by dkwo** [shadow-maint/shadow#842]
is it possible to make the build and install of `groups(1)` (as well as its man pages and possibly pam files) optional at configure time, as one may want to install the corresponding command from gnu coreutils?

**Comment by jubalh** [comment]
In case you are a distro maintainer you could just remove them in the build recipe.

**Comment by dkwo** [comment]
of course, currently most distros either patch the makefile or just remove the build artifacts.
i thought this is something upstream might want to take care of directly.

**Comment by jubalh** [comment]
Personally I don't see a reason for it.

**Comment by dkwo** [comment]
I see, thanks.
