### ISSUE TITLE
getsubids doesn't work on Steam Deck (Steam OS - arch linux)

### ISSUE THREAD

**Issue by kingoftheconnors** [shadow-maint/shadow#883]
The version of getsubids on Steam Deck is 4.11.1-2. When I try to run the command `getsubids deck`, it returns `Error fetching ranges`

Any ideas why?

**Comment by hallyn** [comment]
Can you show the contents and permissions of /etc/nsswitch.conf and /etc/subuid ?

**Comment by kingoftheconnors** [comment]
Update on this, the Steam Deck had updates that used a more recent version of getsubids. I updated it and the issue no longer occurs. Unfortuantely, I can't tell you what about those files could have caused the issue, but I'll close this issue since it shouldn't be a problem in the future
