### ISSUE TITLE
What the package named in repo

### ISSUE THREAD

**Issue by kwekewk** [shadow-maint/shadow#905]
I having issue searching correct package name in apt, I'm trying to install getsubids, but unable to locate shadow. Unless I compiled it from source

**Comment by ikerexxe** [comment]
This seems more like a distribution issue, so I'd recommend you to open a ticket in your distributions tracking system. When opening it, I would recommend that you indicate the version of the distribution you are using, as the package name may change.

For your reference, in Fedora that binary is packed in shadow-utils-subid.

**Comment by lslebodn** [comment]
the apt-file utility can search even for content in dep packages;
* https://wiki.debian.org/apt-file

or you can use web-ui :-)
* https://packages.debian.org/search?searchon=contents&keywords=getsubids&mode=exactfilename&suite=stable&arch=any

So for debian stable, the binary getsubids is in the package uidmap
* https://packages.debian.org/bookworm/amd64/uidmap/filelist

**Comment by kwekewk** [comment]
It start available from lunar 
https://packages.ubuntu.com/search?searchon=sourcenames&keywords=shadow
