### ISSUE TITLE
pwck does not moan about entries with wrong column count

### ISSUE THREAD

**Issue by Nightwulf** [shadow-maint/shadow#94]
The pwck tool checks the entries of /etc/passed and /etc/shadow for correctnes.
At least the pwck tool in version 4.5 of the shadow suite does not moan about entries with 8 columns.

Example: add a line like this in /etc/passed and run pwck:
`clamav:x:64:64:ClamAntiVirus:/dev/null:/bin/:/usr/bin/nologin`

pwck does not complain.

**Comment by jgmdev** [comment]
A similar issue occurs with grpck (/etc/group), for example: 'users:x:100:http:myuser' which should be 'users:x:100:http,myuser' isn't detected as an error so grpck doesn't complains about anything. This kind of behavior makes it harder to trouble shoot syntax errors that cause issues on software that read the related files like systemd-sysusers.

**Comment by hallyn** [comment]
Closed with #175, thanks.
