### ISSUE TITLE
How do you compile this from source?

### ISSUE THREAD

**Issue by Arinerron** [shadow-maint/shadow#95]
I can't seem to find out how to compile this. Would someone mind writing simple steps or providing a link? Thanks.

**Comment by Arinerron** [comment]
Thanks. Is there a requirements file or something? Now I'm getting:

```
configure: error: semanage/semanage.h is missing
```

I installed the selinux headers for my distro already.

**Comment by vapier** [comment]
just pass `--without-selinux` if you don't have the deps

**Comment by Arinerron** [comment]
Thanks. Where are the binaries once compiled? I checked src, and they aren't there. No bin folder either.

**Comment by cyphar** [comment]
Building this project follows the common autotools workflow:

```
% autoreconf -i # or autogen.sh if you prefer
% ./configure # generates the makefiles and other scripts
% make # actually does the build
% make install # optional -- installs the binaries
```

After `make` the binaries will be in `src/`.

**Comment by Arinerron** [comment]
@cyphar Thanks a lot, that worked! Have a great day.
