### ISSUE TITLE
[pwck] Segmentation fault when executing on a nonexistent passwd file

### ISSUE THREAD

**Issue by integeruser** [shadow-maint/shadow#96]
Hello,

executing `pwck` on a nonexistent `passwd` file results in a segmentation fault:
```sh
root@lambda ~# pwck /tmp/nonexistent
fish: “pwck /tmp/nonexistent” terminated by signal SIGSEGV (Address boundary error)
```

This bug is present in the version of the tool currently shipped in Arch Linux,
```sh
root@lambda ~# uname -a
Linux lambda 4.15.2-2-ARCH #1 SMP PREEMPT Thu Feb 8 18:54:52 UTC 2018 x86_64 GNU/Linux
root@lambda ~# pacman -Qi shadow
Name            : shadow
Version         : 4.5-4
. . .
```
but was probably already observed on 2017-04-10 as mentioned in [this post](https://bbs.archlinux.org/viewtopic.php?pid=1703400#p1703400) from the Arch Linux Forums. Moreover, I compiled (`--without-selinux`) the code from this repository and verified the bug is present in both the tag `4.5` and the latest commit.

A brief debugging session revealed that the segmentation fault happens in `commonio_close()` and is caused by a call to `fclose()` with a null pointer argument. Backtrace:
```sh
[#0] 0x7ffff7a8dc64 → Name: fclose@@GLIBC_2.2.5()
[#1] 0x555555559940 → Name: commonio_close.part()
[#2] 0x55555555ab26 → Name: commonio_unlock()
[#3] 0x55555555707f → Name: main()
```

Relevant snippets from [`lib/commonio.c`](https://github.com/shadow-maint/shadow/blob/4.5/lib/commonio.c) (tag `4.5`):
```c
int commonio_close (struct commonio_db *db)
    /*@requires notnull db->fp@*/
{
    . . .
    if (!db->changed || db->readonly) {
        (void) fclose (db->fp);
        . . .
    }
    . . .
}
```
```c
int commonio_unlock (struct commonio_db *db)
{
    . . .
    if (db->isopen) {
        db->readonly = true;
        if (commonio_close (db) == 0) {
            . . .
        }
    }
    . . .
}
```
```c
int commonio_open (struct commonio_db *db, int mode)
{
    . . .
    /*
     * If O_CREAT was specified and the file didn't exist, it will be
     * created by commonio_close().  We have no entries to read yet.  --marekm
     */
    if (NULL == db->fp) {
        if (((flags & O_CREAT) != 0) && (ENOENT == errno)) {
            db->isopen = true;
            return 1;
        }
        return 0;
    }
    . . .
}
```

I have not investigated the issue further. Note that executing `pwck` in read-only mode does not trigger the bug:
```sh
root@lambda ~# pwck -r /tmp/nonexistent
pwck: cannot open /tmp/nonexistent
```

**Comment by hallyn** [comment]
Indeed this seems to be a regression - 3.5.39 in Ubuntu does not exhibit this behavior, but I reproduced it with upstream.  Thanks.

**Comment by hallyn** [comment]
Well somehow ee43f47f4521eda0ee9773f48de85058965653e8 is to blame (@xnox )  dunno why yet.

**Comment by hallyn** [comment]
This seems to be a result of some spaghetti code disagreeing on whether success is 0 or not 0
