### ISSUE TITLE
shadow 4.15.0 complains about unknown configuration option

### ISSUE THREAD

**Issue by jubalh** [shadow-maint/shadow#967]
Running `useradd` we get the following logged:

```
usermod[2998]: shadow: unknown configuration item 'MOTD_FILE' in '/usr/etc/login.defs'                     
usermod[2998]: shadow: unknown configuration item 'ENV_ROOTPATH' in '/usr/etc/login.defs'                  
usermod[2998]: shadow: unknown configuration item 'ALWAYS_SET_PATH' in '/usr/etc/login.defs'
usermod[2998]: shadow: unknown configuration item 'LOGIN_KEEP_USERNAME' in '/usr/etc   
```

With 4.14.6 this doesn't happen.
Might be related to https://github.com/shadow-maint/shadow/pull/814 / https://github.com/shadow-maint/shadow/commit/fa68441bc4be8edeaad8d104344e987b31ed44e6?

openQA [Test](https://openqa.opensuse.org/tests/4003180#step/journal_check/9).

**Comment by DimStar77** [comment]
originally introduced here https://github.com/shadow-maint/shadow/commit/71c6165dcd6b808fc1bf11e0dfb3692beb06221c

i.e we already had a log function for (partially) unknown  / external util entries.

**Comment by alejandro-colomar** [comment]
> Might be related to #814 / [fa68441](https://github.com/shadow-maint/shadow/commit/fa68441bc4be8edeaad8d104344e987b31ed44e6)?

Maybe @hallyn knows.

**Comment by ikerexxe** [comment]
This issue has also been reported for [Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=2265291). I put it here for the sake of it .

**Comment by hallyn** [comment]
Hm, the only nuisance I see here is:

useradd: failed to reset the lastlog entry of UID 1003: Success

Still trying to make sense of the unknown configuration message...

**Comment by hallyn** [comment]
Oh, @DimStar77 , thank you - yes, that's the problem here.  That fix was undone.  (That's the passive way of saying - I undid it :)
