### ISSUE TITLE
Remote login issue and questions

### ISSUE THREAD

**Issue by alejandro-colomar** [shadow-maint/shadow#992]
In
<https://github.com/shadow-maint/shadow/blob/18ecf3987eca055a4caf8dad5bb61442fe8864e6/lib/rlogin.c#L49-L65>

Specifically
<https://github.com/shadow-maint/shadow/blob/18ecf3987eca055a4caf8dad5bb61442fe8864e6/lib/rlogin.c#L59-L62>

This is silently truncating the string.  What should we do?  I don't understand remote login, so I'm hesitant to touch it; but who uses it?  Is it from times when SSH didn't exist?  Should we consider removing support?

**Comment by alejandro-colomar** [comment]
@ikerexxe Do you know anything about this remote login?  I'm thinking of writing a patch for removing that functionality.

**Comment by alejandro-colomar** [comment]
Let's inform some other downstreams, in case they have any comments:

Cc: @jubalh , @thesamesam

**Comment by alejandro-colomar** [comment]
Since there was also some reference to some ruserok() patch in void linux (<https://github.com/void-linux/void-packages/pull/48813>), let's also cc some more people:

Cc: @dataCobra, @dkwo

**Comment by ikerexxe** [comment]
I didn't notice this functionality until now. From a quick glance it seems that the remote login is supposed to be performed using the serial port, thus the speed table.

If nobody complains I'm fine with removing this functionality.
